module Onlyfans
  module Models
    module Statistics
      type reach_get_profile_visitors_params =
        {
          account: String,
          end_date: String,
          start_date: String,
          filter: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::filter?,
          limit: Integer?,
          type: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::type_?
        }
        & Onlyfans::Internal::Type::request_parameters

      class ReachGetProfileVisitorsParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor end_date: String

        attr_accessor start_date: String

        attr_accessor filter: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::filter?

        attr_accessor limit: Integer?

        attr_accessor type: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::type_?

        def initialize: (
          account: String,
          end_date: String,
          start_date: String,
          ?filter: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::filter?,
          ?limit: Integer?,
          ?type: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::type_?,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          end_date: String,
          start_date: String,
          filter: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::filter?,
          limit: Integer?,
          type: Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::type_?,
          request_options: Onlyfans::RequestOptions
        }

        type filter = :chart | :topCountries

        module Filter
          extend Onlyfans::Internal::Type::Enum

          CHART: :chart
          TOP_COUNTRIES: :topCountries

          def self?.values: -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::filter]
        end

        type type_ = :total | :users | :guests

        module Type
          extend Onlyfans::Internal::Type::Enum

          TOTAL: :total
          USERS: :users
          GUESTS: :guests

          def self?.values: -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsParams::type_]
        end
      end
    end
  end
end
