module Onlyfans
  module Models
    module Statistics
      type reach_get_profile_visitors_response =
        Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0
        | Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1
        | Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2

      module ReachGetProfileVisitorsResponse
        extend Onlyfans::Internal::Type::Union

        type union_member0 =
          {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data
          }

        class UnionMember0 < Onlyfans::Internal::Type::BaseModel
          attr_reader _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta?

          def _meta=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta

          attr_reader data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data?

          def data=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data

          def initialize: (
            ?_meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta,
            ?data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data
          ) -> void

          def to_hash: -> {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data
          }

          type meta =
            {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits
            }

          class Meta < Onlyfans::Internal::Type::BaseModel
            attr_reader _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache?

            def _cache=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache

            attr_reader _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits?

            def _credits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits

            attr_reader _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits?

            def _rate_limits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits

            def initialize: (
              ?_cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache,
              ?_credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits,
              ?_rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits
            ) -> void

            def to_hash: -> {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Meta::RateLimits
            }

            type cache = { is_cached: bool, note: String }

            class Cache < Onlyfans::Internal::Type::BaseModel
              attr_reader is_cached: bool?

              def is_cached=: (bool) -> bool

              attr_reader note: String?

              def note=: (String) -> String

              def initialize: (?is_cached: bool, ?note: String) -> void

              def to_hash: -> { is_cached: bool, note: String }
            end

            type credits = { balance: Integer, note: String, used: Integer }

            class Credits < Onlyfans::Internal::Type::BaseModel
              attr_reader balance: Integer?

              def balance=: (Integer) -> Integer

              attr_reader note: String?

              def note=: (String) -> String

              attr_reader used: Integer?

              def used=: (Integer) -> Integer

              def initialize: (
                ?balance: Integer,
                ?note: String,
                ?used: Integer
              ) -> void

              def to_hash: -> { balance: Integer, note: String, used: Integer }
            end

            type rate_limits =
              {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }

            class RateLimits < Onlyfans::Internal::Type::BaseModel
              attr_reader limit_day: Integer?

              def limit_day=: (Integer) -> Integer

              attr_reader limit_minute: Integer?

              def limit_minute=: (Integer) -> Integer

              attr_reader remaining_day: Integer?

              def remaining_day=: (Integer) -> Integer

              attr_reader remaining_minute: Integer?

              def remaining_minute=: (Integer) -> Integer

              def initialize: (
                ?limit_day: Integer,
                ?limit_minute: Integer,
                ?remaining_day: Integer,
                ?remaining_minute: Integer
              ) -> void

              def to_hash: -> {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }
            end
          end

          type data =
            {
              chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart,
              has_stats: bool,
              is_available: bool,
              top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries,
              top_duration_users: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers,
              total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total
            }

          class Data < Onlyfans::Internal::Type::BaseModel
            attr_reader chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart?

            def chart=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart

            attr_reader has_stats: bool?

            def has_stats=: (bool) -> bool

            attr_reader is_available: bool?

            def is_available=: (bool) -> bool

            attr_reader top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries?

            def top_countries=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries

            attr_reader top_duration_users: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers?

            def top_duration_users=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers

            attr_reader total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total?

            def total=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total

            def initialize: (
              ?chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart,
              ?has_stats: bool,
              ?is_available: bool,
              ?top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries,
              ?top_duration_users: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers,
              ?total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total
            ) -> void

            def to_hash: -> {
              chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart,
              has_stats: bool,
              is_available: bool,
              top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries,
              top_duration_users: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers,
              total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Total
            }

            type chart =
              {
                duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration],
                visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]
              }

            class Chart < Onlyfans::Internal::Type::BaseModel
              attr_reader duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration]?

              def duration=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration]

              attr_reader visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]?

              def visitors=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]

              def initialize: (
                ?duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration],
                ?visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]
              ) -> void

              def to_hash: -> {
                duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Duration],
                visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::Chart::Visitor]
              }

              type duration = { count: Integer, date: String }

              class Duration < Onlyfans::Internal::Type::BaseModel
                attr_reader count: Integer?

                def count=: (Integer) -> Integer

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Integer, ?date: String) -> void

                def to_hash: -> { count: Integer, date: String }
              end

              type visitor = { count: Integer, date: String }

              class Visitor < Onlyfans::Internal::Type::BaseModel
                attr_reader count: Integer?

                def count=: (Integer) -> Integer

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Integer, ?date: String) -> void

                def to_hash: -> { count: Integer, date: String }
              end
            end

            type top_countries =
              {
                has_more: bool,
                rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row],
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals
              }

            class TopCountries < Onlyfans::Internal::Type::BaseModel
              attr_reader has_more: bool?

              def has_more=: (bool) -> bool

              attr_reader rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row]?

              def rows=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row]

              attr_reader totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals?

              def totals=: (
                Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals
              ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals

              def initialize: (
                ?has_more: bool,
                ?rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row],
                ?totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals
              ) -> void

              def to_hash: -> {
                has_more: bool,
                rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row],
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Totals
              }

              type row =
                {
                  country_code: String,
                  country_name: String,
                  rank: Integer,
                  views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount
                }

              class Row < Onlyfans::Internal::Type::BaseModel
                attr_reader country_code: String?

                def country_code=: (String) -> String

                attr_reader country_name: String?

                def country_name=: (String) -> String

                attr_reader rank: Integer?

                def rank=: (Integer) -> Integer

                attr_reader views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount?

                def views_count=: (
                  Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount
                ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount

                def initialize: (
                  ?country_code: String,
                  ?country_name: String,
                  ?rank: Integer,
                  ?views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount
                ) -> void

                def to_hash: -> {
                  country_code: String,
                  country_name: String,
                  rank: Integer,
                  views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopCountries::Row::ViewsCount
                }

                type views_count =
                  {
                    guests: Integer,
                    subscribers: Integer,
                    total: Integer,
                    users: Integer
                  }

                class ViewsCount < Onlyfans::Internal::Type::BaseModel
                  attr_reader guests: Integer?

                  def guests=: (Integer) -> Integer

                  attr_reader subscribers: Integer?

                  def subscribers=: (Integer) -> Integer

                  attr_reader total: Integer?

                  def total=: (Integer) -> Integer

                  attr_reader users: Integer?

                  def users=: (Integer) -> Integer

                  def initialize: (
                    ?guests: Integer,
                    ?subscribers: Integer,
                    ?total: Integer,
                    ?users: Integer
                  ) -> void

                  def to_hash: -> {
                    guests: Integer,
                    subscribers: Integer,
                    total: Integer,
                    users: Integer
                  }
                end
              end

              type totals =
                {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }

              class Totals < Onlyfans::Internal::Type::BaseModel
                attr_reader guests: String?

                def guests=: (String) -> String

                attr_reader subscribers: Integer?

                def subscribers=: (Integer) -> Integer

                attr_reader total: Integer?

                def total=: (Integer) -> Integer

                attr_reader users: String?

                def users=: (String) -> String

                def initialize: (
                  ?guests: String,
                  ?subscribers: Integer,
                  ?total: Integer,
                  ?users: String
                ) -> void

                def to_hash: -> {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }
              end
            end

            type top_duration_users =
              {
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals
              }

            class TopDurationUsers < Onlyfans::Internal::Type::BaseModel
              attr_reader totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals?

              def totals=: (
                Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals
              ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals

              def initialize: (
                ?totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals
              ) -> void

              def to_hash: -> {
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember0::Data::TopDurationUsers::Totals
              }

              type totals =
                {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }

              class Totals < Onlyfans::Internal::Type::BaseModel
                attr_reader guests: String?

                def guests=: (String) -> String

                attr_reader subscribers: Integer?

                def subscribers=: (Integer) -> Integer

                attr_reader total: Integer?

                def total=: (Integer) -> Integer

                attr_reader users: String?

                def users=: (String) -> String

                def initialize: (
                  ?guests: String,
                  ?subscribers: Integer,
                  ?total: Integer,
                  ?users: String
                ) -> void

                def to_hash: -> {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }
              end
            end

            type total = { current: String, delta: Float }

            class Total < Onlyfans::Internal::Type::BaseModel
              attr_reader current: String?

              def current=: (String) -> String

              attr_reader delta: Float?

              def delta=: (Float) -> Float

              def initialize: (?current: String, ?delta: Float) -> void

              def to_hash: -> { current: String, delta: Float }
            end
          end
        end

        type union_member1 =
          {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data
          }

        class UnionMember1 < Onlyfans::Internal::Type::BaseModel
          attr_reader _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta?

          def _meta=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta

          attr_reader data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data?

          def data=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data

          def initialize: (
            ?_meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta,
            ?data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data
          ) -> void

          def to_hash: -> {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data
          }

          type meta =
            {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits
            }

          class Meta < Onlyfans::Internal::Type::BaseModel
            attr_reader _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache?

            def _cache=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache

            attr_reader _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits?

            def _credits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits

            attr_reader _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits?

            def _rate_limits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits

            def initialize: (
              ?_cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache,
              ?_credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits,
              ?_rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits
            ) -> void

            def to_hash: -> {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Meta::RateLimits
            }

            type cache = { is_cached: bool, note: String }

            class Cache < Onlyfans::Internal::Type::BaseModel
              attr_reader is_cached: bool?

              def is_cached=: (bool) -> bool

              attr_reader note: String?

              def note=: (String) -> String

              def initialize: (?is_cached: bool, ?note: String) -> void

              def to_hash: -> { is_cached: bool, note: String }
            end

            type credits = { balance: Integer, note: String, used: Integer }

            class Credits < Onlyfans::Internal::Type::BaseModel
              attr_reader balance: Integer?

              def balance=: (Integer) -> Integer

              attr_reader note: String?

              def note=: (String) -> String

              attr_reader used: Integer?

              def used=: (Integer) -> Integer

              def initialize: (
                ?balance: Integer,
                ?note: String,
                ?used: Integer
              ) -> void

              def to_hash: -> { balance: Integer, note: String, used: Integer }
            end

            type rate_limits =
              {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }

            class RateLimits < Onlyfans::Internal::Type::BaseModel
              attr_reader limit_day: Integer?

              def limit_day=: (Integer) -> Integer

              attr_reader limit_minute: Integer?

              def limit_minute=: (Integer) -> Integer

              attr_reader remaining_day: Integer?

              def remaining_day=: (Integer) -> Integer

              attr_reader remaining_minute: Integer?

              def remaining_minute=: (Integer) -> Integer

              def initialize: (
                ?limit_day: Integer,
                ?limit_minute: Integer,
                ?remaining_day: Integer,
                ?remaining_minute: Integer
              ) -> void

              def to_hash: -> {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }
            end
          end

          type data =
            {
              chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart,
              has_stats: bool,
              is_available: bool,
              total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total
            }

          class Data < Onlyfans::Internal::Type::BaseModel
            attr_reader chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart?

            def chart=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart

            attr_reader has_stats: bool?

            def has_stats=: (bool) -> bool

            attr_reader is_available: bool?

            def is_available=: (bool) -> bool

            attr_reader total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total?

            def total=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total

            def initialize: (
              ?chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart,
              ?has_stats: bool,
              ?is_available: bool,
              ?total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total
            ) -> void

            def to_hash: -> {
              chart: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart,
              has_stats: bool,
              is_available: bool,
              total: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Total
            }

            type chart =
              {
                duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration],
                visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]
              }

            class Chart < Onlyfans::Internal::Type::BaseModel
              attr_reader duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration]?

              def duration=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration]

              attr_reader visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]?

              def visitors=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]

              def initialize: (
                ?duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration],
                ?visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]
              ) -> void

              def to_hash: -> {
                duration: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Duration],
                visitors: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember1::Data::Chart::Visitor]
              }

              type duration = { count: Integer, date: String }

              class Duration < Onlyfans::Internal::Type::BaseModel
                attr_reader count: Integer?

                def count=: (Integer) -> Integer

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Integer, ?date: String) -> void

                def to_hash: -> { count: Integer, date: String }
              end

              type visitor = { count: Integer, date: String }

              class Visitor < Onlyfans::Internal::Type::BaseModel
                attr_reader count: Integer?

                def count=: (Integer) -> Integer

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Integer, ?date: String) -> void

                def to_hash: -> { count: Integer, date: String }
              end
            end

            type total = { current: String, delta: Float }

            class Total < Onlyfans::Internal::Type::BaseModel
              attr_reader current: String?

              def current=: (String) -> String

              attr_reader delta: Float?

              def delta=: (Float) -> Float

              def initialize: (?current: String, ?delta: Float) -> void

              def to_hash: -> { current: String, delta: Float }
            end
          end
        end

        type union_member2 =
          {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data
          }

        class UnionMember2 < Onlyfans::Internal::Type::BaseModel
          attr_reader _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta?

          def _meta=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta

          attr_reader data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data?

          def data=: (
            Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data
          ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data

          def initialize: (
            ?_meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta,
            ?data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data
          ) -> void

          def to_hash: -> {
            _meta: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta,
            data: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data
          }

          type meta =
            {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits
            }

          class Meta < Onlyfans::Internal::Type::BaseModel
            attr_reader _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache?

            def _cache=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache

            attr_reader _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits?

            def _credits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits

            attr_reader _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits?

            def _rate_limits=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits

            def initialize: (
              ?_cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache,
              ?_credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits,
              ?_rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits
            ) -> void

            def to_hash: -> {
              _cache: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Cache,
              _credits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::Credits,
              _rate_limits: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Meta::RateLimits
            }

            type cache = { is_cached: bool, note: String }

            class Cache < Onlyfans::Internal::Type::BaseModel
              attr_reader is_cached: bool?

              def is_cached=: (bool) -> bool

              attr_reader note: String?

              def note=: (String) -> String

              def initialize: (?is_cached: bool, ?note: String) -> void

              def to_hash: -> { is_cached: bool, note: String }
            end

            type credits = { balance: Integer, note: String, used: Integer }

            class Credits < Onlyfans::Internal::Type::BaseModel
              attr_reader balance: Integer?

              def balance=: (Integer) -> Integer

              attr_reader note: String?

              def note=: (String) -> String

              attr_reader used: Integer?

              def used=: (Integer) -> Integer

              def initialize: (
                ?balance: Integer,
                ?note: String,
                ?used: Integer
              ) -> void

              def to_hash: -> { balance: Integer, note: String, used: Integer }
            end

            type rate_limits =
              {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }

            class RateLimits < Onlyfans::Internal::Type::BaseModel
              attr_reader limit_day: Integer?

              def limit_day=: (Integer) -> Integer

              attr_reader limit_minute: Integer?

              def limit_minute=: (Integer) -> Integer

              attr_reader remaining_day: Integer?

              def remaining_day=: (Integer) -> Integer

              attr_reader remaining_minute: Integer?

              def remaining_minute=: (Integer) -> Integer

              def initialize: (
                ?limit_day: Integer,
                ?limit_minute: Integer,
                ?remaining_day: Integer,
                ?remaining_minute: Integer
              ) -> void

              def to_hash: -> {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }
            end
          end

          type data =
            {
              has_stats: bool,
              is_available: bool,
              top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries
            }

          class Data < Onlyfans::Internal::Type::BaseModel
            attr_reader has_stats: bool?

            def has_stats=: (bool) -> bool

            attr_reader is_available: bool?

            def is_available=: (bool) -> bool

            attr_reader top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries?

            def top_countries=: (
              Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries
            ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries

            def initialize: (
              ?has_stats: bool,
              ?is_available: bool,
              ?top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries
            ) -> void

            def to_hash: -> {
              has_stats: bool,
              is_available: bool,
              top_countries: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries
            }

            type top_countries =
              {
                has_more: bool,
                rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row],
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals
              }

            class TopCountries < Onlyfans::Internal::Type::BaseModel
              attr_reader has_more: bool?

              def has_more=: (bool) -> bool

              attr_reader rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row]?

              def rows=: (
                ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row]
              ) -> ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row]

              attr_reader totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals?

              def totals=: (
                Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals
              ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals

              def initialize: (
                ?has_more: bool,
                ?rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row],
                ?totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals
              ) -> void

              def to_hash: -> {
                has_more: bool,
                rows: ::Array[Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row],
                totals: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Totals
              }

              type row =
                {
                  country_code: String,
                  country_name: String,
                  rank: Integer,
                  views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount
                }

              class Row < Onlyfans::Internal::Type::BaseModel
                attr_reader country_code: String?

                def country_code=: (String) -> String

                attr_reader country_name: String?

                def country_name=: (String) -> String

                attr_reader rank: Integer?

                def rank=: (Integer) -> Integer

                attr_reader views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount?

                def views_count=: (
                  Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount
                ) -> Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount

                def initialize: (
                  ?country_code: String,
                  ?country_name: String,
                  ?rank: Integer,
                  ?views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount
                ) -> void

                def to_hash: -> {
                  country_code: String,
                  country_name: String,
                  rank: Integer,
                  views_count: Onlyfans::Models::Statistics::ReachGetProfileVisitorsResponse::UnionMember2::Data::TopCountries::Row::ViewsCount
                }

                type views_count =
                  {
                    guests: Integer,
                    subscribers: Integer,
                    total: Integer,
                    users: Integer
                  }

                class ViewsCount < Onlyfans::Internal::Type::BaseModel
                  attr_reader guests: Integer?

                  def guests=: (Integer) -> Integer

                  attr_reader subscribers: Integer?

                  def subscribers=: (Integer) -> Integer

                  attr_reader total: Integer?

                  def total=: (Integer) -> Integer

                  attr_reader users: Integer?

                  def users=: (Integer) -> Integer

                  def initialize: (
                    ?guests: Integer,
                    ?subscribers: Integer,
                    ?total: Integer,
                    ?users: Integer
                  ) -> void

                  def to_hash: -> {
                    guests: Integer,
                    subscribers: Integer,
                    total: Integer,
                    users: Integer
                  }
                end
              end

              type totals =
                {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }

              class Totals < Onlyfans::Internal::Type::BaseModel
                attr_reader guests: String?

                def guests=: (String) -> String

                attr_reader subscribers: Integer?

                def subscribers=: (Integer) -> Integer

                attr_reader total: Integer?

                def total=: (Integer) -> Integer

                attr_reader users: String?

                def users=: (String) -> String

                def initialize: (
                  ?guests: String,
                  ?subscribers: Integer,
                  ?total: Integer,
                  ?users: String
                ) -> void

                def to_hash: -> {
                  guests: String,
                  subscribers: Integer,
                  total: Integer,
                  users: String
                }
              end
            end
          end
        end

        def self?.variants: -> ::Array[Onlyfans::Models::Statistics::reach_get_profile_visitors_response]
      end
    end
  end
end
