module Onlyfans
  module Models
    module SharedTrackingLinks
      type tag_remove_response =
        {
          _meta: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta,
          data: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data
        }

      class TagRemoveResponse < Onlyfans::Internal::Type::BaseModel
        attr_reader _meta: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta?

        def _meta=: (
          Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta
        ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta

        attr_reader data: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data?

        def data=: (
          Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data
        ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data

        def initialize: (
          ?_meta: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta,
          ?data: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta,
          data: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Data
        }

        type meta =
          {
            _cache: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache,
            _credits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits
          }

        class Meta < Onlyfans::Internal::Type::BaseModel
          attr_reader _cache: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache?

          def _cache=: (
            Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache
          ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache

          attr_reader _credits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits?

          def _credits=: (
            Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits
          ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits
          ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache,
            ?_credits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits,
            ?_rate_limits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Cache,
            _credits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfans::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfans::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfans::Internal::Type::BaseModel
            attr_accessor limit_day: String?

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader notice: String?

            def notice=: (String) -> String

            attr_accessor remaining_day: String?

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: String?,
              ?limit_minute: Integer,
              ?notice: String,
              ?remaining_day: String?,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }
          end
        end

        type data = { tags: ::Array[String] }

        class Data < Onlyfans::Internal::Type::BaseModel
          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (?tags: ::Array[String]) -> void

          def to_hash: -> { tags: ::Array[String] }
        end
      end
    end
  end
end
