module Onlyfansapi
  module Resources
    class TrackingLinks
      class Tags
        def list: (
          Integer tracking_link_id,
          account: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::TrackingLinks::TagListResponse

        def add: (
          Integer tracking_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::TrackingLinks::TagAddResponse

        def remove: (
          Integer tracking_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::TrackingLinks::TagRemoveResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
