module Onlyfans
  module Models
    module Banking
      type detail_retrieve_legal_form_details_response =
        {
          _meta: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta,
          data: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data
        }

      class DetailRetrieveLegalFormDetailsResponse < Onlyfans::Internal::Type::BaseModel
        attr_reader _meta: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta?

        def _meta=: (
          Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta
        ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta

        attr_reader data: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data?

        def data=: (
          Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data
        ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data

        def initialize: (
          ?_meta: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta,
          ?data: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta,
          data: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data
        }

        type meta =
          {
            _cache: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache,
            _credits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits
          }

        class Meta < Onlyfans::Internal::Type::BaseModel
          attr_reader _cache: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache?

          def _cache=: (
            Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache
          ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache

          attr_reader _credits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits?

          def _credits=: (
            Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits
          ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits
          ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache,
            ?_credits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits,
            ?_rate_limits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Cache,
            _credits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfans::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfans::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfans::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            date_of_birth: String,
            document_type: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType,
            is_allowed_dl: bool,
            private_website: String,
            real_address: String,
            real_business_name: String,
            real_city: String,
            real_first_name: String,
            real_instagram: String,
            real_last_name: String,
            real_postal: String,
            real_state: String,
            real_twitter: String
          }

        class Data < Onlyfans::Internal::Type::BaseModel
          attr_reader date_of_birth: String?

          def date_of_birth=: (String) -> String

          attr_reader document_type: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType?

          def document_type=: (
            Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType
          ) -> Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType

          attr_reader is_allowed_dl: bool?

          def is_allowed_dl=: (bool) -> bool

          attr_reader private_website: String?

          def private_website=: (String) -> String

          attr_reader real_address: String?

          def real_address=: (String) -> String

          attr_reader real_business_name: String?

          def real_business_name=: (String) -> String

          attr_reader real_city: String?

          def real_city=: (String) -> String

          attr_reader real_first_name: String?

          def real_first_name=: (String) -> String

          attr_reader real_instagram: String?

          def real_instagram=: (String) -> String

          attr_reader real_last_name: String?

          def real_last_name=: (String) -> String

          attr_reader real_postal: String?

          def real_postal=: (String) -> String

          attr_reader real_state: String?

          def real_state=: (String) -> String

          attr_reader real_twitter: String?

          def real_twitter=: (String) -> String

          def initialize: (
            ?date_of_birth: String,
            ?document_type: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType,
            ?is_allowed_dl: bool,
            ?private_website: String,
            ?real_address: String,
            ?real_business_name: String,
            ?real_city: String,
            ?real_first_name: String,
            ?real_instagram: String,
            ?real_last_name: String,
            ?real_postal: String,
            ?real_state: String,
            ?real_twitter: String
          ) -> void

          def to_hash: -> {
            date_of_birth: String,
            document_type: Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType,
            is_allowed_dl: bool,
            private_website: String,
            real_address: String,
            real_business_name: String,
            real_city: String,
            real_first_name: String,
            real_instagram: String,
            real_last_name: String,
            real_postal: String,
            real_state: String,
            real_twitter: String
          }

          type document_type =
            {
              values: ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]
            }

          class DocumentType < Onlyfans::Internal::Type::BaseModel
            attr_reader values: ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]?

            def values=: (
              ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]
            ) -> ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]

            def initialize: (
              ?values: ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]
            ) -> void

            def to_hash: -> {
              values: ::Array[Onlyfans::Models::Banking::DetailRetrieveLegalFormDetailsResponse::Data::DocumentType::Value]
            }

            type value = { code: String, name: String }

            class Value < Onlyfans::Internal::Type::BaseModel
              attr_reader code: String?

              def code=: (String) -> String

              attr_reader name: String?

              def name=: (String) -> String

              def initialize: (?code: String, ?name: String) -> void

              def to_hash: -> { code: String, name: String }
            end
          end
        end
      end
    end
  end
end
