module Onlyfans
  module Resources
    class Statistics
      class Statements
        def get_earnings: (
          String account,
          start_date: String,
          ?end_date: String,
          ?type: Onlyfans::Models::Statistics::StatementGetEarningsParams::type_,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Statistics::StatementGetEarningsResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
