module Onlyfans
  module Resources
    class SavedForLater
      class Posts
        class Settings
          def retrieve: (
            String account,
            ?request_options: Onlyfans::request_opts
          ) -> Onlyfans::Models::SavedForLater::Posts::SettingRetrieveResponse

          def disable_automatic_posting: (
            String account,
            ?request_options: Onlyfans::request_opts
          ) -> Onlyfans::Models::SavedForLater::Posts::SettingDisableAutomaticPostingResponse

          def enable_or_update_automatic_posting: (
            String account,
            period: Onlyfans::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period,
            ?request_options: Onlyfans::request_opts
          ) -> Onlyfans::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingResponse

          def initialize: (client: Onlyfans::Client) -> void
        end
      end
    end
  end
end
