module Onlyfansapi
  module Models
    module Media
      module Vault
        module Lists
          type media_remove_params =
            { account: String, list_id: String, media_ids: ::Array[String] }
            & Onlyfansapi::Internal::Type::request_parameters

          class MediaRemoveParams < Onlyfansapi::Internal::Type::BaseModel
            extend Onlyfansapi::Internal::Type::RequestParameters::Converter
            include Onlyfansapi::Internal::Type::RequestParameters

            attr_accessor account: String

            attr_accessor list_id: String

            attr_accessor media_ids: ::Array[String]

            def initialize: (
              account: String,
              list_id: String,
              media_ids: ::Array[String],
              ?request_options: Onlyfansapi::request_opts
            ) -> void

            def to_hash: -> {
              account: String,
              list_id: String,
              media_ids: ::Array[String],
              request_options: Onlyfansapi::RequestOptions
            }
          end
        end
      end
    end
  end
end
