module Onlyfans
  module Resources
    class SharedTrackingLinks
      class Tags
        def list: (
          Integer shared_tracking_link_id,
          account: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::SharedTrackingLinks::TagListResponse

        def add: (
          Integer shared_tracking_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::SharedTrackingLinks::TagAddResponse

        def remove: (
          Integer shared_tracking_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::SharedTrackingLinks::TagRemoveResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
