module Onlyfansapi
  module Resources
    class Analytics
      class Financial
        class Transactions
          def get_by_type: (
            account_ids: ::Array[String],
            end_date: String,
            start_date: String,
            ?request_options: Onlyfansapi::request_opts
          ) -> Onlyfansapi::Models::Analytics::Financial::transaction_get_by_type_response

          def get_summary: (
            account_ids: ::Array[String],
            end_date: String,
            start_date: String,
            ?request_options: Onlyfansapi::request_opts
          ) -> Onlyfansapi::Models::Analytics::Financial::TransactionGetSummaryResponse

          def initialize: (client: Onlyfansapi::Client) -> void
        end
      end
    end
  end
end
