module Onlyfansapi
  module Models
    module Settings
      type social_media_button_reorder_params =
        { account: String, button_ids: ::Array[String] }
        & Onlyfansapi::Internal::Type::request_parameters

      class SocialMediaButtonReorderParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor button_ids: ::Array[String]

        def initialize: (
          account: String,
          button_ids: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          button_ids: ::Array[String],
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
