module Onlyfansapi
  module Models
    module Settings
      type welcome_message_update_response =
        {
          _meta: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta,
          data: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data
        }

      class WelcomeMessageUpdateResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _meta: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta?

        def _meta=: (
          Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta
        ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta

        attr_reader data: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data?

        def data=: (
          Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data
        ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data

        def initialize: (
          ?_meta: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta,
          ?data: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta,
          data: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data
        }

        type meta =
          {
            _cache: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits
          }

        class Meta < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _cache: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache?

          def _cache=: (
            Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache
          ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache

          attr_reader _credits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits?

          def _credits=: (
            Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits
          ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits
          ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache,
            ?_credits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits,
            ?_rate_limits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfansapi::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            id: String,
            created_at: String,
            display_text: String,
            giphy_id: String?,
            is_active: bool,
            is_couple_people_media: bool,
            is_markdown_disabled: bool,
            is_media_ready: bool,
            locked_text: bool,
            media: ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media],
            media_count: Integer,
            previews: ::Array[top],
            price: Integer,
            release_forms: ::Array[top],
            template: String,
            text: String
          }

        class Data < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader display_text: String?

          def display_text=: (String) -> String

          attr_accessor giphy_id: String?

          attr_reader is_active: bool?

          def is_active=: (bool) -> bool

          attr_reader is_couple_people_media: bool?

          def is_couple_people_media=: (bool) -> bool

          attr_reader is_markdown_disabled: bool?

          def is_markdown_disabled=: (bool) -> bool

          attr_reader is_media_ready: bool?

          def is_media_ready=: (bool) -> bool

          attr_reader locked_text: bool?

          def locked_text=: (bool) -> bool

          attr_reader media: ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media]?

          def media=: (
            ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media]
          ) -> ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media]

          attr_reader media_count: Integer?

          def media_count=: (Integer) -> Integer

          attr_reader previews: ::Array[top]?

          def previews=: (::Array[top]) -> ::Array[top]

          attr_reader price: Integer?

          def price=: (Integer) -> Integer

          attr_reader release_forms: ::Array[top]?

          def release_forms=: (::Array[top]) -> ::Array[top]

          attr_reader template: String?

          def template=: (String) -> String

          attr_reader text: String?

          def text=: (String) -> String

          def initialize: (
            ?id: String,
            ?created_at: String,
            ?display_text: String,
            ?giphy_id: String?,
            ?is_active: bool,
            ?is_couple_people_media: bool,
            ?is_markdown_disabled: bool,
            ?is_media_ready: bool,
            ?locked_text: bool,
            ?media: ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media],
            ?media_count: Integer,
            ?previews: ::Array[top],
            ?price: Integer,
            ?release_forms: ::Array[top],
            ?template: String,
            ?text: String
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: String,
            display_text: String,
            giphy_id: String?,
            is_active: bool,
            is_couple_people_media: bool,
            is_markdown_disabled: bool,
            is_media_ready: bool,
            locked_text: bool,
            media: ::Array[Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media],
            media_count: Integer,
            previews: ::Array[top],
            price: Integer,
            release_forms: ::Array[top],
            template: String,
            text: String
          }

          type media =
            {
              id: Integer,
              can_view: bool,
              converted_to_video: bool,
              created_at: String,
              duration: Integer,
              files: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files,
              has_custom_preview: bool,
              has_error: bool,
              is_ready: bool,
              release_forms: ::Array[top],
              type: String,
              video_sources: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources
            }

          class Media < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader can_view: bool?

            def can_view=: (bool) -> bool

            attr_reader converted_to_video: bool?

            def converted_to_video=: (bool) -> bool

            attr_reader created_at: String?

            def created_at=: (String) -> String

            attr_reader duration: Integer?

            def duration=: (Integer) -> Integer

            attr_reader files: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files?

            def files=: (
              Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files
            ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files

            attr_reader has_custom_preview: bool?

            def has_custom_preview=: (bool) -> bool

            attr_reader has_error: bool?

            def has_error=: (bool) -> bool

            attr_reader is_ready: bool?

            def is_ready=: (bool) -> bool

            attr_reader release_forms: ::Array[top]?

            def release_forms=: (::Array[top]) -> ::Array[top]

            attr_reader type: String?

            def type=: (String) -> String

            attr_reader video_sources: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources?

            def video_sources=: (
              Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources
            ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources

            def initialize: (
              ?id: Integer,
              ?can_view: bool,
              ?converted_to_video: bool,
              ?created_at: String,
              ?duration: Integer,
              ?files: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files,
              ?has_custom_preview: bool,
              ?has_error: bool,
              ?is_ready: bool,
              ?release_forms: ::Array[top],
              ?type: String,
              ?video_sources: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources
            ) -> void

            def to_hash: -> {
              id: Integer,
              can_view: bool,
              converted_to_video: bool,
              created_at: String,
              duration: Integer,
              files: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files,
              has_custom_preview: bool,
              has_error: bool,
              is_ready: bool,
              release_forms: ::Array[top],
              type: String,
              video_sources: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::VideoSources
            }

            type files =
              {
                full: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full,
                preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview,
                square_preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview,
                thumb: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb
              }

            class Files < Onlyfansapi::Internal::Type::BaseModel
              attr_reader full: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full?

              def full=: (
                Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full
              ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full

              attr_reader preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview?

              def preview=: (
                Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview
              ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview

              attr_reader square_preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview?

              def square_preview=: (
                Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview
              ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview

              attr_reader thumb: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb?

              def thumb=: (
                Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb
              ) -> Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb

              def initialize: (
                ?full: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full,
                ?preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview,
                ?square_preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview,
                ?thumb: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb
              ) -> void

              def to_hash: -> {
                full: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Full,
                preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Preview,
                square_preview: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::SquarePreview,
                thumb: Onlyfansapi::Models::Settings::WelcomeMessageUpdateResponse::Data::Media::Files::Thumb
              }

              type full =
                {
                  height: Integer,
                  size: Integer,
                  sources: ::Array[top],
                  url: String,
                  width: Integer
                }

              class Full < Onlyfansapi::Internal::Type::BaseModel
                attr_reader height: Integer?

                def height=: (Integer) -> Integer

                attr_reader size: Integer?

                def size=: (Integer) -> Integer

                attr_reader sources: ::Array[top]?

                def sources=: (::Array[top]) -> ::Array[top]

                attr_reader url: String?

                def url=: (String) -> String

                attr_reader width: Integer?

                def width=: (Integer) -> Integer

                def initialize: (
                  ?height: Integer,
                  ?size: Integer,
                  ?sources: ::Array[top],
                  ?url: String,
                  ?width: Integer
                ) -> void

                def to_hash: -> {
                  height: Integer,
                  size: Integer,
                  sources: ::Array[top],
                  url: String,
                  width: Integer
                }
              end

              type preview =
                { height: Integer, size: Integer, url: String, width: Integer }

              class Preview < Onlyfansapi::Internal::Type::BaseModel
                attr_reader height: Integer?

                def height=: (Integer) -> Integer

                attr_reader size: Integer?

                def size=: (Integer) -> Integer

                attr_reader url: String?

                def url=: (String) -> String

                attr_reader width: Integer?

                def width=: (Integer) -> Integer

                def initialize: (
                  ?height: Integer,
                  ?size: Integer,
                  ?url: String,
                  ?width: Integer
                ) -> void

                def to_hash: -> {
                  height: Integer,
                  size: Integer,
                  url: String,
                  width: Integer
                }
              end

              type square_preview =
                { height: Integer, size: Integer, url: String, width: Integer }

              class SquarePreview < Onlyfansapi::Internal::Type::BaseModel
                attr_reader height: Integer?

                def height=: (Integer) -> Integer

                attr_reader size: Integer?

                def size=: (Integer) -> Integer

                attr_reader url: String?

                def url=: (String) -> String

                attr_reader width: Integer?

                def width=: (Integer) -> Integer

                def initialize: (
                  ?height: Integer,
                  ?size: Integer,
                  ?url: String,
                  ?width: Integer
                ) -> void

                def to_hash: -> {
                  height: Integer,
                  size: Integer,
                  url: String,
                  width: Integer
                }
              end

              type thumb =
                { height: Integer, size: Integer, url: String, width: Integer }

              class Thumb < Onlyfansapi::Internal::Type::BaseModel
                attr_reader height: Integer?

                def height=: (Integer) -> Integer

                attr_reader size: Integer?

                def size=: (Integer) -> Integer

                attr_reader url: String?

                def url=: (String) -> String

                attr_reader width: Integer?

                def width=: (Integer) -> Integer

                def initialize: (
                  ?height: Integer,
                  ?size: Integer,
                  ?url: String,
                  ?width: Integer
                ) -> void

                def to_hash: -> {
                  height: Integer,
                  size: Integer,
                  url: String,
                  width: Integer
                }
              end
            end

            type video_sources =
              { :number_240 => String?, :number_720 => String? }

            class VideoSources < Onlyfansapi::Internal::Type::BaseModel
              attr_accessor number_240: String?

              attr_accessor number_720: String?

              def initialize: (
                ?number_240: String?,
                ?number_720: String?
              ) -> void

              def to_hash: -> { :number_240 => String?, :number_720 => String? }
            end
          end
        end
      end
    end
  end
end
