module Onlyfansapi
  module Models
    module Banking
      type detail_retrieve_dac7_form_details_params =
        { account: String } & Onlyfansapi::Internal::Type::request_parameters

      class DetailRetrieveDac7FormDetailsParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        def initialize: (
          account: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
