module Onlyfans
  module Resources
    class Chargebacks
      def list: (
        String account,
        ?end_date: String,
        ?limit: String?,
        ?offset: String?,
        ?start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::ChargebackListResponse

      def calculate_ratio: (
        String account,
        ?end_date: String,
        ?start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::ChargebackCalculateRatioResponse

      def list_statistics: (
        String account,
        ?end_date: String,
        ?start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::ChargebackListStatisticsResponse

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
