module Onlyfans
  module Resources
    class MassMessaging
      def retrieve: (
        String id,
        account: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingRetrieveResponse

      def update: (
        String id,
        account: String,
        text: String,
        ?giphy_id: String,
        ?locked_text: bool,
        ?media_files: ::Array[String],
        ?previews: ::Array[String],
        ?price: Integer,
        ?scheduled_date: String,
        ?user_ids: ::Array[String],
        ?user_lists: ::Array[String],
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingUpdateResponse

      def list: (
        String account,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingListResponse

      def delete: (
        String id,
        account: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingDeleteResponse

      def retrieve_overview: (
        String account,
        ?end_date: String,
        ?limit: Integer,
        ?query: String,
        ?start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingRetrieveOverviewResponse

      def send_: (
        String account,
        text: String,
        ?excluded_lists: ::Array[String],
        ?giphy_id: String,
        ?locked_text: bool,
        ?media_files: ::Array[top],
        ?previews: ::Array[top],
        ?price: Integer,
        ?rf_guest: String,
        ?rf_partner: String,
        ?rf_tag: String,
        ?save_for_later: bool,
        ?scheduled_date: String,
        ?user_ids: ::Array[String],
        ?user_lists: ::Array[String],
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::MassMessagingSendResponse

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
