module Onlyfans
  module Resources
    class SmartLinkPostbacks
      def create: (
        conversion_types: ::Array[String],
        smart_link_scope: Onlyfans::Models::SmartLinkPostbackCreateParams::smart_link_scope,
        url: String,
        ?smart_link_ids: ::Array[String],
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::SmartLinkPostbackCreateResponse

      def retrieve: (
        Integer postback_id,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::SmartLinkPostbackRetrieveResponse

      def update: (
        Integer postback_id,
        conversion_types: ::Array[String],
        smart_link_scope: Onlyfans::Models::SmartLinkPostbackUpdateParams::smart_link_scope,
        url: String,
        ?smart_link_ids: ::Array[String],
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::SmartLinkPostbackUpdateResponse

      def list: (
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::SmartLinkPostbackListResponse

      def delete: (
        Integer postback_id,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::smart_link_postback_delete_response?

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
