module Onlyfans
  module Resources
    class Statistics
      attr_reader statements: Onlyfans::Resources::Statistics::Statements

      attr_reader reach: Onlyfans::Resources::Statistics::Reach

      def calculate_total_transactions: (
        String account,
        ?end_date: String,
        ?start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StatisticCalculateTotalTransactionsResponse

      def get_overview: (
        String account,
        ?end_date: String,
        ?start_date: String,
        ?type: Onlyfans::Models::StatisticGetOverviewParams::type_?,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StatisticGetOverviewResponse

      def get_subscriber_metrics: (
        String account,
        end_date: String,
        start_date: String,
        ?detailed: bool?,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StatisticGetSubscriberMetricsResponse

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
