module Onlyfans
  module Resources
    class Stored
      def list_shared_tracking_links: (
        String account,
        ?filter: Onlyfans::StoredListSharedTrackingLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StoredListSharedTrackingLinksResponse

      def list_shared_trial_links: (
        String account,
        ?filter: Onlyfans::StoredListSharedTrialLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StoredListSharedTrialLinksResponse

      def list_tracking_links: (
        String account,
        ?filter: Onlyfans::StoredListTrackingLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StoredListTrackingLinksResponse

      def list_trial_links: (
        String account,
        ?filter: Onlyfans::StoredListTrialLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::StoredListTrialLinksResponse

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
