module Onlyfans
  module Resources
    class TrialLinks
      attr_reader tags: Onlyfans::Resources::TrialLinks::Tags

      def create: (
        String account,
        duration: Onlyfans::Models::TrialLinkCreateParams::duration,
        offer_expiration: Integer,
        offer_limit: Onlyfans::Models::TrialLinkCreateParams::offer_limit,
        ?name: String?,
        ?tags: ::Array[String],
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkCreateResponse

      def retrieve: (
        String trial_link_id,
        account: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkRetrieveResponse

      def list: (
        String account,
        ?end_date: String?,
        ?field: Onlyfans::Models::TrialLinkListParams::field,
        ?limit: Integer,
        ?offset: Integer,
        ?sort: Onlyfans::Models::TrialLinkListParams::sort,
        ?start_date: String?,
        ?synchronous: bool,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkListResponse

      def delete: (
        String trial_link_id,
        account: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkDeleteResponse

      def list_spenders: (
        String trial_link_id,
        account: String,
        ?limit: Integer,
        ?min_spend: Float,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkListSpendersResponse

      def list_subscribers: (
        String trial_link_id,
        account: String,
        limit: Integer,
        offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkListSubscribersResponse

      def retrieve_cohort_arps: (
        String trial_link_id,
        account: String,
        ?acquisition_end: String,
        ?acquisition_start: String,
        ?revenue_basis: Onlyfans::Models::TrialLinkRetrieveCohortArpsParams::revenue_basis,
        ?request_options: Onlyfans::request_opts
      ) -> nil

      def retrieve_stats: (
        String trial_link_id,
        account: String,
        ?date_end: String,
        ?date_start: String,
        ?request_options: Onlyfans::request_opts
      ) -> Onlyfans::Models::TrialLinkRetrieveStatsResponse

      def initialize: (client: Onlyfans::Client) -> void
    end
  end
end
