module Onlyfansapi
  module Models
    module Stories
      type highlight_update_response =
        {
          _meta: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta,
          data: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data
        }

      class HighlightUpdateResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _meta: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta?

        def _meta=: (
          Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta
        ) -> Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta

        attr_reader data: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data?

        def data=: (
          Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data
        ) -> Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data

        def initialize: (
          ?_meta: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta,
          ?data: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta,
          data: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Data
        }

        type meta =
          {
            _cache: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits
          }

        class Meta < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _cache: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache?

          def _cache=: (
            Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache
          ) -> Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache

          attr_reader _credits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits?

          def _credits=: (
            Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits
          ) -> Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits
          ) -> Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache,
            ?_credits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits,
            ?_rate_limits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Stories::HighlightUpdateResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfansapi::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfansapi::Internal::Type::BaseModel
            attr_accessor limit_day: String?

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader notice: String?

            def notice=: (String) -> String

            attr_accessor remaining_day: String?

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: String?,
              ?limit_minute: Integer,
              ?notice: String,
              ?remaining_day: String?,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            id: Integer,
            cover: String,
            cover_story_id: Integer,
            created_at: String,
            stories_count: Integer,
            title: String,
            user_id: Integer
          }

        class Data < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader cover: String?

          def cover=: (String) -> String

          attr_reader cover_story_id: Integer?

          def cover_story_id=: (Integer) -> Integer

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader stories_count: Integer?

          def stories_count=: (Integer) -> Integer

          attr_reader title: String?

          def title=: (String) -> String

          attr_reader user_id: Integer?

          def user_id=: (Integer) -> Integer

          def initialize: (
            ?id: Integer,
            ?cover: String,
            ?cover_story_id: Integer,
            ?created_at: String,
            ?stories_count: Integer,
            ?title: String,
            ?user_id: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            cover: String,
            cover_story_id: Integer,
            created_at: String,
            stories_count: Integer,
            title: String,
            user_id: Integer
          }
        end
      end
    end
  end
end
