module Onlyfansapi
  module Models
    module Stories
      type highlight_remove_story_params =
        { account: String, highlight_id: Integer, story_id: String }
        & Onlyfansapi::Internal::Type::request_parameters

      class HighlightRemoveStoryParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor highlight_id: Integer

        attr_accessor story_id: String

        def initialize: (
          account: String,
          highlight_id: Integer,
          story_id: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          highlight_id: Integer,
          story_id: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
