module Onlyfansapi
  module Resources
    class Chats
      class MarkAllAsRead
        def all: (
          String account,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Chats::MarkAllAsReadAllResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
