module Onlyfansapi
  module Resources
    class Chats
      class Messages
        def list: (
          String chat_id,
          account: String,
          ?filter: Onlyfansapi::Models::Chats::MessageListParams::filter,
          ?first_id: String?,
          ?last_id: String?,
          ?limit: String,
          ?order: String,
          ?skip_users: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Chats::MessageListResponse

        def delete: (
          String message_id,
          account: String,
          chat_id: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Chats::MessageDeleteResponse

        def send_: (
          String chat_id,
          account: String,
          ?giphy_id: String,
          ?locked_text: bool,
          ?media_files: ::Array[top],
          ?previews: ::Array[top],
          ?price: Integer,
          ?reply_to_message_id: Integer,
          ?rf_guest: String,
          ?rf_partner: String,
          ?rf_tag: String,
          ?text: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Chats::MessageSendResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
