module Onlyfansapi
  module Models
    module Chats
      type message_retrieve_params =
        { account: String, chat_id: String, message_id: String }
        & Onlyfansapi::Internal::Type::request_parameters

      class MessageRetrieveParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor chat_id: String

        attr_accessor message_id: String

        def initialize: (
          account: String,
          chat_id: String,
          message_id: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          chat_id: String,
          message_id: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
