module Onlyfansapi
  module Models
    module Posts
      type comment_create_params =
        {
          account: String,
          post_id: String,
          text: String,
          answer_to: Integer,
          giphy_id: String
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class CommentCreateParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor post_id: String

        attr_accessor text: String

        attr_reader answer_to: Integer?

        def answer_to=: (Integer) -> Integer

        attr_reader giphy_id: String?

        def giphy_id=: (String) -> String

        def initialize: (
          account: String,
          post_id: String,
          text: String,
          ?answer_to: Integer,
          ?giphy_id: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          post_id: String,
          text: String,
          answer_to: Integer,
          giphy_id: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
