module Onlyfansapi
  module Models
    module Posts
      type comment_list_params =
        {
          account: String,
          post_id: String,
          limit: Integer,
          offset: Integer,
          sort: Onlyfansapi::Models::Posts::CommentListParams::sort
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class CommentListParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor post_id: String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        attr_reader sort: Onlyfansapi::Models::Posts::CommentListParams::sort?

        def sort=: (
          Onlyfansapi::Models::Posts::CommentListParams::sort
        ) -> Onlyfansapi::Models::Posts::CommentListParams::sort

        def initialize: (
          account: String,
          post_id: String,
          ?limit: Integer,
          ?offset: Integer,
          ?sort: Onlyfansapi::Models::Posts::CommentListParams::sort,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          post_id: String,
          limit: Integer,
          offset: Integer,
          sort: Onlyfansapi::Models::Posts::CommentListParams::sort,
          request_options: Onlyfansapi::RequestOptions
        }

        type sort = :desc | :asc

        module Sort
          extend Onlyfansapi::Internal::Type::Enum

          DESC: :desc
          ASC: :asc

          def self?.values: -> ::Array[Onlyfansapi::Models::Posts::CommentListParams::sort]
        end
      end
    end
  end
end
