module Onlyfans
  module Models
    module Posts
      type comment_list_response =
        {
          _meta: Onlyfans::Models::Posts::CommentListResponse::Meta,
          data: Onlyfans::Models::Posts::CommentListResponse::Data
        }

      class CommentListResponse < Onlyfans::Internal::Type::BaseModel
        attr_reader _meta: Onlyfans::Models::Posts::CommentListResponse::Meta?

        def _meta=: (
          Onlyfans::Models::Posts::CommentListResponse::Meta
        ) -> Onlyfans::Models::Posts::CommentListResponse::Meta

        attr_reader data: Onlyfans::Models::Posts::CommentListResponse::Data?

        def data=: (
          Onlyfans::Models::Posts::CommentListResponse::Data
        ) -> Onlyfans::Models::Posts::CommentListResponse::Data

        def initialize: (
          ?_meta: Onlyfans::Models::Posts::CommentListResponse::Meta,
          ?data: Onlyfans::Models::Posts::CommentListResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfans::Models::Posts::CommentListResponse::Meta,
          data: Onlyfans::Models::Posts::CommentListResponse::Data
        }

        type meta =
          {
            _cache: Onlyfans::Models::Posts::CommentListResponse::Meta::Cache,
            _credits: Onlyfans::Models::Posts::CommentListResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits
          }

        class Meta < Onlyfans::Internal::Type::BaseModel
          attr_reader _cache: Onlyfans::Models::Posts::CommentListResponse::Meta::Cache?

          def _cache=: (
            Onlyfans::Models::Posts::CommentListResponse::Meta::Cache
          ) -> Onlyfans::Models::Posts::CommentListResponse::Meta::Cache

          attr_reader _credits: Onlyfans::Models::Posts::CommentListResponse::Meta::Credits?

          def _credits=: (
            Onlyfans::Models::Posts::CommentListResponse::Meta::Credits
          ) -> Onlyfans::Models::Posts::CommentListResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits
          ) -> Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfans::Models::Posts::CommentListResponse::Meta::Cache,
            ?_credits: Onlyfans::Models::Posts::CommentListResponse::Meta::Credits,
            ?_rate_limits: Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfans::Models::Posts::CommentListResponse::Meta::Cache,
            _credits: Onlyfans::Models::Posts::CommentListResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Posts::CommentListResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfans::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfans::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfans::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            has_more: bool,
            list: ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List],
            next_offset: Integer
          }

        class Data < Onlyfans::Internal::Type::BaseModel
          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          attr_reader list: ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List]?

          def list=: (
            ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List]
          ) -> ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List]

          attr_reader next_offset: Integer?

          def next_offset=: (Integer) -> Integer

          def initialize: (
            ?has_more: bool,
            ?list: ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List],
            ?next_offset: Integer
          ) -> void

          def to_hash: -> {
            has_more: bool,
            list: ::Array[Onlyfans::Models::Posts::CommentListResponse::Data::List],
            next_offset: Integer
          }

          type list =
            {
              id: Integer,
              author: Onlyfans::Models::Posts::CommentListResponse::Data::List::Author,
              can_like: bool,
              changed_at: String,
              giphy_id: String?,
              is_liked: bool,
              is_liked_by_author: bool,
              is_pinned: bool,
              likes_count: Integer,
              posted_at: String,
              text: String
            }

          class List < Onlyfans::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader author: Onlyfans::Models::Posts::CommentListResponse::Data::List::Author?

            def author=: (
              Onlyfans::Models::Posts::CommentListResponse::Data::List::Author
            ) -> Onlyfans::Models::Posts::CommentListResponse::Data::List::Author

            attr_reader can_like: bool?

            def can_like=: (bool) -> bool

            attr_reader changed_at: String?

            def changed_at=: (String) -> String

            attr_accessor giphy_id: String?

            attr_reader is_liked: bool?

            def is_liked=: (bool) -> bool

            attr_reader is_liked_by_author: bool?

            def is_liked_by_author=: (bool) -> bool

            attr_reader is_pinned: bool?

            def is_pinned=: (bool) -> bool

            attr_reader likes_count: Integer?

            def likes_count=: (Integer) -> Integer

            attr_reader posted_at: String?

            def posted_at=: (String) -> String

            attr_reader text: String?

            def text=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?author: Onlyfans::Models::Posts::CommentListResponse::Data::List::Author,
              ?can_like: bool,
              ?changed_at: String,
              ?giphy_id: String?,
              ?is_liked: bool,
              ?is_liked_by_author: bool,
              ?is_pinned: bool,
              ?likes_count: Integer,
              ?posted_at: String,
              ?text: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              author: Onlyfans::Models::Posts::CommentListResponse::Data::List::Author,
              can_like: bool,
              changed_at: String,
              giphy_id: String?,
              is_liked: bool,
              is_liked_by_author: bool,
              is_pinned: bool,
              likes_count: Integer,
              posted_at: String,
              text: String
            }

            type author = { id: Integer, _view: String }

            class Author < Onlyfans::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader _view: String?

              def _view=: (String) -> String

              def initialize: (?id: Integer, ?_view: String) -> void

              def to_hash: -> { id: Integer, _view: String }
            end
          end
        end
      end
    end
  end
end
