module Onlyfans
  module Models
    module Posts
      type comment_unpin_params =
        { account: String, post_id: Integer, comment_id: Integer }
        & Onlyfans::Internal::Type::request_parameters

      class CommentUnpinParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor post_id: Integer

        attr_accessor comment_id: Integer

        def initialize: (
          account: String,
          post_id: Integer,
          comment_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          post_id: Integer,
          comment_id: Integer,
          request_options: Onlyfans::RequestOptions
        }
      end
    end
  end
end
