module Onlyfans
  module Models
    module Posts
      type label_create_response =
        {
          _meta: Onlyfans::Models::Posts::LabelCreateResponse::Meta,
          data: Onlyfans::Models::Posts::LabelCreateResponse::Data
        }

      class LabelCreateResponse < Onlyfans::Internal::Type::BaseModel
        attr_reader _meta: Onlyfans::Models::Posts::LabelCreateResponse::Meta?

        def _meta=: (
          Onlyfans::Models::Posts::LabelCreateResponse::Meta
        ) -> Onlyfans::Models::Posts::LabelCreateResponse::Meta

        attr_reader data: Onlyfans::Models::Posts::LabelCreateResponse::Data?

        def data=: (
          Onlyfans::Models::Posts::LabelCreateResponse::Data
        ) -> Onlyfans::Models::Posts::LabelCreateResponse::Data

        def initialize: (
          ?_meta: Onlyfans::Models::Posts::LabelCreateResponse::Meta,
          ?data: Onlyfans::Models::Posts::LabelCreateResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfans::Models::Posts::LabelCreateResponse::Meta,
          data: Onlyfans::Models::Posts::LabelCreateResponse::Data
        }

        type meta =
          {
            _cache: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache,
            _credits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits
          }

        class Meta < Onlyfans::Internal::Type::BaseModel
          attr_reader _cache: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache?

          def _cache=: (
            Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache
          ) -> Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache

          attr_reader _credits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits?

          def _credits=: (
            Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits
          ) -> Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits
          ) -> Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache,
            ?_credits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits,
            ?_rate_limits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Cache,
            _credits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Posts::LabelCreateResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfans::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfans::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfans::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            id: Integer,
            is_clear_in_progress: bool,
            name: String,
            posts: ::Array[top],
            posts_count: Integer,
            type: String
          }

        class Data < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader is_clear_in_progress: bool?

          def is_clear_in_progress=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader posts: ::Array[top]?

          def posts=: (::Array[top]) -> ::Array[top]

          attr_reader posts_count: Integer?

          def posts_count=: (Integer) -> Integer

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?is_clear_in_progress: bool,
            ?name: String,
            ?posts: ::Array[top],
            ?posts_count: Integer,
            ?type: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            is_clear_in_progress: bool,
            name: String,
            posts: ::Array[top],
            posts_count: Integer,
            type: String
          }
        end
      end
    end
  end
end
