module Onlyfansapi
  module Resources
    class Media
      class Vault
        class Lists
          class Media
            def add: (
              String list_id,
              account: String,
              media_ids: ::Array[String],
              ?request_options: Onlyfansapi::request_opts
            ) -> Onlyfansapi::Models::Media::Vault::Lists::MediaAddResponse

            def remove: (
              String list_id,
              account: String,
              media_ids: ::Array[String],
              ?request_options: Onlyfansapi::request_opts
            ) -> Onlyfansapi::Models::Media::Vault::Lists::MediaRemoveResponse

            def initialize: (client: Onlyfansapi::Client) -> void
          end
        end
      end
    end
  end
end
