module Onlyfans
  module Models
    module Analytics
      module Financial
        type profitability_get_profitability_params =
          { account_ids: ::Array[String], month: Integer, year: Integer }
          & Onlyfans::Internal::Type::request_parameters

        class ProfitabilityGetProfitabilityParams < Onlyfans::Internal::Type::BaseModel
          extend Onlyfans::Internal::Type::RequestParameters::Converter
          include Onlyfans::Internal::Type::RequestParameters

          attr_accessor account_ids: ::Array[String]

          attr_accessor month: Integer

          attr_accessor year: Integer

          def initialize: (
            account_ids: ::Array[String],
            month: Integer,
            year: Integer,
            ?request_options: Onlyfans::request_opts
          ) -> void

          def to_hash: -> {
            account_ids: ::Array[String],
            month: Integer,
            year: Integer,
            request_options: Onlyfans::RequestOptions
          }
        end
      end
    end
  end
end
