module Onlyfansapi
  module Models
    module Analytics
      module Financial
        type transaction_get_by_type_params =
          { account_ids: ::Array[String], end_date: String, start_date: String }
          & Onlyfansapi::Internal::Type::request_parameters

        class TransactionGetByTypeParams < Onlyfansapi::Internal::Type::BaseModel
          extend Onlyfansapi::Internal::Type::RequestParameters::Converter
          include Onlyfansapi::Internal::Type::RequestParameters

          attr_accessor account_ids: ::Array[String]

          attr_accessor end_date: String

          attr_accessor start_date: String

          def initialize: (
            account_ids: ::Array[String],
            end_date: String,
            start_date: String,
            ?request_options: Onlyfansapi::request_opts
          ) -> void

          def to_hash: -> {
            account_ids: ::Array[String],
            end_date: String,
            start_date: String,
            request_options: Onlyfansapi::RequestOptions
          }
        end
      end
    end
  end
end
