module Onlyfansapi
  module Models
    module Analytics
      module Financial
        type transaction_get_by_type_response_item =
          { count: Integer, total: Float, type: String }

        class TransactionGetByTypeResponseItem < Onlyfansapi::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader total: Float?

          def total=: (Float) -> Float

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?count: Integer,
            ?total: Float,
            ?type: String
          ) -> void

          def to_hash: -> { count: Integer, total: Float, type: String }
        end

        type transaction_get_by_type_response =
          ::Array[Onlyfansapi::Models::Analytics::Financial::TransactionGetByTypeResponseItem]

        TransactionGetByTypeResponse: Onlyfansapi::Internal::Type::Converter
      end
    end
  end
end
