module Onlyfansapi
  module Models
    module Fans
      type note_get_notes_response =
        {
          _meta: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta,
          data: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data
        }

      class NoteGetNotesResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _meta: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta?

        def _meta=: (
          Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta
        ) -> Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta

        attr_reader data: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data?

        def data=: (
          Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data
        ) -> Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data

        def initialize: (
          ?_meta: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta,
          ?data: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta,
          data: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Data
        }

        type meta =
          {
            _cache: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits
          }

        class Meta < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _cache: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache?

          def _cache=: (
            Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache
          ) -> Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache

          attr_reader _credits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits?

          def _credits=: (
            Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits
          ) -> Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits
          ) -> Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache,
            ?_credits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits,
            ?_rate_limits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Fans::NoteGetNotesResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfansapi::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data = { notes: String }

        class Data < Onlyfansapi::Internal::Type::BaseModel
          attr_reader notes: String?

          def notes=: (String) -> String

          def initialize: (?notes: String) -> void

          def to_hash: -> { notes: String }
        end
      end
    end
  end
end
