module Onlyfansapi
  module Models
    module Media
      type upload_get_status_params =
        { account: String, upload: String }
        & Onlyfansapi::Internal::Type::request_parameters

      class UploadGetStatusParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor upload: String

        def initialize: (
          account: String,
          upload: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          upload: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
