module Onlyfansapi
  module Models
    module Media
      type vault_list_response =
        {
          _meta: Onlyfansapi::Models::Media::VaultListResponse::Meta,
          data: Onlyfansapi::Models::Media::VaultListResponse::Data
        }

      class VaultListResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _meta: Onlyfansapi::Models::Media::VaultListResponse::Meta?

        def _meta=: (
          Onlyfansapi::Models::Media::VaultListResponse::Meta
        ) -> Onlyfansapi::Models::Media::VaultListResponse::Meta

        attr_reader data: Onlyfansapi::Models::Media::VaultListResponse::Data?

        def data=: (
          Onlyfansapi::Models::Media::VaultListResponse::Data
        ) -> Onlyfansapi::Models::Media::VaultListResponse::Data

        def initialize: (
          ?_meta: Onlyfansapi::Models::Media::VaultListResponse::Meta,
          ?data: Onlyfansapi::Models::Media::VaultListResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfansapi::Models::Media::VaultListResponse::Meta,
          data: Onlyfansapi::Models::Media::VaultListResponse::Data
        }

        type meta =
          {
            _cache: Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits
          }

        class Meta < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _cache: Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache?

          def _cache=: (
            Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache
          ) -> Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache

          attr_reader _credits: Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits?

          def _credits=: (
            Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits
          ) -> Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits
          ) -> Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache,
            ?_credits: Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits,
            ?_rate_limits: Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfansapi::Models::Media::VaultListResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::Media::VaultListResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::Media::VaultListResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfansapi::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader limit_day: Integer?

            def limit_day=: (Integer) -> Integer

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader remaining_day: Integer?

            def remaining_day=: (Integer) -> Integer

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: Integer,
              ?limit_minute: Integer,
              ?remaining_day: Integer,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: Integer,
              limit_minute: Integer,
              remaining_day: Integer,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            has_more: bool,
            list: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]
          }

        class Data < Onlyfansapi::Internal::Type::BaseModel
          attr_reader has_more: bool?

          def has_more=: (bool) -> bool

          attr_reader list: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]?

          def list=: (
            ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]
          ) -> ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]

          def initialize: (
            ?has_more: bool,
            ?list: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]
          ) -> void

          def to_hash: -> {
            has_more: bool,
            list: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List]
          }

          type list =
            {
              id: Integer,
              can_view: bool,
              converted_to_video: bool,
              counters: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters,
              created_at: String,
              duration: Integer,
              files: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files,
              has_custom_preview: bool,
              has_error: bool,
              has_posts: bool,
              is_ready: bool,
              list_states: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState],
              release_forms: ::Array[top],
              type: String,
              video_sources: Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources
            }

          class List < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader can_view: bool?

            def can_view=: (bool) -> bool

            attr_reader converted_to_video: bool?

            def converted_to_video=: (bool) -> bool

            attr_reader counters: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters?

            def counters=: (
              Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters
            ) -> Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters

            attr_reader created_at: String?

            def created_at=: (String) -> String

            attr_reader duration: Integer?

            def duration=: (Integer) -> Integer

            attr_reader files: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files?

            def files=: (
              Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files
            ) -> Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files

            attr_reader has_custom_preview: bool?

            def has_custom_preview=: (bool) -> bool

            attr_reader has_error: bool?

            def has_error=: (bool) -> bool

            attr_reader has_posts: bool?

            def has_posts=: (bool) -> bool

            attr_reader is_ready: bool?

            def is_ready=: (bool) -> bool

            attr_reader list_states: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState]?

            def list_states=: (
              ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState]
            ) -> ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState]

            attr_reader release_forms: ::Array[top]?

            def release_forms=: (::Array[top]) -> ::Array[top]

            attr_reader type: String?

            def type=: (String) -> String

            attr_reader video_sources: Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources?

            def video_sources=: (
              Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources
            ) -> Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources

            def initialize: (
              ?id: Integer,
              ?can_view: bool,
              ?converted_to_video: bool,
              ?counters: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters,
              ?created_at: String,
              ?duration: Integer,
              ?files: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files,
              ?has_custom_preview: bool,
              ?has_error: bool,
              ?has_posts: bool,
              ?is_ready: bool,
              ?list_states: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState],
              ?release_forms: ::Array[top],
              ?type: String,
              ?video_sources: Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources
            ) -> void

            def to_hash: -> {
              id: Integer,
              can_view: bool,
              converted_to_video: bool,
              counters: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Counters,
              created_at: String,
              duration: Integer,
              files: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files,
              has_custom_preview: bool,
              has_error: bool,
              has_posts: bool,
              is_ready: bool,
              list_states: ::Array[Onlyfansapi::Models::Media::VaultListResponse::Data::List::ListState],
              release_forms: ::Array[top],
              type: String,
              video_sources: Onlyfansapi::Models::Media::VaultListResponse::Data::List::VideoSources
            }

            type counters = { likes_count: Integer, tips_summ: Integer }

            class Counters < Onlyfansapi::Internal::Type::BaseModel
              attr_reader likes_count: Integer?

              def likes_count=: (Integer) -> Integer

              attr_reader tips_summ: Integer?

              def tips_summ=: (Integer) -> Integer

              def initialize: (
                ?likes_count: Integer,
                ?tips_summ: Integer
              ) -> void

              def to_hash: -> { likes_count: Integer, tips_summ: Integer }
            end

            type files =
              {
                full: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full,
                preview: String?,
                square_preview: String?,
                thumb: String?
              }

            class Files < Onlyfansapi::Internal::Type::BaseModel
              attr_reader full: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full?

              def full=: (
                Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full
              ) -> Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full

              attr_accessor preview: String?

              attr_accessor square_preview: String?

              attr_accessor thumb: String?

              def initialize: (
                ?full: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full,
                ?preview: String?,
                ?square_preview: String?,
                ?thumb: String?
              ) -> void

              def to_hash: -> {
                full: Onlyfansapi::Models::Media::VaultListResponse::Data::List::Files::Full,
                preview: String?,
                square_preview: String?,
                thumb: String?
              }

              type full =
                {
                  height: Integer,
                  size: Integer,
                  sources: ::Array[top],
                  url: String,
                  width: Integer
                }

              class Full < Onlyfansapi::Internal::Type::BaseModel
                attr_reader height: Integer?

                def height=: (Integer) -> Integer

                attr_reader size: Integer?

                def size=: (Integer) -> Integer

                attr_reader sources: ::Array[top]?

                def sources=: (::Array[top]) -> ::Array[top]

                attr_reader url: String?

                def url=: (String) -> String

                attr_reader width: Integer?

                def width=: (Integer) -> Integer

                def initialize: (
                  ?height: Integer,
                  ?size: Integer,
                  ?sources: ::Array[top],
                  ?url: String,
                  ?width: Integer
                ) -> void

                def to_hash: -> {
                  height: Integer,
                  size: Integer,
                  sources: ::Array[top],
                  url: String,
                  width: Integer
                }
              end
            end

            type list_state =
              {
                id: Integer,
                can_add_media: bool,
                has_media: bool,
                name: String,
                type: String
              }

            class ListState < Onlyfansapi::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader can_add_media: bool?

              def can_add_media=: (bool) -> bool

              attr_reader has_media: bool?

              def has_media=: (bool) -> bool

              attr_reader name: String?

              def name=: (String) -> String

              attr_reader type: String?

              def type=: (String) -> String

              def initialize: (
                ?id: Integer,
                ?can_add_media: bool,
                ?has_media: bool,
                ?name: String,
                ?type: String
              ) -> void

              def to_hash: -> {
                id: Integer,
                can_add_media: bool,
                has_media: bool,
                name: String,
                type: String
              }
            end

            type video_sources =
              { :number_240 => String?, :number_720 => String? }

            class VideoSources < Onlyfansapi::Internal::Type::BaseModel
              attr_accessor number_240: String?

              attr_accessor number_720: String?

              def initialize: (
                ?number_240: String?,
                ?number_720: String?
              ) -> void

              def to_hash: -> { :number_240 => String?, :number_720 => String? }
            end
          end
        end
      end
    end
  end
end
