module Onlyfansapi
  module Models
    module Media
      type vault_list_params =
        {
          account: String,
          field: Onlyfansapi::Models::Media::VaultListParams::field,
          limit: Integer,
          list: Integer,
          offset: Integer,
          query: String?,
          sort: Onlyfansapi::Models::Media::VaultListParams::sort,
          type: Onlyfansapi::Models::Media::VaultListParams::type_
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class VaultListParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_reader field: Onlyfansapi::Models::Media::VaultListParams::field?

        def field=: (
          Onlyfansapi::Models::Media::VaultListParams::field
        ) -> Onlyfansapi::Models::Media::VaultListParams::field

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader list: Integer?

        def list=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        attr_accessor query: String?

        attr_reader sort: Onlyfansapi::Models::Media::VaultListParams::sort?

        def sort=: (
          Onlyfansapi::Models::Media::VaultListParams::sort
        ) -> Onlyfansapi::Models::Media::VaultListParams::sort

        attr_reader type: Onlyfansapi::Models::Media::VaultListParams::type_?

        def type=: (
          Onlyfansapi::Models::Media::VaultListParams::type_
        ) -> Onlyfansapi::Models::Media::VaultListParams::type_

        def initialize: (
          account: String,
          ?field: Onlyfansapi::Models::Media::VaultListParams::field,
          ?limit: Integer,
          ?list: Integer,
          ?offset: Integer,
          ?query: String?,
          ?sort: Onlyfansapi::Models::Media::VaultListParams::sort,
          ?type: Onlyfansapi::Models::Media::VaultListParams::type_,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          field: Onlyfansapi::Models::Media::VaultListParams::field,
          limit: Integer,
          list: Integer,
          offset: Integer,
          query: String?,
          sort: Onlyfansapi::Models::Media::VaultListParams::sort,
          type: Onlyfansapi::Models::Media::VaultListParams::type_,
          request_options: Onlyfansapi::RequestOptions
        }

        type field = :recent | :"most-liked" | :"highest-tips"

        module Field
          extend Onlyfansapi::Internal::Type::Enum

          RECENT: :recent
          MOST_LIKED: :"most-liked"
          HIGHEST_TIPS: :"highest-tips"

          def self?.values: -> ::Array[Onlyfansapi::Models::Media::VaultListParams::field]
        end

        type sort = :desc | :asc

        module Sort
          extend Onlyfansapi::Internal::Type::Enum

          DESC: :desc
          ASC: :asc

          def self?.values: -> ::Array[Onlyfansapi::Models::Media::VaultListParams::sort]
        end

        type type_ = :photo | :gif | :video | :audio

        module Type
          extend Onlyfansapi::Internal::Type::Enum

          PHOTO: :photo
          GIF: :gif
          VIDEO: :video
          AUDIO: :audio

          def self?.values: -> ::Array[Onlyfansapi::Models::Media::VaultListParams::type_]
        end
      end
    end
  end
end
