module Onlyfansapi
  module Models
    module Media
      type vault_retrieve_params =
        { account: String, media_id: Integer }
        & Onlyfansapi::Internal::Type::request_parameters

      class VaultRetrieveParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor media_id: Integer

        def initialize: (
          account: String,
          media_id: Integer,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          media_id: Integer,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
