module Onlyfansapi
  module Resources
    class Analytics
      class Financial
        attr_reader transactions: Onlyfansapi::Resources::Analytics::Financial::Transactions

        attr_reader profitability: Onlyfansapi::Resources::Analytics::Financial::Profitability

        def get_forecast: (
          account_ids: ::Array[String],
          forecast_days: Integer,
          historical_days: Integer,
          metric: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric,
          model: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Analytics::FinancialGetForecastResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
