module Onlyfansapi
  module Resources
    class Analytics
      class Summary
        def get_earnings_overview: (
          account_ids: ::Array[String],
          end_date: String,
          start_date: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Analytics::SummaryGetEarningsOverviewResponse

        def get_historical_performance: (
          ?time_range: Onlyfansapi::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Analytics::summary_get_historical_performance_response

        def get_period_comparison: (
          account_ids: ::Array[String],
          period_a: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodA,
          period_b: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodB,
          ?granularity: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity,
          ?stat_type: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
