module Onlyfansapi
  module Models
    module Media
      module Vault
        type list_delete_params =
          { account: String, list_id: String }
          & Onlyfansapi::Internal::Type::request_parameters

        class ListDeleteParams < Onlyfansapi::Internal::Type::BaseModel
          extend Onlyfansapi::Internal::Type::RequestParameters::Converter
          include Onlyfansapi::Internal::Type::RequestParameters

          attr_accessor account: String

          attr_accessor list_id: String

          def initialize: (
            account: String,
            list_id: String,
            ?request_options: Onlyfansapi::request_opts
          ) -> void

          def to_hash: -> {
            account: String,
            list_id: String,
            request_options: Onlyfansapi::RequestOptions
          }
        end
      end
    end
  end
end
