module Onlyfansapi
  module Models
    module Media
      module Vault
        type list_list_response =
          {
            _meta: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta,
            data: Onlyfansapi::Models::Media::Vault::ListListResponse::Data
          }

        class ListListResponse < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _meta: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta?

          def _meta=: (
            Onlyfansapi::Models::Media::Vault::ListListResponse::Meta
          ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Meta

          attr_reader data: Onlyfansapi::Models::Media::Vault::ListListResponse::Data?

          def data=: (
            Onlyfansapi::Models::Media::Vault::ListListResponse::Data
          ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Data

          def initialize: (
            ?_meta: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta,
            ?data: Onlyfansapi::Models::Media::Vault::ListListResponse::Data
          ) -> void

          def to_hash: -> {
            _meta: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta,
            data: Onlyfansapi::Models::Media::Vault::ListListResponse::Data
          }

          type meta =
            {
              _cache: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache,
              _credits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits,
              _rate_limits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits
            }

          class Meta < Onlyfansapi::Internal::Type::BaseModel
            attr_reader _cache: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache?

            def _cache=: (
              Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache
            ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache

            attr_reader _credits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits?

            def _credits=: (
              Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits
            ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits

            attr_reader _rate_limits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits?

            def _rate_limits=: (
              Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits
            ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits

            def initialize: (
              ?_cache: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache,
              ?_credits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits,
              ?_rate_limits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits
            ) -> void

            def to_hash: -> {
              _cache: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Cache,
              _credits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::Credits,
              _rate_limits: Onlyfansapi::Models::Media::Vault::ListListResponse::Meta::RateLimits
            }

            type cache = { is_cached: bool, note: String }

            class Cache < Onlyfansapi::Internal::Type::BaseModel
              attr_reader is_cached: bool?

              def is_cached=: (bool) -> bool

              attr_reader note: String?

              def note=: (String) -> String

              def initialize: (?is_cached: bool, ?note: String) -> void

              def to_hash: -> { is_cached: bool, note: String }
            end

            type credits = { balance: Integer, note: String, used: Integer }

            class Credits < Onlyfansapi::Internal::Type::BaseModel
              attr_reader balance: Integer?

              def balance=: (Integer) -> Integer

              attr_reader note: String?

              def note=: (String) -> String

              attr_reader used: Integer?

              def used=: (Integer) -> Integer

              def initialize: (
                ?balance: Integer,
                ?note: String,
                ?used: Integer
              ) -> void

              def to_hash: -> { balance: Integer, note: String, used: Integer }
            end

            type rate_limits =
              {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }

            class RateLimits < Onlyfansapi::Internal::Type::BaseModel
              attr_reader limit_day: Integer?

              def limit_day=: (Integer) -> Integer

              attr_reader limit_minute: Integer?

              def limit_minute=: (Integer) -> Integer

              attr_reader remaining_day: Integer?

              def remaining_day=: (Integer) -> Integer

              attr_reader remaining_minute: Integer?

              def remaining_minute=: (Integer) -> Integer

              def initialize: (
                ?limit_day: Integer,
                ?limit_minute: Integer,
                ?remaining_day: Integer,
                ?remaining_minute: Integer
              ) -> void

              def to_hash: -> {
                limit_day: Integer,
                limit_minute: Integer,
                remaining_day: Integer,
                remaining_minute: Integer
              }
            end
          end

          type data =
            {
              all: Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All,
              can_create_vault_lists: bool,
              has_more: bool,
              list: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List],
              order: String,
              sort: String
            }

          class Data < Onlyfansapi::Internal::Type::BaseModel
            attr_reader all: Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All?

            def all=: (
              Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All
            ) -> Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All

            attr_reader can_create_vault_lists: bool?

            def can_create_vault_lists=: (bool) -> bool

            attr_reader has_more: bool?

            def has_more=: (bool) -> bool

            attr_reader list: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List]?

            def list=: (
              ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List]
            ) -> ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List]

            attr_reader order: String?

            def order=: (String) -> String

            attr_reader sort: String?

            def sort=: (String) -> String

            def initialize: (
              ?all: Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All,
              ?can_create_vault_lists: bool,
              ?has_more: bool,
              ?list: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List],
              ?order: String,
              ?sort: String
            ) -> void

            def to_hash: -> {
              all: Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All,
              can_create_vault_lists: bool,
              has_more: bool,
              list: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::List],
              order: String,
              sort: String
            }

            type all =
              {
                audios_count: Integer,
                gifs_count: Integer,
                medias: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media],
                photos_count: Integer,
                videos_count: Integer
              }

            class All < Onlyfansapi::Internal::Type::BaseModel
              attr_reader audios_count: Integer?

              def audios_count=: (Integer) -> Integer

              attr_reader gifs_count: Integer?

              def gifs_count=: (Integer) -> Integer

              attr_reader medias: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media]?

              def medias=: (
                ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media]
              ) -> ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media]

              attr_reader photos_count: Integer?

              def photos_count=: (Integer) -> Integer

              attr_reader videos_count: Integer?

              def videos_count=: (Integer) -> Integer

              def initialize: (
                ?audios_count: Integer,
                ?gifs_count: Integer,
                ?medias: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media],
                ?photos_count: Integer,
                ?videos_count: Integer
              ) -> void

              def to_hash: -> {
                audios_count: Integer,
                gifs_count: Integer,
                medias: ::Array[Onlyfansapi::Models::Media::Vault::ListListResponse::Data::All::Media],
                photos_count: Integer,
                videos_count: Integer
              }

              type media = { type: String, url: String }

              class Media < Onlyfansapi::Internal::Type::BaseModel
                attr_reader type: String?

                def type=: (String) -> String

                attr_reader url: String?

                def url=: (String) -> String

                def initialize: (?type: String, ?url: String) -> void

                def to_hash: -> { type: String, url: String }
              end
            end

            type list =
              {
                id: Integer,
                audios_count: Integer,
                can_delete: bool,
                can_update: bool,
                gifs_count: Integer,
                has_media: bool,
                medias: ::Array[top],
                name: String,
                photos_count: Integer,
                type: String,
                videos_count: Integer
              }

            class List < Onlyfansapi::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader audios_count: Integer?

              def audios_count=: (Integer) -> Integer

              attr_reader can_delete: bool?

              def can_delete=: (bool) -> bool

              attr_reader can_update: bool?

              def can_update=: (bool) -> bool

              attr_reader gifs_count: Integer?

              def gifs_count=: (Integer) -> Integer

              attr_reader has_media: bool?

              def has_media=: (bool) -> bool

              attr_reader medias: ::Array[top]?

              def medias=: (::Array[top]) -> ::Array[top]

              attr_reader name: String?

              def name=: (String) -> String

              attr_reader photos_count: Integer?

              def photos_count=: (Integer) -> Integer

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader videos_count: Integer?

              def videos_count=: (Integer) -> Integer

              def initialize: (
                ?id: Integer,
                ?audios_count: Integer,
                ?can_delete: bool,
                ?can_update: bool,
                ?gifs_count: Integer,
                ?has_media: bool,
                ?medias: ::Array[top],
                ?name: String,
                ?photos_count: Integer,
                ?type: String,
                ?videos_count: Integer
              ) -> void

              def to_hash: -> {
                id: Integer,
                audios_count: Integer,
                can_delete: bool,
                can_update: bool,
                gifs_count: Integer,
                has_media: bool,
                medias: ::Array[top],
                name: String,
                photos_count: Integer,
                type: String,
                videos_count: Integer
              }
            end
          end
        end
      end
    end
  end
end
