module Onlyfansapi
  module Resources
    class SavedForLater
      class Messages
        class Settings
          def retrieve: (
            String account,
            ?request_options: Onlyfansapi::request_opts
          ) -> Onlyfansapi::Models::SavedForLater::Messages::SettingRetrieveResponse

          def disable_automatic_messaging: (
            String account,
            ?request_options: Onlyfansapi::request_opts
          ) -> Onlyfansapi::Models::SavedForLater::Messages::SettingDisableAutomaticMessagingResponse

          def enable_or_update_automatic_messaging: (
            String account,
            period: Onlyfansapi::Models::SavedForLater::Messages::SettingEnableOrUpdateAutomaticMessagingParams::period,
            ?request_options: Onlyfansapi::request_opts
          ) -> Onlyfansapi::Models::SavedForLater::Messages::SettingEnableOrUpdateAutomaticMessagingResponse

          def initialize: (client: Onlyfansapi::Client) -> void
        end
      end
    end
  end
end
