module Onlyfansapi
  module Models
    module Users
      type subscribe_delete_params =
        { account: String, user_id: String, reason: String }
        & Onlyfansapi::Internal::Type::request_parameters

      class SubscribeDeleteParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor user_id: String

        attr_accessor reason: String

        def initialize: (
          account: String,
          user_id: String,
          reason: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          user_id: String,
          reason: String,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
