module Onlyfans
  module Resources
    class Fans
      class Notes
        def clear_notes: (
          String fan_id,
          account: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Fans::NoteClearNotesResponse

        def create_edit_notes: (
          String fan_id,
          account: String,
          notes: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Fans::NoteCreateEditNotesResponse

        def get_notes: (
          String fan_id,
          account: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Fans::NoteGetNotesResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
