module Onlyfansapi
  module Models
    module UserLists
      type user_add_params =
        { account: String, user_list_id: Integer, ids: ::Array[String] }
        & Onlyfansapi::Internal::Type::request_parameters

      class UserAddParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor user_list_id: Integer

        attr_accessor ids: ::Array[String]

        def initialize: (
          account: String,
          user_list_id: Integer,
          ids: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          user_list_id: Integer,
          ids: ::Array[String],
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
