module Onlyfans
  module Models
    type authenticate_start_params =
      {
        _internal_automatic_syncs_disabled: bool,
        auth_id: String,
        auth_type: Onlyfans::Models::AuthenticateStartParams::auth_type,
        cookies: String,
        custom_proxy: Onlyfans::AuthenticateStartParams::CustomProxy,
        email: String,
        force_connect: bool,
        name: String,
        password: String,
        proxy_country: Onlyfans::Models::AuthenticateStartParams::proxy_country,
        user_agent: String,
        xbc: String
      }
      & Onlyfans::Internal::Type::request_parameters

    class AuthenticateStartParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_reader _internal_automatic_syncs_disabled: bool?

      def _internal_automatic_syncs_disabled=: (bool) -> bool

      attr_reader auth_id: String?

      def auth_id=: (String) -> String

      attr_reader auth_type: Onlyfans::Models::AuthenticateStartParams::auth_type?

      def auth_type=: (
        Onlyfans::Models::AuthenticateStartParams::auth_type
      ) -> Onlyfans::Models::AuthenticateStartParams::auth_type

      attr_reader cookies: String?

      def cookies=: (String) -> String

      attr_reader custom_proxy: Onlyfans::AuthenticateStartParams::CustomProxy?

      def custom_proxy=: (
        Onlyfans::AuthenticateStartParams::CustomProxy
      ) -> Onlyfans::AuthenticateStartParams::CustomProxy

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader force_connect: bool?

      def force_connect=: (bool) -> bool

      attr_reader name: String?

      def name=: (String) -> String

      attr_reader password: String?

      def password=: (String) -> String

      attr_reader proxy_country: Onlyfans::Models::AuthenticateStartParams::proxy_country?

      def proxy_country=: (
        Onlyfans::Models::AuthenticateStartParams::proxy_country
      ) -> Onlyfans::Models::AuthenticateStartParams::proxy_country

      attr_reader user_agent: String?

      def user_agent=: (String) -> String

      attr_reader xbc: String?

      def xbc=: (String) -> String

      def initialize: (
        ?_internal_automatic_syncs_disabled: bool,
        ?auth_id: String,
        ?auth_type: Onlyfans::Models::AuthenticateStartParams::auth_type,
        ?cookies: String,
        ?custom_proxy: Onlyfans::AuthenticateStartParams::CustomProxy,
        ?email: String,
        ?force_connect: bool,
        ?name: String,
        ?password: String,
        ?proxy_country: Onlyfans::Models::AuthenticateStartParams::proxy_country,
        ?user_agent: String,
        ?xbc: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        _internal_automatic_syncs_disabled: bool,
        auth_id: String,
        auth_type: Onlyfans::Models::AuthenticateStartParams::auth_type,
        cookies: String,
        custom_proxy: Onlyfans::AuthenticateStartParams::CustomProxy,
        email: String,
        force_connect: bool,
        name: String,
        password: String,
        proxy_country: Onlyfans::Models::AuthenticateStartParams::proxy_country,
        user_agent: String,
        xbc: String,
        request_options: Onlyfans::RequestOptions
      }

      type auth_type = :email_password | :raw_data | :mobile_app

      module AuthType
        extend Onlyfans::Internal::Type::Enum

        EMAIL_PASSWORD: :email_password
        RAW_DATA: :raw_data
        MOBILE_APP: :mobile_app

        def self?.values: -> ::Array[Onlyfans::Models::AuthenticateStartParams::auth_type]
      end

      type custom_proxy =
        { host: String, password: String, port: Integer, username: String }

      class CustomProxy < Onlyfans::Internal::Type::BaseModel
        attr_reader host: String?

        def host=: (String) -> String

        attr_reader password: String?

        def password=: (String) -> String

        attr_reader port: Integer?

        def port=: (Integer) -> Integer

        attr_reader username: String?

        def username=: (String) -> String

        def initialize: (
          ?host: String,
          ?password: String,
          ?port: Integer,
          ?username: String
        ) -> void

        def to_hash: -> {
          host: String,
          password: String,
          port: Integer,
          username: String
        }
      end

      type proxy_country = :us | :uk

      module ProxyCountry
        extend Onlyfans::Internal::Type::Enum

        US: :us
        UK: :uk

        def self?.values: -> ::Array[Onlyfans::Models::AuthenticateStartParams::proxy_country]
      end
    end
  end
end
