module Onlyfans
  module Models
    type authenticate_poll_status_params =
      { attempt_id: String } & Onlyfans::Internal::Type::request_parameters

    class AuthenticatePollStatusParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor attempt_id: String

      def initialize: (
        attempt_id: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        attempt_id: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
