module Onlyfans
  module Models
    type banking_list_available_payout_systems_params =
      { account: String } & Onlyfans::Internal::Type::request_parameters

    class BankingListAvailablePayoutSystemsParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      def initialize: (
        account: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
