module Onlyfans
  module Models
    type bundle_create_params =
      {
        account: String,
        discount: Onlyfans::Models::BundleCreateParams::discount,
        duration: Onlyfans::Models::BundleCreateParams::duration
      }
      & Onlyfans::Internal::Type::request_parameters

    class BundleCreateParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor discount: Onlyfans::Models::BundleCreateParams::discount

      attr_accessor duration: Onlyfans::Models::BundleCreateParams::duration

      def initialize: (
        account: String,
        discount: Onlyfans::Models::BundleCreateParams::discount,
        duration: Onlyfans::Models::BundleCreateParams::duration,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        discount: Onlyfans::Models::BundleCreateParams::discount,
        duration: Onlyfans::Models::BundleCreateParams::duration,
        request_options: Onlyfans::RequestOptions
      }

      type discount = 0 | 5 | 10 | 15 | 20 | 25 | 30 | 35 | 40 | 45 | 50

      module Discount
        extend Onlyfans::Internal::Type::Enum

        DISCOUNT_0: 0
        DISCOUNT_5: 5
        DISCOUNT_10: 10
        DISCOUNT_15: 15
        DISCOUNT_20: 20
        DISCOUNT_25: 25
        DISCOUNT_30: 30
        DISCOUNT_35: 35
        DISCOUNT_40: 40
        DISCOUNT_45: 45
        DISCOUNT_50: 50

        def self?.values: -> ::Array[Onlyfans::Models::BundleCreateParams::discount]
      end

      type duration = 3 | 6 | 12

      module Duration
        extend Onlyfans::Internal::Type::Enum

        DURATION_3: 3
        DURATION_6: 6
        DURATION_12: 12

        def self?.values: -> ::Array[Onlyfans::Models::BundleCreateParams::duration]
      end
    end
  end
end
