module Onlyfans
  module Models
    type bundle_delete_response =
      {
        _meta: Onlyfans::Models::BundleDeleteResponse::Meta,
        data: Onlyfans::Models::BundleDeleteResponse::Data
      }

    class BundleDeleteResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::BundleDeleteResponse::Meta?

      def _meta=: (
        Onlyfans::Models::BundleDeleteResponse::Meta
      ) -> Onlyfans::Models::BundleDeleteResponse::Meta

      attr_reader data: Onlyfans::Models::BundleDeleteResponse::Data?

      def data=: (
        Onlyfans::Models::BundleDeleteResponse::Data
      ) -> Onlyfans::Models::BundleDeleteResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::BundleDeleteResponse::Meta,
        ?data: Onlyfans::Models::BundleDeleteResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::BundleDeleteResponse::Meta,
        data: Onlyfans::Models::BundleDeleteResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::BundleDeleteResponse::Meta::Cache,
          _credits: Onlyfans::Models::BundleDeleteResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::BundleDeleteResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::BundleDeleteResponse::Meta::Cache
        ) -> Onlyfans::Models::BundleDeleteResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::BundleDeleteResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::BundleDeleteResponse::Meta::Credits
        ) -> Onlyfans::Models::BundleDeleteResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits
        ) -> Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::BundleDeleteResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::BundleDeleteResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::BundleDeleteResponse::Meta::Cache,
          _credits: Onlyfans::Models::BundleDeleteResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::BundleDeleteResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_accessor limit_day: String?

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_accessor remaining_day: String?

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: String?,
            ?limit_minute: Integer,
            ?notice: String,
            ?remaining_day: String?,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          id: Integer,
          can_buy: bool,
          discount: Integer,
          duration: Integer,
          price: Integer
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader can_buy: bool?

        def can_buy=: (bool) -> bool

        attr_reader discount: Integer?

        def discount=: (Integer) -> Integer

        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_reader price: Integer?

        def price=: (Integer) -> Integer

        def initialize: (
          ?id: Integer,
          ?can_buy: bool,
          ?discount: Integer,
          ?duration: Integer,
          ?price: Integer
        ) -> void

        def to_hash: -> {
          id: Integer,
          can_buy: bool,
          discount: Integer,
          duration: Integer,
          price: Integer
        }
      end
    end
  end
end
