module Onlyfans
  module Models
    type client_session_create_response =
      {
        _meta: Onlyfans::Models::ClientSessionCreateResponse::Meta,
        data: Onlyfans::Models::ClientSessionCreateResponse::Data
      }

    class ClientSessionCreateResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::ClientSessionCreateResponse::Meta?

      def _meta=: (
        Onlyfans::Models::ClientSessionCreateResponse::Meta
      ) -> Onlyfans::Models::ClientSessionCreateResponse::Meta

      attr_reader data: Onlyfans::Models::ClientSessionCreateResponse::Data?

      def data=: (
        Onlyfans::Models::ClientSessionCreateResponse::Data
      ) -> Onlyfans::Models::ClientSessionCreateResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::ClientSessionCreateResponse::Meta,
        ?data: Onlyfans::Models::ClientSessionCreateResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::ClientSessionCreateResponse::Meta,
        data: Onlyfans::Models::ClientSessionCreateResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache
        ) -> Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits
        ) -> Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits
        ) -> Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::ClientSessionCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::ClientSessionCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::ClientSessionCreateResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        { token: String, client_reference_id: String, display_name: String }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader token: String?

        def token=: (String) -> String

        attr_reader client_reference_id: String?

        def client_reference_id=: (String) -> String

        attr_reader display_name: String?

        def display_name=: (String) -> String

        def initialize: (
          ?token: String,
          ?client_reference_id: String,
          ?display_name: String
        ) -> void

        def to_hash: -> {
          token: String,
          client_reference_id: String,
          display_name: String
        }
      end
    end
  end
end
