module Onlyfans
  module Models
    type data_export_create_params =
      {
        end_date: String,
        file_type: Onlyfans::Models::DataExportCreateParams::file_type,
        start_date: String,
        type: Onlyfans::Models::DataExportCreateParams::type_,
        account_ids: ::Array[String],
        auto_start: bool,
        export_columns: ::Array[String],
        options: ::Hash[Symbol, top]
      }
      & Onlyfans::Internal::Type::request_parameters

    class DataExportCreateParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor end_date: String

      attr_accessor file_type: Onlyfans::Models::DataExportCreateParams::file_type

      attr_accessor start_date: String

      attr_accessor type: Onlyfans::Models::DataExportCreateParams::type_

      attr_reader account_ids: ::Array[String]?

      def account_ids=: (::Array[String]) -> ::Array[String]

      attr_reader auto_start: bool?

      def auto_start=: (bool) -> bool

      attr_reader export_columns: ::Array[String]?

      def export_columns=: (::Array[String]) -> ::Array[String]

      attr_reader options: ::Hash[Symbol, top]?

      def options=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        end_date: String,
        file_type: Onlyfans::Models::DataExportCreateParams::file_type,
        start_date: String,
        type: Onlyfans::Models::DataExportCreateParams::type_,
        ?account_ids: ::Array[String],
        ?auto_start: bool,
        ?export_columns: ::Array[String],
        ?options: ::Hash[Symbol, top],
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        end_date: String,
        file_type: Onlyfans::Models::DataExportCreateParams::file_type,
        start_date: String,
        type: Onlyfans::Models::DataExportCreateParams::type_,
        account_ids: ::Array[String],
        auto_start: bool,
        export_columns: ::Array[String],
        options: ::Hash[Symbol, top],
        request_options: Onlyfans::RequestOptions
      }

      type file_type = :csv | :xlsx | :zip

      module FileType
        extend Onlyfans::Internal::Type::Enum

        CSV: :csv
        XLSX: :xlsx
        ZIP: :zip

        def self?.values: -> ::Array[Onlyfans::Models::DataExportCreateParams::file_type]
      end

      type type_ =
        :transactions
        | :chat_messages
        | :media_vault
        | :trial_links
        | :tracking_links
        | :smart_links
        | :payouts
        | :chargebacks
        | :public_profiles
        | :fans
        | :followings
        | :profile_visitors
        | :fansly_chat_messages

      module Type
        extend Onlyfans::Internal::Type::Enum

        TRANSACTIONS: :transactions
        CHAT_MESSAGES: :chat_messages
        MEDIA_VAULT: :media_vault
        TRIAL_LINKS: :trial_links
        TRACKING_LINKS: :tracking_links
        SMART_LINKS: :smart_links
        PAYOUTS: :payouts
        CHARGEBACKS: :chargebacks
        PUBLIC_PROFILES: :public_profiles
        FANS: :fans
        FOLLOWINGS: :followings
        PROFILE_VISITORS: :profile_visitors
        FANSLY_CHAT_MESSAGES: :fansly_chat_messages

        def self?.values: -> ::Array[Onlyfans::Models::DataExportCreateParams::type_]
      end
    end
  end
end
