module Onlyfans
  module Models
    type following_list_active_response =
      {
        _meta: Onlyfans::Models::FollowingListActiveResponse::Meta,
        _pagination: Onlyfans::Models::FollowingListActiveResponse::Pagination,
        data: Onlyfans::Models::FollowingListActiveResponse::Data
      }

    class FollowingListActiveResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::FollowingListActiveResponse::Meta?

      def _meta=: (
        Onlyfans::Models::FollowingListActiveResponse::Meta
      ) -> Onlyfans::Models::FollowingListActiveResponse::Meta

      attr_reader _pagination: Onlyfans::Models::FollowingListActiveResponse::Pagination?

      def _pagination=: (
        Onlyfans::Models::FollowingListActiveResponse::Pagination
      ) -> Onlyfans::Models::FollowingListActiveResponse::Pagination

      attr_reader data: Onlyfans::Models::FollowingListActiveResponse::Data?

      def data=: (
        Onlyfans::Models::FollowingListActiveResponse::Data
      ) -> Onlyfans::Models::FollowingListActiveResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::FollowingListActiveResponse::Meta,
        ?_pagination: Onlyfans::Models::FollowingListActiveResponse::Pagination,
        ?data: Onlyfans::Models::FollowingListActiveResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::FollowingListActiveResponse::Meta,
        _pagination: Onlyfans::Models::FollowingListActiveResponse::Pagination,
        data: Onlyfans::Models::FollowingListActiveResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::FollowingListActiveResponse::Meta::Cache,
          _credits: Onlyfans::Models::FollowingListActiveResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::FollowingListActiveResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::FollowingListActiveResponse::Meta::Cache
        ) -> Onlyfans::Models::FollowingListActiveResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::FollowingListActiveResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::FollowingListActiveResponse::Meta::Credits
        ) -> Onlyfans::Models::FollowingListActiveResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits
        ) -> Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::FollowingListActiveResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::FollowingListActiveResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::FollowingListActiveResponse::Meta::Cache,
          _credits: Onlyfans::Models::FollowingListActiveResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::FollowingListActiveResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type pagination = { next_page: String }

      class Pagination < Onlyfans::Internal::Type::BaseModel
        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (?next_page: String) -> void

        def to_hash: -> { next_page: String }
      end

      type data =
        {
          has_more: bool,
          list: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader has_more: bool?

        def has_more=: (bool) -> bool

        attr_reader list: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]?

        def list=: (
          ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]
        ) -> ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]

        def initialize: (
          ?has_more: bool,
          ?list: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]
        ) -> void

        def to_hash: -> {
          has_more: bool,
          list: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List]
        }

        type list =
          {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_receive_chat_message: bool,
            can_report: bool,
            can_restrict: bool,
            can_trial_send: bool,
            can_unsubscribe: bool,
            current_subscribe_price: Integer,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            header: String,
            header_size: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize,
            header_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs,
            hide_chat: bool,
            is_blocked: bool,
            is_paywall_required: bool,
            is_pending_autoprolong: bool,
            is_performer: bool,
            is_real_performer: bool,
            is_restricted: bool,
            is_verified: bool,
            last_seen: String?,
            lists_states: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState],
            name: String,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_data: Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_data: String?,
            subscribed_on_duration: String?,
            subscribed_on_expired_now: String?,
            subscribe_price: Integer,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

        class List < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader avatar: String?

          def avatar=: (String) -> String

          attr_reader avatar_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs?

          def avatar_thumbs=: (
            Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs
          ) -> Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs

          attr_reader can_add_subscriber: bool?

          def can_add_subscriber=: (bool) -> bool

          attr_reader can_comment_story: bool?

          def can_comment_story=: (bool) -> bool

          attr_reader can_earn: bool?

          def can_earn=: (bool) -> bool

          attr_reader can_look_story: bool?

          def can_look_story=: (bool) -> bool

          attr_reader can_pay_internal: bool?

          def can_pay_internal=: (bool) -> bool

          attr_reader can_receive_chat_message: bool?

          def can_receive_chat_message=: (bool) -> bool

          attr_reader can_report: bool?

          def can_report=: (bool) -> bool

          attr_reader can_restrict: bool?

          def can_restrict=: (bool) -> bool

          attr_reader can_trial_send: bool?

          def can_trial_send=: (bool) -> bool

          attr_reader can_unsubscribe: bool?

          def can_unsubscribe=: (bool) -> bool

          attr_reader current_subscribe_price: Integer?

          def current_subscribe_price=: (Integer) -> Integer

          attr_reader has_not_viewed_story: bool?

          def has_not_viewed_story=: (bool) -> bool

          attr_reader has_scheduled_stream: bool?

          def has_scheduled_stream=: (bool) -> bool

          attr_reader has_stories: bool?

          def has_stories=: (bool) -> bool

          attr_reader has_stream: bool?

          def has_stream=: (bool) -> bool

          attr_reader header: String?

          def header=: (String) -> String

          attr_reader header_size: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize?

          def header_size=: (
            Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize
          ) -> Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize

          attr_reader header_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs?

          def header_thumbs=: (
            Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs
          ) -> Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs

          attr_reader hide_chat: bool?

          def hide_chat=: (bool) -> bool

          attr_reader is_blocked: bool?

          def is_blocked=: (bool) -> bool

          attr_reader is_paywall_required: bool?

          def is_paywall_required=: (bool) -> bool

          attr_reader is_pending_autoprolong: bool?

          def is_pending_autoprolong=: (bool) -> bool

          attr_reader is_performer: bool?

          def is_performer=: (bool) -> bool

          attr_reader is_real_performer: bool?

          def is_real_performer=: (bool) -> bool

          attr_reader is_restricted: bool?

          def is_restricted=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_accessor last_seen: String?

          attr_reader lists_states: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState]?

          def lists_states=: (
            ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState]
          ) -> ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState]

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader subscribed_by: bool?

          def subscribed_by=: (bool) -> bool

          attr_reader subscribed_by_autoprolong: bool?

          def subscribed_by_autoprolong=: (bool) -> bool

          attr_reader subscribed_by_data: Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData?

          def subscribed_by_data=: (
            Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData
          ) -> Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData

          attr_reader subscribed_by_expire: bool?

          def subscribed_by_expire=: (bool) -> bool

          attr_reader subscribed_by_expire_date: String?

          def subscribed_by_expire_date=: (String) -> String

          attr_reader subscribed_is_expired_now: bool?

          def subscribed_is_expired_now=: (bool) -> bool

          attr_reader subscribed_on: bool?

          def subscribed_on=: (bool) -> bool

          attr_accessor subscribed_on_data: String?

          attr_accessor subscribed_on_duration: String?

          attr_accessor subscribed_on_expired_now: String?

          attr_reader subscribe_price: Integer?

          def subscribe_price=: (Integer) -> Integer

          attr_reader tips_enabled: bool?

          def tips_enabled=: (bool) -> bool

          attr_reader tips_max: Integer?

          def tips_max=: (Integer) -> Integer

          attr_reader tips_min: Integer?

          def tips_min=: (Integer) -> Integer

          attr_reader tips_min_internal: Integer?

          def tips_min_internal=: (Integer) -> Integer

          attr_reader tips_text_enabled: bool?

          def tips_text_enabled=: (bool) -> bool

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader view: String?

          def view=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?avatar: String,
            ?avatar_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs,
            ?can_add_subscriber: bool,
            ?can_comment_story: bool,
            ?can_earn: bool,
            ?can_look_story: bool,
            ?can_pay_internal: bool,
            ?can_receive_chat_message: bool,
            ?can_report: bool,
            ?can_restrict: bool,
            ?can_trial_send: bool,
            ?can_unsubscribe: bool,
            ?current_subscribe_price: Integer,
            ?has_not_viewed_story: bool,
            ?has_scheduled_stream: bool,
            ?has_stories: bool,
            ?has_stream: bool,
            ?header: String,
            ?header_size: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize,
            ?header_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs,
            ?hide_chat: bool,
            ?is_blocked: bool,
            ?is_paywall_required: bool,
            ?is_pending_autoprolong: bool,
            ?is_performer: bool,
            ?is_real_performer: bool,
            ?is_restricted: bool,
            ?is_verified: bool,
            ?last_seen: String?,
            ?lists_states: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState],
            ?name: String,
            ?subscribed_by: bool,
            ?subscribed_by_autoprolong: bool,
            ?subscribed_by_data: Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData,
            ?subscribed_by_expire: bool,
            ?subscribed_by_expire_date: String,
            ?subscribed_is_expired_now: bool,
            ?subscribed_on: bool,
            ?subscribed_on_data: String?,
            ?subscribed_on_duration: String?,
            ?subscribed_on_expired_now: String?,
            ?subscribe_price: Integer,
            ?tips_enabled: bool,
            ?tips_max: Integer,
            ?tips_min: Integer,
            ?tips_min_internal: Integer,
            ?tips_text_enabled: bool,
            ?username: String,
            ?view: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::AvatarThumbs,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_receive_chat_message: bool,
            can_report: bool,
            can_restrict: bool,
            can_trial_send: bool,
            can_unsubscribe: bool,
            current_subscribe_price: Integer,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            header: String,
            header_size: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderSize,
            header_thumbs: Onlyfans::Models::FollowingListActiveResponse::Data::List::HeaderThumbs,
            hide_chat: bool,
            is_blocked: bool,
            is_paywall_required: bool,
            is_pending_autoprolong: bool,
            is_performer: bool,
            is_real_performer: bool,
            is_restricted: bool,
            is_verified: bool,
            last_seen: String?,
            lists_states: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::ListsState],
            name: String,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_data: Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_data: String?,
            subscribed_on_duration: String?,
            subscribed_on_expired_now: String?,
            subscribe_price: Integer,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

          type avatar_thumbs = { :c144 => String, :c50 => String }

          class AvatarThumbs < Onlyfans::Internal::Type::BaseModel
            attr_reader c144: String?

            def c144=: (String) -> String

            attr_reader c50: String?

            def c50=: (String) -> String

            def initialize: (?c144: String, ?c50: String) -> void

            def to_hash: -> { :c144 => String, :c50 => String }
          end

          type header_size = { height: Integer, width: Integer }

          class HeaderSize < Onlyfans::Internal::Type::BaseModel
            attr_reader height: Integer?

            def height=: (Integer) -> Integer

            attr_reader width: Integer?

            def width=: (Integer) -> Integer

            def initialize: (?height: Integer, ?width: Integer) -> void

            def to_hash: -> { height: Integer, width: Integer }
          end

          type header_thumbs = { :w480 => String, :w760 => String }

          class HeaderThumbs < Onlyfans::Internal::Type::BaseModel
            attr_reader w480: String?

            def w480=: (String) -> String

            attr_reader w760: String?

            def w760=: (String) -> String

            def initialize: (?w480: String, ?w760: String) -> void

            def to_hash: -> { :w480 => String, :w760 => String }
          end

          type lists_state =
            {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }

          class ListsState < Onlyfans::Internal::Type::BaseModel
            attr_reader id: String?

            def id=: (String) -> String

            attr_reader can_add_user: bool?

            def can_add_user=: (bool) -> bool

            attr_reader cannot_add_user_reason: String?

            def cannot_add_user_reason=: (String) -> String

            attr_reader has_user: bool?

            def has_user=: (bool) -> bool

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?id: String,
              ?can_add_user: bool,
              ?cannot_add_user_reason: String,
              ?has_user: bool,
              ?name: String,
              ?type: String
            ) -> void

            def to_hash: -> {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }
          end

          type subscribed_by_data =
            {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              new_price: Integer,
              price: Integer,
              regular_price: Integer,
              renewed_at: String,
              show_posts_in_feed: bool,
              status: String?,
              subscribe_at: String,
              subscribe_price: Integer,
              subscribes: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe],
              unsubscribe_reason: String
            }

          class SubscribedByData < Onlyfans::Internal::Type::BaseModel
            attr_accessor discount_finished_at: String?

            attr_reader discount_percent: Integer?

            def discount_percent=: (Integer) -> Integer

            attr_reader discount_period: Integer?

            def discount_period=: (Integer) -> Integer

            attr_accessor discount_started_at: String?

            attr_reader duration: String?

            def duration=: (String) -> String

            attr_reader expired_at: String?

            def expired_at=: (String) -> String

            attr_reader has_active_paid_subscriptions: bool?

            def has_active_paid_subscriptions=: (bool) -> bool

            attr_reader is_muted: bool?

            def is_muted=: (bool) -> bool

            attr_reader new_price: Integer?

            def new_price=: (Integer) -> Integer

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader regular_price: Integer?

            def regular_price=: (Integer) -> Integer

            attr_reader renewed_at: String?

            def renewed_at=: (String) -> String

            attr_reader show_posts_in_feed: bool?

            def show_posts_in_feed=: (bool) -> bool

            attr_accessor status: String?

            attr_reader subscribe_at: String?

            def subscribe_at=: (String) -> String

            attr_reader subscribe_price: Integer?

            def subscribe_price=: (Integer) -> Integer

            attr_reader subscribes: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe]?

            def subscribes=: (
              ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe]
            ) -> ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe]

            attr_reader unsubscribe_reason: String?

            def unsubscribe_reason=: (String) -> String

            def initialize: (
              ?discount_finished_at: String?,
              ?discount_percent: Integer,
              ?discount_period: Integer,
              ?discount_started_at: String?,
              ?duration: String,
              ?expired_at: String,
              ?has_active_paid_subscriptions: bool,
              ?is_muted: bool,
              ?new_price: Integer,
              ?price: Integer,
              ?regular_price: Integer,
              ?renewed_at: String,
              ?show_posts_in_feed: bool,
              ?status: String?,
              ?subscribe_at: String,
              ?subscribe_price: Integer,
              ?subscribes: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe],
              ?unsubscribe_reason: String
            ) -> void

            def to_hash: -> {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              new_price: Integer,
              price: Integer,
              regular_price: Integer,
              renewed_at: String,
              show_posts_in_feed: bool,
              status: String?,
              subscribe_at: String,
              subscribe_price: Integer,
              subscribes: ::Array[Onlyfans::Models::FollowingListActiveResponse::Data::List::SubscribedByData::Subscribe],
              unsubscribe_reason: String
            }

            type subscribe =
              {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }

            class Subscribe < Onlyfans::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader action: String?

              def action=: (String) -> String

              attr_accessor cancel_date: String?

              attr_reader date: String?

              def date=: (String) -> String

              attr_reader discount: Integer?

              def discount=: (Integer) -> Integer

              attr_reader duration: Integer?

              def duration=: (Integer) -> Integer

              attr_reader earning_id: Integer?

              def earning_id=: (Integer) -> Integer

              attr_reader expire_date: String?

              def expire_date=: (String) -> String

              attr_reader is_current: bool?

              def is_current=: (bool) -> bool

              attr_accessor offer_end: String?

              attr_accessor offer_start: String?

              attr_reader price: Integer?

              def price=: (Integer) -> Integer

              attr_reader regular_price: Integer?

              def regular_price=: (Integer) -> Integer

              attr_reader start_date: String?

              def start_date=: (String) -> String

              attr_reader subscriber_id: Integer?

              def subscriber_id=: (Integer) -> Integer

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader user_id: Integer?

              def user_id=: (Integer) -> Integer

              def initialize: (
                ?id: Integer,
                ?action: String,
                ?cancel_date: String?,
                ?date: String,
                ?discount: Integer,
                ?duration: Integer,
                ?earning_id: Integer,
                ?expire_date: String,
                ?is_current: bool,
                ?offer_end: String?,
                ?offer_start: String?,
                ?price: Integer,
                ?regular_price: Integer,
                ?start_date: String,
                ?subscriber_id: Integer,
                ?type: String,
                ?user_id: Integer
              ) -> void

              def to_hash: -> {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }
            end
          end
        end
      end
    end
  end
end
