module Onlyfans
  module Models
    type me_get_top_percentage_response =
      {
        _meta: Onlyfans::Models::MeGetTopPercentageResponse::Meta,
        data: Onlyfans::Models::MeGetTopPercentageResponse::Data
      }

    class MeGetTopPercentageResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::MeGetTopPercentageResponse::Meta?

      def _meta=: (
        Onlyfans::Models::MeGetTopPercentageResponse::Meta
      ) -> Onlyfans::Models::MeGetTopPercentageResponse::Meta

      attr_reader data: Onlyfans::Models::MeGetTopPercentageResponse::Data?

      def data=: (
        Onlyfans::Models::MeGetTopPercentageResponse::Data
      ) -> Onlyfans::Models::MeGetTopPercentageResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::MeGetTopPercentageResponse::Meta,
        ?data: Onlyfans::Models::MeGetTopPercentageResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::MeGetTopPercentageResponse::Meta,
        data: Onlyfans::Models::MeGetTopPercentageResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache,
          _credits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache
        ) -> Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits
        ) -> Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits
        ) -> Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Cache,
          _credits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::MeGetTopPercentageResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data = { message: String?, top_percentage: Float }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_accessor message: String?

        attr_reader top_percentage: Float?

        def top_percentage=: (Float) -> Float

        def initialize: (?message: String?, ?top_percentage: Float) -> void

        def to_hash: -> { message: String?, top_percentage: Float }
      end
    end
  end
end
