module Onlyfans
  module Models
    type media_scrape_params =
      {
        account: String,
        expiration_date: String?,
        file_type: Onlyfans::Models::MediaScrapeParams::file_type?,
        media_id: Integer?,
        public: bool?,
        url: String?
      }
      & Onlyfans::Internal::Type::request_parameters

    class MediaScrapeParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor expiration_date: String?

      attr_accessor file_type: Onlyfans::Models::MediaScrapeParams::file_type?

      attr_accessor media_id: Integer?

      attr_accessor public: bool?

      attr_accessor url: String?

      def initialize: (
        account: String,
        ?expiration_date: String?,
        ?file_type: Onlyfans::Models::MediaScrapeParams::file_type?,
        ?media_id: Integer?,
        ?public: bool?,
        ?url: String?,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        expiration_date: String?,
        file_type: Onlyfans::Models::MediaScrapeParams::file_type?,
        media_id: Integer?,
        public: bool?,
        url: String?,
        request_options: Onlyfans::RequestOptions
      }

      type file_type = :full | :thumb | :preview | :squarePreview

      module FileType
        extend Onlyfans::Internal::Type::Enum

        FULL: :full
        THUMB: :thumb
        PREVIEW: :preview
        SQUARE_PREVIEW: :squarePreview

        def self?.values: -> ::Array[Onlyfans::Models::MediaScrapeParams::file_type]
      end
    end
  end
end
