module Onlyfans
  module Models
    type media_scrape_response =
      { expiration_date: String, temporary_url: String }

    class MediaScrapeResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader expiration_date: String?

      def expiration_date=: (String) -> String

      attr_reader temporary_url: String?

      def temporary_url=: (String) -> String

      def initialize: (?expiration_date: String, ?temporary_url: String) -> void

      def to_hash: -> { expiration_date: String, temporary_url: String }
    end
  end
end
