module Onlyfans
  module Models
    type payout_list_requests_response =
      {
        _meta: Onlyfans::Models::PayoutListRequestsResponse::Meta,
        data: Onlyfans::Models::PayoutListRequestsResponse::Data
      }

    class PayoutListRequestsResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::PayoutListRequestsResponse::Meta?

      def _meta=: (
        Onlyfans::Models::PayoutListRequestsResponse::Meta
      ) -> Onlyfans::Models::PayoutListRequestsResponse::Meta

      attr_reader data: Onlyfans::Models::PayoutListRequestsResponse::Data?

      def data=: (
        Onlyfans::Models::PayoutListRequestsResponse::Data
      ) -> Onlyfans::Models::PayoutListRequestsResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::PayoutListRequestsResponse::Meta,
        ?data: Onlyfans::Models::PayoutListRequestsResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::PayoutListRequestsResponse::Meta,
        data: Onlyfans::Models::PayoutListRequestsResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache,
          _credits: Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache
        ) -> Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits
        ) -> Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits
        ) -> Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::PayoutListRequestsResponse::Meta::Cache,
          _credits: Onlyfans::Models::PayoutListRequestsResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::PayoutListRequestsResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          list: ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List],
          marker: Integer
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader list: ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List]?

        def list=: (
          ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List]
        ) -> ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List]

        attr_reader marker: Integer?

        def marker=: (Integer) -> Integer

        def initialize: (
          ?list: ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List],
          ?marker: Integer
        ) -> void

        def to_hash: -> {
          list: ::Array[Onlyfans::Models::PayoutListRequestsResponse::Data::List],
          marker: Integer
        }

        type list =
          {
            amount: Integer,
            created_at: String,
            currency: String,
            invoice_id: String,
            reject_reason: String?,
            state: String
          }

        class List < Onlyfans::Internal::Type::BaseModel
          attr_reader amount: Integer?

          def amount=: (Integer) -> Integer

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader currency: String?

          def currency=: (String) -> String

          attr_reader invoice_id: String?

          def invoice_id=: (String) -> String

          attr_accessor reject_reason: String?

          attr_reader state: String?

          def state=: (String) -> String

          def initialize: (
            ?amount: Integer,
            ?created_at: String,
            ?currency: String,
            ?invoice_id: String,
            ?reject_reason: String?,
            ?state: String
          ) -> void

          def to_hash: -> {
            amount: Integer,
            created_at: String,
            currency: String,
            invoice_id: String,
            reject_reason: String?,
            state: String
          }
        end
      end
    end
  end
end
