module Onlyfans
  module Models
    type payout_list_requests_params =
      { account: String, limit: String, offset: String }
      & Onlyfans::Internal::Type::request_parameters

    class PayoutListRequestsParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader limit: String?

      def limit=: (String) -> String

      attr_reader offset: String?

      def offset=: (String) -> String

      def initialize: (
        account: String,
        ?limit: String,
        ?offset: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: String,
        offset: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
