module Onlyfans
  module Models
    type post_stats_params =
      { account: String, post_id: Integer, with_historical_data: bool }
      & Onlyfans::Internal::Type::request_parameters

    class PostStatsParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor post_id: Integer

      attr_reader with_historical_data: bool?

      def with_historical_data=: (bool) -> bool

      def initialize: (
        account: String,
        post_id: Integer,
        ?with_historical_data: bool,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        post_id: Integer,
        with_historical_data: bool,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
