module Onlyfans
  module Models
    type post_create_response =
      {
        _meta: Onlyfans::Models::PostCreateResponse::Meta,
        data: Onlyfans::Models::PostCreateResponse::Data
      }

    class PostCreateResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::PostCreateResponse::Meta?

      def _meta=: (
        Onlyfans::Models::PostCreateResponse::Meta
      ) -> Onlyfans::Models::PostCreateResponse::Meta

      attr_reader data: Onlyfans::Models::PostCreateResponse::Data?

      def data=: (
        Onlyfans::Models::PostCreateResponse::Data
      ) -> Onlyfans::Models::PostCreateResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::PostCreateResponse::Meta,
        ?data: Onlyfans::Models::PostCreateResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::PostCreateResponse::Meta,
        data: Onlyfans::Models::PostCreateResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::PostCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::PostCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::PostCreateResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::PostCreateResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::PostCreateResponse::Meta::Cache
        ) -> Onlyfans::Models::PostCreateResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::PostCreateResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::PostCreateResponse::Meta::Credits
        ) -> Onlyfans::Models::PostCreateResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::PostCreateResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::PostCreateResponse::Meta::RateLimits
        ) -> Onlyfans::Models::PostCreateResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::PostCreateResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::PostCreateResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::PostCreateResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::PostCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::PostCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::PostCreateResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          id: Integer,
          author: Onlyfans::Models::PostCreateResponse::Data::Author,
          can_comment: bool,
          can_delete: bool,
          can_edit: bool,
          can_toggle_favorite: bool,
          can_view_media: bool,
          is_markdown_disabled: bool,
          is_opened: bool,
          media: ::Array[Onlyfans::Models::PostCreateResponse::Data::Media],
          media_count: Integer,
          posted_at: String,
          posted_at_precise: String,
          raw_text: String,
          response_type: String,
          text: String,
          tips_amount: String
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader author: Onlyfans::Models::PostCreateResponse::Data::Author?

        def author=: (
          Onlyfans::Models::PostCreateResponse::Data::Author
        ) -> Onlyfans::Models::PostCreateResponse::Data::Author

        attr_reader can_comment: bool?

        def can_comment=: (bool) -> bool

        attr_reader can_delete: bool?

        def can_delete=: (bool) -> bool

        attr_reader can_edit: bool?

        def can_edit=: (bool) -> bool

        attr_reader can_toggle_favorite: bool?

        def can_toggle_favorite=: (bool) -> bool

        attr_reader can_view_media: bool?

        def can_view_media=: (bool) -> bool

        attr_reader is_markdown_disabled: bool?

        def is_markdown_disabled=: (bool) -> bool

        attr_reader is_opened: bool?

        def is_opened=: (bool) -> bool

        attr_reader media: ::Array[Onlyfans::Models::PostCreateResponse::Data::Media]?

        def media=: (
          ::Array[Onlyfans::Models::PostCreateResponse::Data::Media]
        ) -> ::Array[Onlyfans::Models::PostCreateResponse::Data::Media]

        attr_reader media_count: Integer?

        def media_count=: (Integer) -> Integer

        attr_reader posted_at: String?

        def posted_at=: (String) -> String

        attr_reader posted_at_precise: String?

        def posted_at_precise=: (String) -> String

        attr_reader raw_text: String?

        def raw_text=: (String) -> String

        attr_reader response_type: String?

        def response_type=: (String) -> String

        attr_reader text: String?

        def text=: (String) -> String

        attr_reader tips_amount: String?

        def tips_amount=: (String) -> String

        def initialize: (
          ?id: Integer,
          ?author: Onlyfans::Models::PostCreateResponse::Data::Author,
          ?can_comment: bool,
          ?can_delete: bool,
          ?can_edit: bool,
          ?can_toggle_favorite: bool,
          ?can_view_media: bool,
          ?is_markdown_disabled: bool,
          ?is_opened: bool,
          ?media: ::Array[Onlyfans::Models::PostCreateResponse::Data::Media],
          ?media_count: Integer,
          ?posted_at: String,
          ?posted_at_precise: String,
          ?raw_text: String,
          ?response_type: String,
          ?text: String,
          ?tips_amount: String
        ) -> void

        def to_hash: -> {
          id: Integer,
          author: Onlyfans::Models::PostCreateResponse::Data::Author,
          can_comment: bool,
          can_delete: bool,
          can_edit: bool,
          can_toggle_favorite: bool,
          can_view_media: bool,
          is_markdown_disabled: bool,
          is_opened: bool,
          media: ::Array[Onlyfans::Models::PostCreateResponse::Data::Media],
          media_count: Integer,
          posted_at: String,
          posted_at_precise: String,
          raw_text: String,
          response_type: String,
          text: String,
          tips_amount: String
        }

        type author =
          {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_create_lists: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_send_chat_to_all: bool,
            can_trial_send: bool,
            credits_max: Integer,
            credits_min: Integer,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            has_stripe: bool,
            header: String,
            header_size: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize,
            header_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs,
            is_paywall_passed: bool,
            is_stripe_exist: bool,
            is_verified: bool,
            name: String,
            show_media_count: bool,
            show_posts_in_feed: bool,
            subscribed_by: bool,
            subscribe_price: Float,
            subscription_bundles: ::Array[top],
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

        class Author < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader avatar: String?

          def avatar=: (String) -> String

          attr_reader avatar_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs?

          def avatar_thumbs=: (
            Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs
          ) -> Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs

          attr_reader can_add_subscriber: bool?

          def can_add_subscriber=: (bool) -> bool

          attr_reader can_comment_story: bool?

          def can_comment_story=: (bool) -> bool

          attr_reader can_create_lists: bool?

          def can_create_lists=: (bool) -> bool

          attr_reader can_earn: bool?

          def can_earn=: (bool) -> bool

          attr_reader can_look_story: bool?

          def can_look_story=: (bool) -> bool

          attr_reader can_pay_internal: bool?

          def can_pay_internal=: (bool) -> bool

          attr_reader can_send_chat_to_all: bool?

          def can_send_chat_to_all=: (bool) -> bool

          attr_reader can_trial_send: bool?

          def can_trial_send=: (bool) -> bool

          attr_reader credits_max: Integer?

          def credits_max=: (Integer) -> Integer

          attr_reader credits_min: Integer?

          def credits_min=: (Integer) -> Integer

          attr_reader has_not_viewed_story: bool?

          def has_not_viewed_story=: (bool) -> bool

          attr_reader has_scheduled_stream: bool?

          def has_scheduled_stream=: (bool) -> bool

          attr_reader has_stories: bool?

          def has_stories=: (bool) -> bool

          attr_reader has_stream: bool?

          def has_stream=: (bool) -> bool

          attr_reader has_stripe: bool?

          def has_stripe=: (bool) -> bool

          attr_reader header: String?

          def header=: (String) -> String

          attr_reader header_size: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize?

          def header_size=: (
            Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize
          ) -> Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize

          attr_reader header_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs?

          def header_thumbs=: (
            Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs
          ) -> Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs

          attr_reader is_paywall_passed: bool?

          def is_paywall_passed=: (bool) -> bool

          attr_reader is_stripe_exist: bool?

          def is_stripe_exist=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader show_media_count: bool?

          def show_media_count=: (bool) -> bool

          attr_reader show_posts_in_feed: bool?

          def show_posts_in_feed=: (bool) -> bool

          attr_reader subscribed_by: bool?

          def subscribed_by=: (bool) -> bool

          attr_reader subscribe_price: Float?

          def subscribe_price=: (Float) -> Float

          attr_reader subscription_bundles: ::Array[top]?

          def subscription_bundles=: (::Array[top]) -> ::Array[top]

          attr_reader tips_enabled: bool?

          def tips_enabled=: (bool) -> bool

          attr_reader tips_max: Integer?

          def tips_max=: (Integer) -> Integer

          attr_reader tips_min: Integer?

          def tips_min=: (Integer) -> Integer

          attr_reader tips_min_internal: Integer?

          def tips_min_internal=: (Integer) -> Integer

          attr_reader tips_text_enabled: bool?

          def tips_text_enabled=: (bool) -> bool

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader view: String?

          def view=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?avatar: String,
            ?avatar_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs,
            ?can_add_subscriber: bool,
            ?can_comment_story: bool,
            ?can_create_lists: bool,
            ?can_earn: bool,
            ?can_look_story: bool,
            ?can_pay_internal: bool,
            ?can_send_chat_to_all: bool,
            ?can_trial_send: bool,
            ?credits_max: Integer,
            ?credits_min: Integer,
            ?has_not_viewed_story: bool,
            ?has_scheduled_stream: bool,
            ?has_stories: bool,
            ?has_stream: bool,
            ?has_stripe: bool,
            ?header: String,
            ?header_size: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize,
            ?header_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs,
            ?is_paywall_passed: bool,
            ?is_stripe_exist: bool,
            ?is_verified: bool,
            ?name: String,
            ?show_media_count: bool,
            ?show_posts_in_feed: bool,
            ?subscribed_by: bool,
            ?subscribe_price: Float,
            ?subscription_bundles: ::Array[top],
            ?tips_enabled: bool,
            ?tips_max: Integer,
            ?tips_min: Integer,
            ?tips_min_internal: Integer,
            ?tips_text_enabled: bool,
            ?username: String,
            ?view: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::AvatarThumbs,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_create_lists: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_send_chat_to_all: bool,
            can_trial_send: bool,
            credits_max: Integer,
            credits_min: Integer,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            has_stripe: bool,
            header: String,
            header_size: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderSize,
            header_thumbs: Onlyfans::Models::PostCreateResponse::Data::Author::HeaderThumbs,
            is_paywall_passed: bool,
            is_stripe_exist: bool,
            is_verified: bool,
            name: String,
            show_media_count: bool,
            show_posts_in_feed: bool,
            subscribed_by: bool,
            subscribe_price: Float,
            subscription_bundles: ::Array[top],
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

          type avatar_thumbs = { :c144 => String, :c50 => String }

          class AvatarThumbs < Onlyfans::Internal::Type::BaseModel
            attr_reader c144: String?

            def c144=: (String) -> String

            attr_reader c50: String?

            def c50=: (String) -> String

            def initialize: (?c144: String, ?c50: String) -> void

            def to_hash: -> { :c144 => String, :c50 => String }
          end

          type header_size = { height: Integer, width: Integer }

          class HeaderSize < Onlyfans::Internal::Type::BaseModel
            attr_reader height: Integer?

            def height=: (Integer) -> Integer

            attr_reader width: Integer?

            def width=: (Integer) -> Integer

            def initialize: (?height: Integer, ?width: Integer) -> void

            def to_hash: -> { height: Integer, width: Integer }
          end

          type header_thumbs = { :w480 => String, :w760 => String }

          class HeaderThumbs < Onlyfans::Internal::Type::BaseModel
            attr_reader w480: String?

            def w480=: (String) -> String

            attr_reader w760: String?

            def w760=: (String) -> String

            def initialize: (?w480: String, ?w760: String) -> void

            def to_hash: -> { :w480 => String, :w760 => String }
          end
        end

        type media =
          {
            id: Integer,
            can_view: bool,
            converted_to_video: bool,
            created_at: String,
            duration: Integer,
            files: Onlyfans::Models::PostCreateResponse::Data::Media::Files,
            has_custom_preview: bool,
            has_error: bool,
            is_ready: bool,
            release_forms: ::Array[top],
            type: String
          }

        class Media < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader can_view: bool?

          def can_view=: (bool) -> bool

          attr_reader converted_to_video: bool?

          def converted_to_video=: (bool) -> bool

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader duration: Integer?

          def duration=: (Integer) -> Integer

          attr_reader files: Onlyfans::Models::PostCreateResponse::Data::Media::Files?

          def files=: (
            Onlyfans::Models::PostCreateResponse::Data::Media::Files
          ) -> Onlyfans::Models::PostCreateResponse::Data::Media::Files

          attr_reader has_custom_preview: bool?

          def has_custom_preview=: (bool) -> bool

          attr_reader has_error: bool?

          def has_error=: (bool) -> bool

          attr_reader is_ready: bool?

          def is_ready=: (bool) -> bool

          attr_reader release_forms: ::Array[top]?

          def release_forms=: (::Array[top]) -> ::Array[top]

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?can_view: bool,
            ?converted_to_video: bool,
            ?created_at: String,
            ?duration: Integer,
            ?files: Onlyfans::Models::PostCreateResponse::Data::Media::Files,
            ?has_custom_preview: bool,
            ?has_error: bool,
            ?is_ready: bool,
            ?release_forms: ::Array[top],
            ?type: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            can_view: bool,
            converted_to_video: bool,
            created_at: String,
            duration: Integer,
            files: Onlyfans::Models::PostCreateResponse::Data::Media::Files,
            has_custom_preview: bool,
            has_error: bool,
            is_ready: bool,
            release_forms: ::Array[top],
            type: String
          }

          type files =
            {
              full: Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full,
              preview: String?,
              square_preview: String?,
              thumb: String?
            }

          class Files < Onlyfans::Internal::Type::BaseModel
            attr_reader full: Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full?

            def full=: (
              Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full
            ) -> Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full

            attr_accessor preview: String?

            attr_accessor square_preview: String?

            attr_accessor thumb: String?

            def initialize: (
              ?full: Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full,
              ?preview: String?,
              ?square_preview: String?,
              ?thumb: String?
            ) -> void

            def to_hash: -> {
              full: Onlyfans::Models::PostCreateResponse::Data::Media::Files::Full,
              preview: String?,
              square_preview: String?,
              thumb: String?
            }

            type full =
              {
                height: Integer,
                size: Integer,
                sources: ::Array[top],
                url: String?,
                width: Integer
              }

            class Full < Onlyfans::Internal::Type::BaseModel
              attr_reader height: Integer?

              def height=: (Integer) -> Integer

              attr_reader size: Integer?

              def size=: (Integer) -> Integer

              attr_reader sources: ::Array[top]?

              def sources=: (::Array[top]) -> ::Array[top]

              attr_accessor url: String?

              attr_reader width: Integer?

              def width=: (Integer) -> Integer

              def initialize: (
                ?height: Integer,
                ?size: Integer,
                ?sources: ::Array[top],
                ?url: String?,
                ?width: Integer
              ) -> void

              def to_hash: -> {
                height: Integer,
                size: Integer,
                sources: ::Array[top],
                url: String?,
                width: Integer
              }
            end
          end
        end
      end
    end
  end
end
