module Onlyfans
  module Models
    type post_archive_params =
      { account: String, post_id: Integer, private_archive: bool }
      & Onlyfans::Internal::Type::request_parameters

    class PostArchiveParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor post_id: Integer

      attr_reader private_archive: bool?

      def private_archive=: (bool) -> bool

      def initialize: (
        account: String,
        post_id: Integer,
        ?private_archive: bool,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        post_id: Integer,
        private_archive: bool,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
