module Onlyfans
  module Models
    type queue_count_response =
      {
        _meta: Onlyfans::Models::QueueCountResponse::Meta,
        data: Onlyfans::Models::QueueCountResponse::Data
      }

    class QueueCountResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::QueueCountResponse::Meta?

      def _meta=: (
        Onlyfans::Models::QueueCountResponse::Meta
      ) -> Onlyfans::Models::QueueCountResponse::Meta

      attr_reader data: Onlyfans::Models::QueueCountResponse::Data?

      def data=: (
        Onlyfans::Models::QueueCountResponse::Data
      ) -> Onlyfans::Models::QueueCountResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::QueueCountResponse::Meta,
        ?data: Onlyfans::Models::QueueCountResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::QueueCountResponse::Meta,
        data: Onlyfans::Models::QueueCountResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::QueueCountResponse::Meta::Cache,
          _credits: Onlyfans::Models::QueueCountResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::QueueCountResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::QueueCountResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::QueueCountResponse::Meta::Cache
        ) -> Onlyfans::Models::QueueCountResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::QueueCountResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::QueueCountResponse::Meta::Credits
        ) -> Onlyfans::Models::QueueCountResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::QueueCountResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::QueueCountResponse::Meta::RateLimits
        ) -> Onlyfans::Models::QueueCountResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::QueueCountResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::QueueCountResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::QueueCountResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::QueueCountResponse::Meta::Cache,
          _credits: Onlyfans::Models::QueueCountResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::QueueCountResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          list: Onlyfans::Models::QueueCountResponse::Data::List,
          sync_in_process: bool
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader list: Onlyfans::Models::QueueCountResponse::Data::List?

        def list=: (
          Onlyfans::Models::QueueCountResponse::Data::List
        ) -> Onlyfans::Models::QueueCountResponse::Data::List

        attr_reader sync_in_process: bool?

        def sync_in_process=: (bool) -> bool

        def initialize: (
          ?list: Onlyfans::Models::QueueCountResponse::Data::List,
          ?sync_in_process: bool
        ) -> void

        def to_hash: -> {
          list: Onlyfans::Models::QueueCountResponse::Data::List,
          sync_in_process: bool
        }

        type list =
          {
            :number_2025_01_01 => Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01,
            :number_2025_01_02 => Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02
          }

        class List < Onlyfans::Internal::Type::BaseModel
          attr_reader number_2025_01_01: Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01?

          def number_2025_01_01=: (
            Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01
          ) -> Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01

          attr_reader number_2025_01_02: Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02?

          def number_2025_01_02=: (
            Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02
          ) -> Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02

          def initialize: (
            ?number_2025_01_01: Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01,
            ?number_2025_01_02: Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02
          ) -> void

          def to_hash: -> {
            :number_2025_01_01 => Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_01,
            :number_2025_01_02 => Onlyfans::Models::QueueCountResponse::Data::List::Const2025_01_02
          }

          type const2025_01_01 = { post: Integer }

          class Const2025_01_01 < Onlyfans::Internal::Type::BaseModel
            attr_reader post: Integer?

            def post=: (Integer) -> Integer

            def initialize: (?post: Integer) -> void

            def to_hash: -> { post: Integer }
          end

          type const2025_01_02 = { chat: Integer, post: Integer }

          class Const2025_01_02 < Onlyfans::Internal::Type::BaseModel
            attr_reader chat: Integer?

            def chat=: (Integer) -> Integer

            attr_reader post: Integer?

            def post=: (Integer) -> Integer

            def initialize: (?chat: Integer, ?post: Integer) -> void

            def to_hash: -> { chat: Integer, post: Integer }
          end
        end
      end
    end
  end
end
