module Onlyfans
  module Models
    type release_form_create_invitation_link_response =
      {
        _meta: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta,
        data: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data
      }

    class ReleaseFormCreateInvitationLinkResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta?

      def _meta=: (
        Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta
      ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta

      attr_reader data: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data?

      def data=: (
        Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data
      ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta,
        ?data: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta,
        data: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache,
          _credits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache
        ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits
        ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits
        ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Cache,
          _credits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          id: Integer,
          token: String,
          date: String,
          invitation_url: String,
          name: String,
          type: String,
          user: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader token: String?

        def token=: (String) -> String

        attr_reader date: String?

        def date=: (String) -> String

        attr_reader invitation_url: String?

        def invitation_url=: (String) -> String

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader type: String?

        def type=: (String) -> String

        attr_reader user: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User?

        def user=: (
          Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User
        ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User

        def initialize: (
          ?id: Integer,
          ?token: String,
          ?date: String,
          ?invitation_url: String,
          ?name: String,
          ?type: String,
          ?user: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User
        ) -> void

        def to_hash: -> {
          id: Integer,
          token: String,
          date: String,
          invitation_url: String,
          name: String,
          type: String,
          user: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User
        }

        type user =
          {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs,
            is_active: bool,
            is_deleted: bool,
            is_verified: bool,
            name: String,
            username: String,
            view: String
          }

        class User < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader avatar: String?

          def avatar=: (String) -> String

          attr_reader avatar_thumbs: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs?

          def avatar_thumbs=: (
            Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs
          ) -> Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs

          attr_reader is_active: bool?

          def is_active=: (bool) -> bool

          attr_reader is_deleted: bool?

          def is_deleted=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader view: String?

          def view=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?avatar: String,
            ?avatar_thumbs: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs,
            ?is_active: bool,
            ?is_deleted: bool,
            ?is_verified: bool,
            ?name: String,
            ?username: String,
            ?view: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            avatar: String,
            avatar_thumbs: Onlyfans::Models::ReleaseFormCreateInvitationLinkResponse::Data::User::AvatarThumbs,
            is_active: bool,
            is_deleted: bool,
            is_verified: bool,
            name: String,
            username: String,
            view: String
          }

          type avatar_thumbs = { :c144 => String, :c50 => String }

          class AvatarThumbs < Onlyfans::Internal::Type::BaseModel
            attr_reader c144: String?

            def c144=: (String) -> String

            attr_reader c50: String?

            def c50=: (String) -> String

            def initialize: (?c144: String, ?c50: String) -> void

            def to_hash: -> { :c144 => String, :c50 => String }
          end
        end
      end
    end
  end
end
