module Onlyfans
  module Models
    type shared_tracking_link_list_response =
      {
        _meta: Onlyfans::Models::SharedTrackingLinkListResponse::Meta,
        _pagination: Onlyfans::Models::SharedTrackingLinkListResponse::Pagination,
        data: Onlyfans::Models::SharedTrackingLinkListResponse::Data
      }

    class SharedTrackingLinkListResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::SharedTrackingLinkListResponse::Meta?

      def _meta=: (
        Onlyfans::Models::SharedTrackingLinkListResponse::Meta
      ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Meta

      attr_reader _pagination: Onlyfans::Models::SharedTrackingLinkListResponse::Pagination?

      def _pagination=: (
        Onlyfans::Models::SharedTrackingLinkListResponse::Pagination
      ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Pagination

      attr_reader data: Onlyfans::Models::SharedTrackingLinkListResponse::Data?

      def data=: (
        Onlyfans::Models::SharedTrackingLinkListResponse::Data
      ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::SharedTrackingLinkListResponse::Meta,
        ?_pagination: Onlyfans::Models::SharedTrackingLinkListResponse::Pagination,
        ?data: Onlyfans::Models::SharedTrackingLinkListResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::SharedTrackingLinkListResponse::Meta,
        _pagination: Onlyfans::Models::SharedTrackingLinkListResponse::Pagination,
        data: Onlyfans::Models::SharedTrackingLinkListResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache,
          _credits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache
        ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits
        ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits
        ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Cache,
          _credits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::SharedTrackingLinkListResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_accessor limit_day: String?

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_accessor remaining_day: String?

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: String?,
            ?limit_minute: Integer,
            ?notice: String,
            ?remaining_day: String?,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }
        end
      end

      type pagination = { next_page: String }

      class Pagination < Onlyfans::Internal::Type::BaseModel
        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (?next_page: String) -> void

        def to_hash: -> { next_page: String }
      end

      type data =
        {
          has_more: bool,
          list: ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader has_more: bool?

        def has_more=: (bool) -> bool

        attr_reader list: ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]?

        def list=: (
          ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]
        ) -> ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]

        def initialize: (
          ?has_more: bool,
          ?list: ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]
        ) -> void

        def to_hash: -> {
          has_more: bool,
          list: ::Array[Onlyfans::Models::SharedTrackingLinkListResponse::Data::List]
        }

        type list =
          {
            id: Integer,
            campaign_code: Integer,
            campaign_name: String,
            campaign_url: String,
            clicks_count: Integer,
            created_at: String,
            end_date: String?,
            is_deleted: bool,
            owner: Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner,
            subscribers_count: Integer,
            tags: ::Array[top]
          }

        class List < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader campaign_code: Integer?

          def campaign_code=: (Integer) -> Integer

          attr_reader campaign_name: String?

          def campaign_name=: (String) -> String

          attr_reader campaign_url: String?

          def campaign_url=: (String) -> String

          attr_reader clicks_count: Integer?

          def clicks_count=: (Integer) -> Integer

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_accessor end_date: String?

          attr_reader is_deleted: bool?

          def is_deleted=: (bool) -> bool

          attr_reader owner: Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner?

          def owner=: (
            Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner
          ) -> Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner

          attr_reader subscribers_count: Integer?

          def subscribers_count=: (Integer) -> Integer

          attr_reader tags: ::Array[top]?

          def tags=: (::Array[top]) -> ::Array[top]

          def initialize: (
            ?id: Integer,
            ?campaign_code: Integer,
            ?campaign_name: String,
            ?campaign_url: String,
            ?clicks_count: Integer,
            ?created_at: String,
            ?end_date: String?,
            ?is_deleted: bool,
            ?owner: Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner,
            ?subscribers_count: Integer,
            ?tags: ::Array[top]
          ) -> void

          def to_hash: -> {
            id: Integer,
            campaign_code: Integer,
            campaign_name: String,
            campaign_url: String,
            clicks_count: Integer,
            created_at: String,
            end_date: String?,
            is_deleted: bool,
            owner: Onlyfans::Models::SharedTrackingLinkListResponse::Data::List::Owner,
            subscribers_count: Integer,
            tags: ::Array[top]
          }

          type owner =
            {
              id: Integer,
              avatar_thumb_url: String,
              name: String,
              username: String
            }

          class Owner < Onlyfans::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader avatar_thumb_url: String?

            def avatar_thumb_url=: (String) -> String

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader username: String?

            def username=: (String) -> String

            def initialize: (
              ?id: Integer,
              ?avatar_thumb_url: String,
              ?name: String,
              ?username: String
            ) -> void

            def to_hash: -> {
              id: Integer,
              avatar_thumb_url: String,
              name: String,
              username: String
            }
          end
        end
      end
    end
  end
end
