module Onlyfans
  module Models
    type smart_link_list_params =
      {
        account_ids: String?,
        filter: Onlyfans::SmartLinkListParams::Filter,
        limit: Integer,
        meta_pixel_ids: String?,
        name: String?,
        offset: Integer,
        pixel_ids: String?
      }
      & Onlyfans::Internal::Type::request_parameters

    class SmartLinkListParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account_ids: String?

      attr_reader filter: Onlyfans::SmartLinkListParams::Filter?

      def filter=: (
        Onlyfans::SmartLinkListParams::Filter
      ) -> Onlyfans::SmartLinkListParams::Filter

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor meta_pixel_ids: String?

      attr_accessor name: String?

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor pixel_ids: String?

      def initialize: (
        ?account_ids: String?,
        ?filter: Onlyfans::SmartLinkListParams::Filter,
        ?limit: Integer,
        ?meta_pixel_ids: String?,
        ?name: String?,
        ?offset: Integer,
        ?pixel_ids: String?,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account_ids: String?,
        filter: Onlyfans::SmartLinkListParams::Filter,
        limit: Integer,
        meta_pixel_ids: String?,
        name: String?,
        offset: Integer,
        pixel_ids: String?,
        request_options: Onlyfans::RequestOptions
      }

      type filter = { tags: ::Array[String] }

      class Filter < Onlyfans::Internal::Type::BaseModel
        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (?tags: ::Array[String]) -> void

        def to_hash: -> { tags: ::Array[String] }
      end
    end
  end
end
