module Onlyfans
  module Models
    type smart_link_delete_params =
      { smart_link_id: String } & Onlyfans::Internal::Type::request_parameters

    class SmartLinkDeleteParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor smart_link_id: String

      def initialize: (
        smart_link_id: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        smart_link_id: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
