module Onlyfans
  module Models
    type smart_link_list_clicks_params =
      {
        smart_link_id: String,
        date_end: String,
        date_start: String,
        include_bots: bool,
        include_duplicates: bool,
        limit: Integer,
        offset: Integer
      }
      & Onlyfans::Internal::Type::request_parameters

    class SmartLinkListClicksParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor smart_link_id: String

      attr_reader date_end: String?

      def date_end=: (String) -> String

      attr_reader date_start: String?

      def date_start=: (String) -> String

      attr_reader include_bots: bool?

      def include_bots=: (bool) -> bool

      attr_reader include_duplicates: bool?

      def include_duplicates=: (bool) -> bool

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize: (
        smart_link_id: String,
        ?date_end: String,
        ?date_start: String,
        ?include_bots: bool,
        ?include_duplicates: bool,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        smart_link_id: String,
        date_end: String,
        date_start: String,
        include_bots: bool,
        include_duplicates: bool,
        limit: Integer,
        offset: Integer,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
