module Onlyfans
  module Models
    type statistic_calculate_total_transactions_params =
      { account: String, end_date: String, start_date: String }
      & Onlyfans::Internal::Type::request_parameters

    class StatisticCalculateTotalTransactionsParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String

      attr_accessor start_date: String

      def initialize: (
        account: String,
        end_date: String,
        start_date: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String,
        start_date: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
