module Onlyfans
  module Models
    type statistic_calculate_total_transactions_response =
      { total_amount: Float, total_transactions: Integer }

    class StatisticCalculateTotalTransactionsResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader total_amount: Float?

      def total_amount=: (Float) -> Float

      attr_reader total_transactions: Integer?

      def total_transactions=: (Integer) -> Integer

      def initialize: (
        ?total_amount: Float,
        ?total_transactions: Integer
      ) -> void

      def to_hash: -> { total_amount: Float, total_transactions: Integer }
    end
  end
end
