module Onlyfans
  module Models
    type story_delete_response =
      {
        _meta: Onlyfans::Models::StoryDeleteResponse::Meta,
        data: Onlyfans::Models::StoryDeleteResponse::Data
      }

    class StoryDeleteResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::StoryDeleteResponse::Meta?

      def _meta=: (
        Onlyfans::Models::StoryDeleteResponse::Meta
      ) -> Onlyfans::Models::StoryDeleteResponse::Meta

      attr_reader data: Onlyfans::Models::StoryDeleteResponse::Data?

      def data=: (
        Onlyfans::Models::StoryDeleteResponse::Data
      ) -> Onlyfans::Models::StoryDeleteResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::StoryDeleteResponse::Meta,
        ?data: Onlyfans::Models::StoryDeleteResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::StoryDeleteResponse::Meta,
        data: Onlyfans::Models::StoryDeleteResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::StoryDeleteResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryDeleteResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::StoryDeleteResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::StoryDeleteResponse::Meta::Cache
        ) -> Onlyfans::Models::StoryDeleteResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::StoryDeleteResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::StoryDeleteResponse::Meta::Credits
        ) -> Onlyfans::Models::StoryDeleteResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits
        ) -> Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::StoryDeleteResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::StoryDeleteResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::StoryDeleteResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryDeleteResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryDeleteResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_accessor limit_day: String?

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_accessor remaining_day: String?

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: String?,
            ?limit_minute: Integer,
            ?notice: String,
            ?remaining_day: String?,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }
        end
      end

      type data = { success: bool }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (?success: bool) -> void

        def to_hash: -> { success: bool }
      end
    end
  end
end
