module Onlyfans
  module Models
    type story_retrieve_stats_response =
      {
        _meta: Onlyfans::Models::StoryRetrieveStatsResponse::Meta,
        data: Onlyfans::Models::StoryRetrieveStatsResponse::Data
      }

    class StoryRetrieveStatsResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::StoryRetrieveStatsResponse::Meta?

      def _meta=: (
        Onlyfans::Models::StoryRetrieveStatsResponse::Meta
      ) -> Onlyfans::Models::StoryRetrieveStatsResponse::Meta

      attr_reader data: Onlyfans::Models::StoryRetrieveStatsResponse::Data?

      def data=: (
        Onlyfans::Models::StoryRetrieveStatsResponse::Data
      ) -> Onlyfans::Models::StoryRetrieveStatsResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::StoryRetrieveStatsResponse::Meta,
        ?data: Onlyfans::Models::StoryRetrieveStatsResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::StoryRetrieveStatsResponse::Meta,
        data: Onlyfans::Models::StoryRetrieveStatsResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache
        ) -> Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits
        ) -> Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits
        ) -> Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryRetrieveStatsResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_accessor limit_day: String?

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_accessor remaining_day: String?

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: String?,
            ?limit_minute: Integer,
            ?notice: String,
            ?remaining_day: String?,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          created_at: String,
          story_comment_all: ::Array[String],
          story_comment_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart],
          story_comment_count: Integer,
          story_like_all: ::Array[String],
          story_like_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart],
          story_like_count: Integer,
          story_look_all: ::Array[String],
          story_look_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart],
          story_look_count: String,
          story_tip_all: ::Array[String],
          story_tip_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart],
          story_tip_count: Integer,
          story_tip_sum: Integer,
          story_tip_sum_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader created_at: String?

        def created_at=: (String) -> String

        attr_reader story_comment_all: ::Array[String]?

        def story_comment_all=: (::Array[String]) -> ::Array[String]

        attr_reader story_comment_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart]?

        def story_comment_chart=: (
          ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart]
        ) -> ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart]

        attr_reader story_comment_count: Integer?

        def story_comment_count=: (Integer) -> Integer

        attr_reader story_like_all: ::Array[String]?

        def story_like_all=: (::Array[String]) -> ::Array[String]

        attr_reader story_like_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart]?

        def story_like_chart=: (
          ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart]
        ) -> ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart]

        attr_reader story_like_count: Integer?

        def story_like_count=: (Integer) -> Integer

        attr_reader story_look_all: ::Array[String]?

        def story_look_all=: (::Array[String]) -> ::Array[String]

        attr_reader story_look_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart]?

        def story_look_chart=: (
          ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart]
        ) -> ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart]

        attr_reader story_look_count: String?

        def story_look_count=: (String) -> String

        attr_reader story_tip_all: ::Array[String]?

        def story_tip_all=: (::Array[String]) -> ::Array[String]

        attr_reader story_tip_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart]?

        def story_tip_chart=: (
          ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart]
        ) -> ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart]

        attr_reader story_tip_count: Integer?

        def story_tip_count=: (Integer) -> Integer

        attr_reader story_tip_sum: Integer?

        def story_tip_sum=: (Integer) -> Integer

        attr_reader story_tip_sum_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]?

        def story_tip_sum_chart=: (
          ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]
        ) -> ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]

        def initialize: (
          ?created_at: String,
          ?story_comment_all: ::Array[String],
          ?story_comment_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart],
          ?story_comment_count: Integer,
          ?story_like_all: ::Array[String],
          ?story_like_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart],
          ?story_like_count: Integer,
          ?story_look_all: ::Array[String],
          ?story_look_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart],
          ?story_look_count: String,
          ?story_tip_all: ::Array[String],
          ?story_tip_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart],
          ?story_tip_count: Integer,
          ?story_tip_sum: Integer,
          ?story_tip_sum_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]
        ) -> void

        def to_hash: -> {
          created_at: String,
          story_comment_all: ::Array[String],
          story_comment_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryCommentChart],
          story_comment_count: Integer,
          story_like_all: ::Array[String],
          story_like_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLikeChart],
          story_like_count: Integer,
          story_look_all: ::Array[String],
          story_look_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryLookChart],
          story_look_count: String,
          story_tip_all: ::Array[String],
          story_tip_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipChart],
          story_tip_count: Integer,
          story_tip_sum: Integer,
          story_tip_sum_chart: ::Array[Onlyfans::Models::StoryRetrieveStatsResponse::Data::StoryTipSumChart]
        }

        type story_comment_chart = { count: Integer, date: String }

        class StoryCommentChart < Onlyfans::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader date: String?

          def date=: (String) -> String

          def initialize: (?count: Integer, ?date: String) -> void

          def to_hash: -> { count: Integer, date: String }
        end

        type story_like_chart = { count: Integer, date: String }

        class StoryLikeChart < Onlyfans::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader date: String?

          def date=: (String) -> String

          def initialize: (?count: Integer, ?date: String) -> void

          def to_hash: -> { count: Integer, date: String }
        end

        type story_look_chart = { count: Integer, date: String }

        class StoryLookChart < Onlyfans::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader date: String?

          def date=: (String) -> String

          def initialize: (?count: Integer, ?date: String) -> void

          def to_hash: -> { count: Integer, date: String }
        end

        type story_tip_chart = { count: Integer, date: String }

        class StoryTipChart < Onlyfans::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader date: String?

          def date=: (String) -> String

          def initialize: (?count: Integer, ?date: String) -> void

          def to_hash: -> { count: Integer, date: String }
        end

        type story_tip_sum_chart = { count: Integer, date: String }

        class StoryTipSumChart < Onlyfans::Internal::Type::BaseModel
          attr_reader count: Integer?

          def count=: (Integer) -> Integer

          attr_reader date: String?

          def date=: (String) -> String

          def initialize: (?count: Integer, ?date: String) -> void

          def to_hash: -> { count: Integer, date: String }
        end
      end
    end
  end
end
