module Onlyfans
  module Models
    type story_list_viewers_response =
      {
        _meta: Onlyfans::Models::StoryListViewersResponse::Meta,
        data: Onlyfans::Models::StoryListViewersResponse::Data
      }

    class StoryListViewersResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::StoryListViewersResponse::Meta?

      def _meta=: (
        Onlyfans::Models::StoryListViewersResponse::Meta
      ) -> Onlyfans::Models::StoryListViewersResponse::Meta

      attr_reader data: Onlyfans::Models::StoryListViewersResponse::Data?

      def data=: (
        Onlyfans::Models::StoryListViewersResponse::Data
      ) -> Onlyfans::Models::StoryListViewersResponse::Data

      def initialize: (
        ?_meta: Onlyfans::Models::StoryListViewersResponse::Meta,
        ?data: Onlyfans::Models::StoryListViewersResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::StoryListViewersResponse::Meta,
        data: Onlyfans::Models::StoryListViewersResponse::Data
      }

      type meta =
        {
          _cache: Onlyfans::Models::StoryListViewersResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryListViewersResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::StoryListViewersResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::StoryListViewersResponse::Meta::Cache
        ) -> Onlyfans::Models::StoryListViewersResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::StoryListViewersResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::StoryListViewersResponse::Meta::Credits
        ) -> Onlyfans::Models::StoryListViewersResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits
        ) -> Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::StoryListViewersResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::StoryListViewersResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::StoryListViewersResponse::Meta::Cache,
          _credits: Onlyfans::Models::StoryListViewersResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::StoryListViewersResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_accessor limit_day: String?

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_accessor remaining_day: String?

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: String?,
            ?limit_minute: Integer,
            ?notice: String,
            ?remaining_day: String?,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: String?,
            limit_minute: Integer,
            notice: String,
            remaining_day: String?,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          has_more: bool,
          list: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader has_more: bool?

        def has_more=: (bool) -> bool

        attr_reader list: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]?

        def list=: (
          ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]
        ) -> ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]

        def initialize: (
          ?has_more: bool,
          ?list: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]
        ) -> void

        def to_hash: -> {
          has_more: bool,
          list: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List]
        }

        type list =
          {
            id: Integer,
            avatar: String?,
            avatar_thumbs: String?,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_report: bool,
            can_restrict: bool,
            current_subscribe_price: Integer,
            display_name: String,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_story_tips: bool,
            has_stream: bool,
            has_top_story_tips: bool,
            header: String?,
            header_size: String?,
            header_thumbs: String?,
            is_restricted: bool,
            is_story_blocked_user: bool,
            is_story_liked: bool,
            is_verified: bool,
            last_seen: String,
            lists_states: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState],
            name: String,
            notice: String,
            show_media_count: bool,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_duration: String,
            subscribed_on_expired_now: bool,
            subscribe_price: Integer,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

        class List < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_accessor avatar: String?

          attr_accessor avatar_thumbs: String?

          attr_reader can_add_subscriber: bool?

          def can_add_subscriber=: (bool) -> bool

          attr_reader can_comment_story: bool?

          def can_comment_story=: (bool) -> bool

          attr_reader can_earn: bool?

          def can_earn=: (bool) -> bool

          attr_reader can_look_story: bool?

          def can_look_story=: (bool) -> bool

          attr_reader can_pay_internal: bool?

          def can_pay_internal=: (bool) -> bool

          attr_reader can_report: bool?

          def can_report=: (bool) -> bool

          attr_reader can_restrict: bool?

          def can_restrict=: (bool) -> bool

          attr_reader current_subscribe_price: Integer?

          def current_subscribe_price=: (Integer) -> Integer

          attr_reader display_name: String?

          def display_name=: (String) -> String

          attr_reader has_not_viewed_story: bool?

          def has_not_viewed_story=: (bool) -> bool

          attr_reader has_scheduled_stream: bool?

          def has_scheduled_stream=: (bool) -> bool

          attr_reader has_stories: bool?

          def has_stories=: (bool) -> bool

          attr_reader has_story_tips: bool?

          def has_story_tips=: (bool) -> bool

          attr_reader has_stream: bool?

          def has_stream=: (bool) -> bool

          attr_reader has_top_story_tips: bool?

          def has_top_story_tips=: (bool) -> bool

          attr_accessor header: String?

          attr_accessor header_size: String?

          attr_accessor header_thumbs: String?

          attr_reader is_restricted: bool?

          def is_restricted=: (bool) -> bool

          attr_reader is_story_blocked_user: bool?

          def is_story_blocked_user=: (bool) -> bool

          attr_reader is_story_liked: bool?

          def is_story_liked=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_reader last_seen: String?

          def last_seen=: (String) -> String

          attr_reader lists_states: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState]?

          def lists_states=: (
            ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState]
          ) -> ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState]

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_reader show_media_count: bool?

          def show_media_count=: (bool) -> bool

          attr_reader subscribed_by: bool?

          def subscribed_by=: (bool) -> bool

          attr_reader subscribed_by_autoprolong: bool?

          def subscribed_by_autoprolong=: (bool) -> bool

          attr_reader subscribed_by_expire: bool?

          def subscribed_by_expire=: (bool) -> bool

          attr_reader subscribed_by_expire_date: String?

          def subscribed_by_expire_date=: (String) -> String

          attr_reader subscribed_is_expired_now: bool?

          def subscribed_is_expired_now=: (bool) -> bool

          attr_reader subscribed_on: bool?

          def subscribed_on=: (bool) -> bool

          attr_reader subscribed_on_duration: String?

          def subscribed_on_duration=: (String) -> String

          attr_reader subscribed_on_expired_now: bool?

          def subscribed_on_expired_now=: (bool) -> bool

          attr_reader subscribe_price: Integer?

          def subscribe_price=: (Integer) -> Integer

          attr_reader tips_enabled: bool?

          def tips_enabled=: (bool) -> bool

          attr_reader tips_max: Integer?

          def tips_max=: (Integer) -> Integer

          attr_reader tips_min: Integer?

          def tips_min=: (Integer) -> Integer

          attr_reader tips_min_internal: Integer?

          def tips_min_internal=: (Integer) -> Integer

          attr_reader tips_text_enabled: bool?

          def tips_text_enabled=: (bool) -> bool

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader view: String?

          def view=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?avatar: String?,
            ?avatar_thumbs: String?,
            ?can_add_subscriber: bool,
            ?can_comment_story: bool,
            ?can_earn: bool,
            ?can_look_story: bool,
            ?can_pay_internal: bool,
            ?can_report: bool,
            ?can_restrict: bool,
            ?current_subscribe_price: Integer,
            ?display_name: String,
            ?has_not_viewed_story: bool,
            ?has_scheduled_stream: bool,
            ?has_stories: bool,
            ?has_story_tips: bool,
            ?has_stream: bool,
            ?has_top_story_tips: bool,
            ?header: String?,
            ?header_size: String?,
            ?header_thumbs: String?,
            ?is_restricted: bool,
            ?is_story_blocked_user: bool,
            ?is_story_liked: bool,
            ?is_verified: bool,
            ?last_seen: String,
            ?lists_states: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState],
            ?name: String,
            ?notice: String,
            ?show_media_count: bool,
            ?subscribed_by: bool,
            ?subscribed_by_autoprolong: bool,
            ?subscribed_by_expire: bool,
            ?subscribed_by_expire_date: String,
            ?subscribed_is_expired_now: bool,
            ?subscribed_on: bool,
            ?subscribed_on_duration: String,
            ?subscribed_on_expired_now: bool,
            ?subscribe_price: Integer,
            ?tips_enabled: bool,
            ?tips_max: Integer,
            ?tips_min: Integer,
            ?tips_min_internal: Integer,
            ?tips_text_enabled: bool,
            ?username: String,
            ?view: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            avatar: String?,
            avatar_thumbs: String?,
            can_add_subscriber: bool,
            can_comment_story: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_report: bool,
            can_restrict: bool,
            current_subscribe_price: Integer,
            display_name: String,
            has_not_viewed_story: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_story_tips: bool,
            has_stream: bool,
            has_top_story_tips: bool,
            header: String?,
            header_size: String?,
            header_thumbs: String?,
            is_restricted: bool,
            is_story_blocked_user: bool,
            is_story_liked: bool,
            is_verified: bool,
            last_seen: String,
            lists_states: ::Array[Onlyfans::Models::StoryListViewersResponse::Data::List::ListsState],
            name: String,
            notice: String,
            show_media_count: bool,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_duration: String,
            subscribed_on_expired_now: bool,
            subscribe_price: Integer,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            view: String
          }

          type lists_state =
            {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }

          class ListsState < Onlyfans::Internal::Type::BaseModel
            attr_reader id: String?

            def id=: (String) -> String

            attr_reader can_add_user: bool?

            def can_add_user=: (bool) -> bool

            attr_reader cannot_add_user_reason: String?

            def cannot_add_user_reason=: (String) -> String

            attr_reader has_user: bool?

            def has_user=: (bool) -> bool

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?id: String,
              ?can_add_user: bool,
              ?cannot_add_user_reason: String,
              ?has_user: bool,
              ?name: String,
              ?type: String
            ) -> void

            def to_hash: -> {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }
          end
        end
      end
    end
  end
end
