module Onlyfans
  module Models
    type stored_list_trial_links_params =
      {
        account: String,
        filter: Onlyfans::StoredListTrialLinksParams::Filter,
        limit: Integer,
        offset: Integer
      }
      & Onlyfans::Internal::Type::request_parameters

    class StoredListTrialLinksParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader filter: Onlyfans::StoredListTrialLinksParams::Filter?

      def filter=: (
        Onlyfans::StoredListTrialLinksParams::Filter
      ) -> Onlyfans::StoredListTrialLinksParams::Filter

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize: (
        account: String,
        ?filter: Onlyfans::StoredListTrialLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfans::StoredListTrialLinksParams::Filter,
        limit: Integer,
        offset: Integer,
        request_options: Onlyfans::RequestOptions
      }

      type filter =
        { include_smart_links: bool, search: String?, tags: ::Array[String] }

      class Filter < Onlyfans::Internal::Type::BaseModel
        attr_reader include_smart_links: bool?

        def include_smart_links=: (bool) -> bool

        attr_accessor search: String?

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?include_smart_links: bool,
          ?search: String?,
          ?tags: ::Array[String]
        ) -> void

        def to_hash: -> {
          include_smart_links: bool,
          search: String?,
          tags: ::Array[String]
        }
      end
    end
  end
end
