module Onlyfans
  module Models
    type tracking_link_create_response =
      {
        _meta: Onlyfans::Models::TrackingLinkCreateResponse::Meta,
        data: ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]
      }

    class TrackingLinkCreateResponse < Onlyfans::Internal::Type::BaseModel
      attr_reader _meta: Onlyfans::Models::TrackingLinkCreateResponse::Meta?

      def _meta=: (
        Onlyfans::Models::TrackingLinkCreateResponse::Meta
      ) -> Onlyfans::Models::TrackingLinkCreateResponse::Meta

      attr_reader data: ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]?

      def data=: (
        ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]
      ) -> ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]

      def initialize: (
        ?_meta: Onlyfans::Models::TrackingLinkCreateResponse::Meta,
        ?data: ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]
      ) -> void

      def to_hash: -> {
        _meta: Onlyfans::Models::TrackingLinkCreateResponse::Meta,
        data: ::Array[Onlyfans::Models::TrackingLinkCreateResponse::Data]
      }

      type meta =
        {
          _cache: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits
        }

      class Meta < Onlyfans::Internal::Type::BaseModel
        attr_reader _cache: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache?

        def _cache=: (
          Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache
        ) -> Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache

        attr_reader _credits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits?

        def _credits=: (
          Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits
        ) -> Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits
        ) -> Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache,
          ?_credits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits,
          ?_rate_limits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Cache,
          _credits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::Credits,
          _rate_limits: Onlyfans::Models::TrackingLinkCreateResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfans::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfans::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfans::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          id: Integer,
          campaign_code: Integer,
          campaign_name: String,
          count_subscribers: Integer,
          count_transitions: Integer,
          created_at: String,
          end_date: String?
        }

      class Data < Onlyfans::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_reader campaign_code: Integer?

        def campaign_code=: (Integer) -> Integer

        attr_reader campaign_name: String?

        def campaign_name=: (String) -> String

        attr_reader count_subscribers: Integer?

        def count_subscribers=: (Integer) -> Integer

        attr_reader count_transitions: Integer?

        def count_transitions=: (Integer) -> Integer

        attr_reader created_at: String?

        def created_at=: (String) -> String

        attr_accessor end_date: String?

        def initialize: (
          ?id: Integer,
          ?campaign_code: Integer,
          ?campaign_name: String,
          ?count_subscribers: Integer,
          ?count_transitions: Integer,
          ?created_at: String,
          ?end_date: String?
        ) -> void

        def to_hash: -> {
          id: Integer,
          campaign_code: Integer,
          campaign_name: String,
          count_subscribers: Integer,
          count_transitions: Integer,
          created_at: String,
          end_date: String?
        }
      end
    end
  end
end
