module Onlyfans
  module Models
    type tracking_link_list_subscribers_params =
      {
        account: String,
        tracking_link_id: String,
        limit: Integer,
        offset: Integer
      }
      & Onlyfans::Internal::Type::request_parameters

    class TrackingLinkListSubscribersParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor tracking_link_id: String

      attr_accessor limit: Integer

      attr_accessor offset: Integer

      def initialize: (
        account: String,
        tracking_link_id: String,
        limit: Integer,
        offset: Integer,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        tracking_link_id: String,
        limit: Integer,
        offset: Integer,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
