module Onlyfans
  module Models
    type trial_link_list_params =
      {
        account: String,
        end_date: String?,
        field: Onlyfans::Models::TrialLinkListParams::field,
        limit: Integer,
        offset: Integer,
        sort: Onlyfans::Models::TrialLinkListParams::sort,
        start_date: String?,
        synchronous: bool
      }
      & Onlyfans::Internal::Type::request_parameters

    class TrialLinkListParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String?

      attr_reader field: Onlyfans::Models::TrialLinkListParams::field?

      def field=: (
        Onlyfans::Models::TrialLinkListParams::field
      ) -> Onlyfans::Models::TrialLinkListParams::field

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_reader sort: Onlyfans::Models::TrialLinkListParams::sort?

      def sort=: (
        Onlyfans::Models::TrialLinkListParams::sort
      ) -> Onlyfans::Models::TrialLinkListParams::sort

      attr_accessor start_date: String?

      attr_reader synchronous: bool?

      def synchronous=: (bool) -> bool

      def initialize: (
        account: String,
        ?end_date: String?,
        ?field: Onlyfans::Models::TrialLinkListParams::field,
        ?limit: Integer,
        ?offset: Integer,
        ?sort: Onlyfans::Models::TrialLinkListParams::sort,
        ?start_date: String?,
        ?synchronous: bool,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String?,
        field: Onlyfans::Models::TrialLinkListParams::field,
        limit: Integer,
        offset: Integer,
        sort: Onlyfans::Models::TrialLinkListParams::sort,
        start_date: String?,
        synchronous: bool,
        request_options: Onlyfans::RequestOptions
      }

      type field =
        :create_date
        | :expire_date
        | :subscribe_counts
        | :subscribe_days
        | :claims_count

      module Field
        extend Onlyfans::Internal::Type::Enum

        CREATE_DATE: :create_date
        EXPIRE_DATE: :expire_date
        SUBSCRIBE_COUNTS: :subscribe_counts
        SUBSCRIBE_DAYS: :subscribe_days
        CLAIMS_COUNT: :claims_count

        def self?.values: -> ::Array[Onlyfans::Models::TrialLinkListParams::field]
      end

      type sort = :asc | :desc

      module Sort
        extend Onlyfans::Internal::Type::Enum

        ASC: :asc
        DESC: :desc

        def self?.values: -> ::Array[Onlyfans::Models::TrialLinkListParams::sort]
      end
    end
  end
end
