module Onlyfans
  module Models
    type trial_link_list_params =
      {
        account: String,
        limit: Integer,
        offset: Integer,
        field: Onlyfans::Models::TrialLinkListParams::field?,
        sort: Onlyfans::Models::TrialLinkListParams::sort?,
        synchronous: bool?
      }
      & Onlyfans::Internal::Type::request_parameters

    class TrialLinkListParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor limit: Integer

      attr_accessor offset: Integer

      attr_accessor field: Onlyfans::Models::TrialLinkListParams::field?

      attr_accessor sort: Onlyfans::Models::TrialLinkListParams::sort?

      attr_accessor synchronous: bool?

      def initialize: (
        account: String,
        limit: Integer,
        offset: Integer,
        ?field: Onlyfans::Models::TrialLinkListParams::field?,
        ?sort: Onlyfans::Models::TrialLinkListParams::sort?,
        ?synchronous: bool?,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: Integer,
        offset: Integer,
        field: Onlyfans::Models::TrialLinkListParams::field?,
        sort: Onlyfans::Models::TrialLinkListParams::sort?,
        synchronous: bool?,
        request_options: Onlyfans::RequestOptions
      }

      type field =
        :create_date
        | :expire_date
        | :subscribe_counts
        | :subscribe_days
        | :claims_count

      module Field
        extend Onlyfans::Internal::Type::Enum

        CREATE_DATE: :create_date
        EXPIRE_DATE: :expire_date
        SUBSCRIBE_COUNTS: :subscribe_counts
        SUBSCRIBE_DAYS: :subscribe_days
        CLAIMS_COUNT: :claims_count

        def self?.values: -> ::Array[Onlyfans::Models::TrialLinkListParams::field]
      end

      type sort = :desc | :asc

      module Sort
        extend Onlyfans::Internal::Type::Enum

        DESC: :desc
        ASC: :asc

        def self?.values: -> ::Array[Onlyfans::Models::TrialLinkListParams::sort]
      end
    end
  end
end
