module Onlyfans
  module Models
    type user_list_params =
      { account: String, ids: String }
      & Onlyfans::Internal::Type::request_parameters

    class UserListParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor ids: String

      def initialize: (
        account: String,
        ids: String,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        ids: String,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
