module Onlyfans
  module Models
    type webhook_update_params =
      {
        webhook_id: String,
        account_scope: String,
        endpoint_url: String,
        events: ::Array[String],
        account_ids: ::Array[String],
        enabled: bool?
      }
      & Onlyfans::Internal::Type::request_parameters

    class WebhookUpdateParams < Onlyfans::Internal::Type::BaseModel
      extend Onlyfans::Internal::Type::RequestParameters::Converter
      include Onlyfans::Internal::Type::RequestParameters

      attr_accessor webhook_id: String

      attr_accessor account_scope: String

      attr_accessor endpoint_url: String

      attr_accessor events: ::Array[String]

      attr_reader account_ids: ::Array[String]?

      def account_ids=: (::Array[String]) -> ::Array[String]

      attr_accessor enabled: bool?

      def initialize: (
        webhook_id: String,
        account_scope: String,
        endpoint_url: String,
        events: ::Array[String],
        ?account_ids: ::Array[String],
        ?enabled: bool?,
        ?request_options: Onlyfans::request_opts
      ) -> void

      def to_hash: -> {
        webhook_id: String,
        account_scope: String,
        endpoint_url: String,
        events: ::Array[String],
        account_ids: ::Array[String],
        enabled: bool?,
        request_options: Onlyfans::RequestOptions
      }
    end
  end
end
