module Onlyfans
  module Resources
    class UserLists
      class Users
        def list: (
          String user_list_id,
          account: String,
          ?limit: String,
          ?offset: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserListResponse

        def add: (
          String user_list_id,
          account: String,
          ids: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserAddResponse

        def clear: (
          String user_list_id,
          account: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserClearResponse

        def list_pinned: (
          String user_list_id,
          account: String,
          ?limit: String,
          ?offset: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserListPinnedResponse

        def pin: (
          Integer user_id,
          account: String,
          user_list_id: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserPinResponse

        def remove: (
          Integer user_id,
          account: String,
          user_list_id: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::UserLists::UserRemoveResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
