module Onlyfansapi
  module Models
    module TrackingLinks
      type tag_list_params =
        { account: String, tracking_link_id: Integer }
        & Onlyfansapi::Internal::Type::request_parameters

      class TagListParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor tracking_link_id: Integer

        def initialize: (
          account: String,
          tracking_link_id: Integer,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          tracking_link_id: Integer,
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
