module Onlyfans
  module Models
    module Stories
      type highlight_retrieve_response =
        {
          _meta: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta,
          data: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data
        }

      class HighlightRetrieveResponse < Onlyfans::Internal::Type::BaseModel
        attr_reader _meta: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta?

        def _meta=: (
          Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta
        ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta

        attr_reader data: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data?

        def data=: (
          Onlyfans::Models::Stories::HighlightRetrieveResponse::Data
        ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data

        def initialize: (
          ?_meta: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta,
          ?data: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta,
          data: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data
        }

        type meta =
          {
            _cache: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache,
            _credits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits
          }

        class Meta < Onlyfans::Internal::Type::BaseModel
          attr_reader _cache: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache?

          def _cache=: (
            Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache
          ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache

          attr_reader _credits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits?

          def _credits=: (
            Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits
          ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits
          ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache,
            ?_credits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits,
            ?_rate_limits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Cache,
            _credits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::Credits,
            _rate_limits: Onlyfans::Models::Stories::HighlightRetrieveResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfans::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfans::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfans::Internal::Type::BaseModel
            attr_accessor limit_day: String?

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader notice: String?

            def notice=: (String) -> String

            attr_accessor remaining_day: String?

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: String?,
              ?limit_minute: Integer,
              ?notice: String,
              ?remaining_day: String?,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }
          end
        end

        type data =
          {
            id: Integer,
            cover: String,
            cover_story_id: Integer,
            created_at: String,
            stories: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story],
            stories_count: Integer,
            title: String,
            user_id: Integer
          }

        class Data < Onlyfans::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader cover: String?

          def cover=: (String) -> String

          attr_reader cover_story_id: Integer?

          def cover_story_id=: (Integer) -> Integer

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader stories: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story]?

          def stories=: (
            ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story]
          ) -> ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story]

          attr_reader stories_count: Integer?

          def stories_count=: (Integer) -> Integer

          attr_reader title: String?

          def title=: (String) -> String

          attr_reader user_id: Integer?

          def user_id=: (Integer) -> Integer

          def initialize: (
            ?id: Integer,
            ?cover: String,
            ?cover_story_id: Integer,
            ?created_at: String,
            ?stories: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story],
            ?stories_count: Integer,
            ?title: String,
            ?user_id: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            cover: String,
            cover_story_id: Integer,
            created_at: String,
            stories: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story],
            stories_count: Integer,
            title: String,
            user_id: Integer
          }

          type story =
            {
              id: Integer,
              can_delete: bool,
              canvas_height: Integer,
              canvas_width: Integer,
              comments_count: Integer,
              created_at: String,
              has_post: bool,
              is_highlight_cover: bool,
              is_last_in_highlight: bool,
              is_ready: bool,
              is_watched: bool,
              likes_count: Integer,
              media: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media],
              question: String?,
              release_forms: ::Array[top],
              texts: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text],
              tips_amount: String,
              tips_amount_raw: Integer,
              tips_count: Integer,
              user_id: Integer,
              viewers: ::Array[top],
              viewers_count: Integer
            }

          class Story < Onlyfans::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader can_delete: bool?

            def can_delete=: (bool) -> bool

            attr_reader canvas_height: Integer?

            def canvas_height=: (Integer) -> Integer

            attr_reader canvas_width: Integer?

            def canvas_width=: (Integer) -> Integer

            attr_reader comments_count: Integer?

            def comments_count=: (Integer) -> Integer

            attr_reader created_at: String?

            def created_at=: (String) -> String

            attr_reader has_post: bool?

            def has_post=: (bool) -> bool

            attr_reader is_highlight_cover: bool?

            def is_highlight_cover=: (bool) -> bool

            attr_reader is_last_in_highlight: bool?

            def is_last_in_highlight=: (bool) -> bool

            attr_reader is_ready: bool?

            def is_ready=: (bool) -> bool

            attr_reader is_watched: bool?

            def is_watched=: (bool) -> bool

            attr_reader likes_count: Integer?

            def likes_count=: (Integer) -> Integer

            attr_reader media: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media]?

            def media=: (
              ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media]
            ) -> ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media]

            attr_accessor question: String?

            attr_reader release_forms: ::Array[top]?

            def release_forms=: (::Array[top]) -> ::Array[top]

            attr_reader texts: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text]?

            def texts=: (
              ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text]
            ) -> ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text]

            attr_reader tips_amount: String?

            def tips_amount=: (String) -> String

            attr_reader tips_amount_raw: Integer?

            def tips_amount_raw=: (Integer) -> Integer

            attr_reader tips_count: Integer?

            def tips_count=: (Integer) -> Integer

            attr_reader user_id: Integer?

            def user_id=: (Integer) -> Integer

            attr_reader viewers: ::Array[top]?

            def viewers=: (::Array[top]) -> ::Array[top]

            attr_reader viewers_count: Integer?

            def viewers_count=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?can_delete: bool,
              ?canvas_height: Integer,
              ?canvas_width: Integer,
              ?comments_count: Integer,
              ?created_at: String,
              ?has_post: bool,
              ?is_highlight_cover: bool,
              ?is_last_in_highlight: bool,
              ?is_ready: bool,
              ?is_watched: bool,
              ?likes_count: Integer,
              ?media: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media],
              ?question: String?,
              ?release_forms: ::Array[top],
              ?texts: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text],
              ?tips_amount: String,
              ?tips_amount_raw: Integer,
              ?tips_count: Integer,
              ?user_id: Integer,
              ?viewers: ::Array[top],
              ?viewers_count: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              can_delete: bool,
              canvas_height: Integer,
              canvas_width: Integer,
              comments_count: Integer,
              created_at: String,
              has_post: bool,
              is_highlight_cover: bool,
              is_last_in_highlight: bool,
              is_ready: bool,
              is_watched: bool,
              likes_count: Integer,
              media: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media],
              question: String?,
              release_forms: ::Array[top],
              texts: ::Array[Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Text],
              tips_amount: String,
              tips_amount_raw: Integer,
              tips_count: Integer,
              user_id: Integer,
              viewers: ::Array[top],
              viewers_count: Integer
            }

            type media =
              {
                id: Integer,
                can_view: bool,
                converted_to_video: bool,
                created_at: String,
                duration: Integer,
                files: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files,
                has_custom_preview: bool,
                has_error: bool,
                is_ready: bool,
                type: String,
                video_sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources
              }

            class Media < Onlyfans::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader can_view: bool?

              def can_view=: (bool) -> bool

              attr_reader converted_to_video: bool?

              def converted_to_video=: (bool) -> bool

              attr_reader created_at: String?

              def created_at=: (String) -> String

              attr_reader duration: Integer?

              def duration=: (Integer) -> Integer

              attr_reader files: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files?

              def files=: (
                Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files
              ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files

              attr_reader has_custom_preview: bool?

              def has_custom_preview=: (bool) -> bool

              attr_reader has_error: bool?

              def has_error=: (bool) -> bool

              attr_reader is_ready: bool?

              def is_ready=: (bool) -> bool

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader video_sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources?

              def video_sources=: (
                Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources
              ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources

              def initialize: (
                ?id: Integer,
                ?can_view: bool,
                ?converted_to_video: bool,
                ?created_at: String,
                ?duration: Integer,
                ?files: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files,
                ?has_custom_preview: bool,
                ?has_error: bool,
                ?is_ready: bool,
                ?type: String,
                ?video_sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources
              ) -> void

              def to_hash: -> {
                id: Integer,
                can_view: bool,
                converted_to_video: bool,
                created_at: String,
                duration: Integer,
                files: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files,
                has_custom_preview: bool,
                has_error: bool,
                is_ready: bool,
                type: String,
                video_sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::VideoSources
              }

              type files =
                {
                  full: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full,
                  preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview,
                  square_preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview,
                  thumb: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb
                }

              class Files < Onlyfans::Internal::Type::BaseModel
                attr_reader full: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full?

                def full=: (
                  Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full
                ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full

                attr_reader preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview?

                def preview=: (
                  Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview
                ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview

                attr_reader square_preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview?

                def square_preview=: (
                  Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview
                ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview

                attr_reader thumb: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb?

                def thumb=: (
                  Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb
                ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb

                def initialize: (
                  ?full: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full,
                  ?preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview,
                  ?square_preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview,
                  ?thumb: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb
                ) -> void

                def to_hash: -> {
                  full: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Full,
                  preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview,
                  square_preview: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview,
                  thumb: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Thumb
                }

                type full =
                  {
                    height: Integer,
                    size: Integer,
                    sources: ::Array[top],
                    url: String,
                    width: Integer
                  }

                class Full < Onlyfans::Internal::Type::BaseModel
                  attr_reader height: Integer?

                  def height=: (Integer) -> Integer

                  attr_reader size: Integer?

                  def size=: (Integer) -> Integer

                  attr_reader sources: ::Array[top]?

                  def sources=: (::Array[top]) -> ::Array[top]

                  attr_reader url: String?

                  def url=: (String) -> String

                  attr_reader width: Integer?

                  def width=: (Integer) -> Integer

                  def initialize: (
                    ?height: Integer,
                    ?size: Integer,
                    ?sources: ::Array[top],
                    ?url: String,
                    ?width: Integer
                  ) -> void

                  def to_hash: -> {
                    height: Integer,
                    size: Integer,
                    sources: ::Array[top],
                    url: String,
                    width: Integer
                  }
                end

                type preview =
                  {
                    height: Integer,
                    size: Integer,
                    sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources,
                    url: String,
                    width: Integer
                  }

                class Preview < Onlyfans::Internal::Type::BaseModel
                  attr_reader height: Integer?

                  def height=: (Integer) -> Integer

                  attr_reader size: Integer?

                  def size=: (Integer) -> Integer

                  attr_reader sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources?

                  def sources=: (
                    Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources
                  ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources

                  attr_reader url: String?

                  def url=: (String) -> String

                  attr_reader width: Integer?

                  def width=: (Integer) -> Integer

                  def initialize: (
                    ?height: Integer,
                    ?size: Integer,
                    ?sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources,
                    ?url: String,
                    ?width: Integer
                  ) -> void

                  def to_hash: -> {
                    height: Integer,
                    size: Integer,
                    sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::Preview::Sources,
                    url: String,
                    width: Integer
                  }

                  type sources = { :w150 => String }

                  class Sources < Onlyfans::Internal::Type::BaseModel
                    attr_reader w150: String?

                    def w150=: (String) -> String

                    def initialize: (?w150: String) -> void

                    def to_hash: -> { :w150 => String }
                  end
                end

                type square_preview =
                  {
                    height: Integer,
                    size: Integer,
                    sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources,
                    url: String,
                    width: Integer
                  }

                class SquarePreview < Onlyfans::Internal::Type::BaseModel
                  attr_reader height: Integer?

                  def height=: (Integer) -> Integer

                  attr_reader size: Integer?

                  def size=: (Integer) -> Integer

                  attr_reader sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources?

                  def sources=: (
                    Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources
                  ) -> Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources

                  attr_reader url: String?

                  def url=: (String) -> String

                  attr_reader width: Integer?

                  def width=: (Integer) -> Integer

                  def initialize: (
                    ?height: Integer,
                    ?size: Integer,
                    ?sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources,
                    ?url: String,
                    ?width: Integer
                  ) -> void

                  def to_hash: -> {
                    height: Integer,
                    size: Integer,
                    sources: Onlyfans::Models::Stories::HighlightRetrieveResponse::Data::Story::Media::Files::SquarePreview::Sources,
                    url: String,
                    width: Integer
                  }

                  type sources = { :w150 => String, :w480 => String }

                  class Sources < Onlyfans::Internal::Type::BaseModel
                    attr_reader w150: String?

                    def w150=: (String) -> String

                    attr_reader w480: String?

                    def w480=: (String) -> String

                    def initialize: (?w150: String, ?w480: String) -> void

                    def to_hash: -> { :w150 => String, :w480 => String }
                  end
                end

                type thumb =
                  {
                    height: Integer,
                    size: Integer,
                    url: String,
                    width: Integer
                  }

                class Thumb < Onlyfans::Internal::Type::BaseModel
                  attr_reader height: Integer?

                  def height=: (Integer) -> Integer

                  attr_reader size: Integer?

                  def size=: (Integer) -> Integer

                  attr_reader url: String?

                  def url=: (String) -> String

                  attr_reader width: Integer?

                  def width=: (Integer) -> Integer

                  def initialize: (
                    ?height: Integer,
                    ?size: Integer,
                    ?url: String,
                    ?width: Integer
                  ) -> void

                  def to_hash: -> {
                    height: Integer,
                    size: Integer,
                    url: String,
                    width: Integer
                  }
                end
              end

              type video_sources =
                { :number_240 => String?, :number_720 => String? }

              class VideoSources < Onlyfans::Internal::Type::BaseModel
                attr_accessor number_240: String?

                attr_accessor number_720: String?

                def initialize: (
                  ?number_240: String?,
                  ?number_720: String?
                ) -> void

                def to_hash: -> {
                  :number_240 => String?,
                  :number_720 => String?
                }
              end
            end

            type text =
              {
                angle: Integer,
                bg_color: String,
                color: String,
                font_family: String,
                font_size: String,
                font_style: String?,
                font_weight: Integer,
                left: Float,
                scale: Float,
                text: String,
                text_align: String,
                text_height: Float,
                text_width: Float,
                top: Float,
                type: String,
                users: ::Array[top],
                z_index: Integer
              }

            class Text < Onlyfans::Internal::Type::BaseModel
              attr_reader angle: Integer?

              def angle=: (Integer) -> Integer

              attr_reader bg_color: String?

              def bg_color=: (String) -> String

              attr_reader color: String?

              def color=: (String) -> String

              attr_reader font_family: String?

              def font_family=: (String) -> String

              attr_reader font_size: String?

              def font_size=: (String) -> String

              attr_accessor font_style: String?

              attr_reader font_weight: Integer?

              def font_weight=: (Integer) -> Integer

              attr_reader left: Float?

              def left=: (Float) -> Float

              attr_reader scale: Float?

              def scale=: (Float) -> Float

              attr_reader text: String?

              def text=: (String) -> String

              attr_reader text_align: String?

              def text_align=: (String) -> String

              attr_reader text_height: Float?

              def text_height=: (Float) -> Float

              attr_reader text_width: Float?

              def text_width=: (Float) -> Float

              attr_reader top: Float?

              def top=: (Float) -> Float

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader users: ::Array[top]?

              def users=: (::Array[top]) -> ::Array[top]

              attr_reader z_index: Integer?

              def z_index=: (Integer) -> Integer

              def initialize: (
                ?angle: Integer,
                ?bg_color: String,
                ?color: String,
                ?font_family: String,
                ?font_size: String,
                ?font_style: String?,
                ?font_weight: Integer,
                ?left: Float,
                ?scale: Float,
                ?text: String,
                ?text_align: String,
                ?text_height: Float,
                ?text_width: Float,
                ?top: Float,
                ?type: String,
                ?users: ::Array[top],
                ?z_index: Integer
              ) -> void

              def to_hash: -> {
                angle: Integer,
                bg_color: String,
                color: String,
                font_family: String,
                font_size: String,
                font_style: String?,
                font_weight: Integer,
                left: Float,
                scale: Float,
                text: String,
                text_align: String,
                text_height: Float,
                text_width: Float,
                top: Float,
                type: String,
                users: ::Array[top],
                z_index: Integer
              }
            end
          end
        end
      end
    end
  end
end
