module Onlyfansapi
  module Internal
    extend Onlyfansapi::Internal::Util::SorbetRuntimeSupport

    type file_input = Pathname | StringIO | IO | String | Onlyfansapi::FilePart

    OMIT: Object
  end
end
