module Onlyfans
  module Models
    module SavedForLater
      module Messages
        type setting_disable_automatic_messaging_params =
          { account: String } & Onlyfans::Internal::Type::request_parameters

        class SettingDisableAutomaticMessagingParams < Onlyfans::Internal::Type::BaseModel
          extend Onlyfans::Internal::Type::RequestParameters::Converter
          include Onlyfans::Internal::Type::RequestParameters

          attr_accessor account: String

          def initialize: (
            account: String,
            ?request_options: Onlyfans::request_opts
          ) -> void

          def to_hash: -> {
            account: String,
            request_options: Onlyfans::RequestOptions
          }
        end
      end
    end
  end
end
