module Onlyfans
  module Resources
    class TrialLinks
      class Tags
        def list: (
          Integer trial_link_id,
          account: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::TrialLinks::TagListResponse

        def add: (
          Integer trial_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::TrialLinks::TagAddResponse

        def remove: (
          Integer trial_link_id,
          account: String,
          tags: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::TrialLinks::TagRemoveResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
