module Onlyfansapi
  module Models
    module SavedForLater
      module Posts
        type setting_enable_or_update_automatic_posting_params =
          {
            account: String,
            period: Onlyfansapi::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period
          }
          & Onlyfansapi::Internal::Type::request_parameters

        class SettingEnableOrUpdateAutomaticPostingParams < Onlyfansapi::Internal::Type::BaseModel
          extend Onlyfansapi::Internal::Type::RequestParameters::Converter
          include Onlyfansapi::Internal::Type::RequestParameters

          attr_accessor account: String

          attr_accessor period: Onlyfansapi::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period

          def initialize: (
            account: String,
            period: Onlyfansapi::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period,
            ?request_options: Onlyfansapi::request_opts
          ) -> void

          def to_hash: -> {
            account: String,
            period: Onlyfansapi::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period,
            request_options: Onlyfansapi::RequestOptions
          }

          type period = 6 | 12 | 24 | 48

          module Period
            extend Onlyfansapi::Internal::Type::Enum

            PERIOD_6: 6
            PERIOD_12: 12
            PERIOD_24: 24
            PERIOD_48: 48

            def self?.values: -> ::Array[Onlyfansapi::Models::SavedForLater::Posts::SettingEnableOrUpdateAutomaticPostingParams::period]
          end
        end
      end
    end
  end
end
