module Onlyfans
  module Models
    module Chats
      type message_send_params =
        {
          account: String,
          chat_id: String,
          block_banned_words: Onlyfans::Models::Chats::MessageSendParams::block_banned_words,
          giphy_id: String,
          locked_text: bool,
          media_files: ::Array[top],
          previews: ::Array[top],
          price: Float,
          reply_to_message_id: Integer,
          rf_guest: String,
          rf_partner: String,
          rf_tag: String,
          text: String
        }
        & Onlyfans::Internal::Type::request_parameters

      class MessageSendParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor chat_id: String

        attr_reader block_banned_words: Onlyfans::Models::Chats::MessageSendParams::block_banned_words?

        def block_banned_words=: (
          Onlyfans::Models::Chats::MessageSendParams::block_banned_words
        ) -> Onlyfans::Models::Chats::MessageSendParams::block_banned_words

        attr_reader giphy_id: String?

        def giphy_id=: (String) -> String

        attr_reader locked_text: bool?

        def locked_text=: (bool) -> bool

        attr_reader media_files: ::Array[top]?

        def media_files=: (::Array[top]) -> ::Array[top]

        attr_reader previews: ::Array[top]?

        def previews=: (::Array[top]) -> ::Array[top]

        attr_reader price: Float?

        def price=: (Float) -> Float

        attr_reader reply_to_message_id: Integer?

        def reply_to_message_id=: (Integer) -> Integer

        attr_reader rf_guest: String?

        def rf_guest=: (String) -> String

        attr_reader rf_partner: String?

        def rf_partner=: (String) -> String

        attr_reader rf_tag: String?

        def rf_tag=: (String) -> String

        attr_reader text: String?

        def text=: (String) -> String

        def initialize: (
          account: String,
          chat_id: String,
          ?block_banned_words: Onlyfans::Models::Chats::MessageSendParams::block_banned_words,
          ?giphy_id: String,
          ?locked_text: bool,
          ?media_files: ::Array[top],
          ?previews: ::Array[top],
          ?price: Float,
          ?reply_to_message_id: Integer,
          ?rf_guest: String,
          ?rf_partner: String,
          ?rf_tag: String,
          ?text: String,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          chat_id: String,
          block_banned_words: Onlyfans::Models::Chats::MessageSendParams::block_banned_words,
          giphy_id: String,
          locked_text: bool,
          media_files: ::Array[top],
          previews: ::Array[top],
          price: Float,
          reply_to_message_id: Integer,
          rf_guest: String,
          rf_partner: String,
          rf_tag: String,
          text: String,
          request_options: Onlyfans::RequestOptions
        }

        type block_banned_words = :strict_ban | :risky | :replace_soften

        module BlockBannedWords
          extend Onlyfans::Internal::Type::Enum

          STRICT_BAN: :strict_ban
          RISKY: :risky
          REPLACE_SOFTEN: :replace_soften

          def self?.values: -> ::Array[Onlyfans::Models::Chats::MessageSendParams::block_banned_words]
        end
      end
    end
  end
end
