module Onlyfans
  module Models
    module UserLists
      type user_pin_params =
        { account: String, user_list_id: String, user_id: Integer }
        & Onlyfans::Internal::Type::request_parameters

      class UserPinParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor user_list_id: String

        attr_accessor user_id: Integer

        def initialize: (
          account: String,
          user_list_id: String,
          user_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          user_list_id: String,
          user_id: Integer,
          request_options: Onlyfans::RequestOptions
        }
      end
    end
  end
end
