module Onlyfans
  module Resources
    class Posts
      class Comments
        def create: (
          String post_id,
          account: String,
          text: String,
          ?answer_to: Integer,
          ?giphy_id: String,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentCreateResponse

        def list: (
          String post_id,
          account: String,
          ?limit: Integer,
          ?offset: Integer,
          ?sort: Onlyfans::Models::Posts::CommentListParams::sort,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentListResponse

        def delete: (
          Integer comment_id,
          account: String,
          post_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentDeleteResponse

        def like: (
          Integer comment_id,
          account: String,
          post_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentLikeResponse

        def pin: (
          Integer comment_id,
          account: String,
          post_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentPinResponse

        def unlike: (
          Integer comment_id,
          account: String,
          post_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentUnlikeResponse

        def unpin: (
          Integer comment_id,
          account: String,
          post_id: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> Onlyfans::Models::Posts::CommentUnpinResponse

        def initialize: (client: Onlyfans::Client) -> void
      end
    end
  end
end
