module Onlyfansapi
  module Resources
    class Media
      class Vault
        attr_reader lists: Onlyfansapi::Resources::Media::Vault::Lists

        def retrieve: (
          Integer media_id,
          account: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Media::VaultRetrieveResponse

        def list: (
          String account,
          ?field: Onlyfansapi::Models::Media::VaultListParams::field,
          ?limit: Integer,
          ?list: Integer,
          ?offset: Integer,
          ?query: String?,
          ?sort: Onlyfansapi::Models::Media::VaultListParams::sort,
          ?type: Onlyfansapi::Models::Media::VaultListParams::type_,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Media::VaultListResponse

        def delete: (
          String account,
          media_ids: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Media::VaultDeleteResponse

        def upload: (
          String account,
          ?async: bool,
          ?file: Onlyfansapi::Internal::file_input,
          ?file_url: String,
          ?request_options: Onlyfansapi::request_opts
        ) -> Onlyfansapi::Models::Media::VaultUploadResponse

        def initialize: (client: Onlyfansapi::Client) -> void
      end
    end
  end
end
