module Onlyfansapi
  module Models
    module Notifications
      type tabs_order_update_params =
        { account: String, tabs: ::Array[String] }
        & Onlyfansapi::Internal::Type::request_parameters

      class TabsOrderUpdateParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor tabs: ::Array[String]

        def initialize: (
          account: String,
          tabs: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          tabs: ::Array[String],
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
