module Onlyfans
  module Models
    module Analytics
      type summary_get_earnings_overview_params =
        { account_ids: ::Array[String], end_date: String, start_date: String }
        & Onlyfans::Internal::Type::request_parameters

      class SummaryGetEarningsOverviewParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account_ids: ::Array[String]

        attr_accessor end_date: String

        attr_accessor start_date: String

        def initialize: (
          account_ids: ::Array[String],
          end_date: String,
          start_date: String,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account_ids: ::Array[String],
          end_date: String,
          start_date: String,
          request_options: Onlyfans::RequestOptions
        }
      end
    end
  end
end
