module Onlyfans
  module Models
    module Analytics
      type summary_get_historical_performance_params =
        {
          time_range: Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range
        }
        & Onlyfans::Internal::Type::request_parameters

      class SummaryGetHistoricalPerformanceParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_reader time_range: Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range?

        def time_range=: (
          Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range
        ) -> Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range

        def initialize: (
          ?time_range: Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          time_range: Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range,
          request_options: Onlyfans::RequestOptions
        }

        type time_range = :"3m" | :"6m" | :"12m" | :ytd | :"last-year"

        module TimeRange
          extend Onlyfans::Internal::Type::Enum

          TIME_RANGE_3M: :"3m"
          TIME_RANGE_6M: :"6m"
          TIME_RANGE_12M: :"12m"
          YTD: :ytd
          LAST_YEAR: :"last-year"

          def self?.values: -> ::Array[Onlyfans::Models::Analytics::SummaryGetHistoricalPerformanceParams::time_range]
        end
      end
    end
  end
end
