module Onlyfansapi
  module Models
    module Analytics
      type financial_get_forecast_params =
        {
          account_ids: ::Array[String],
          forecast_days: Integer,
          historical_days: Integer,
          metric: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric,
          model: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class FinancialGetForecastParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account_ids: ::Array[String]

        attr_accessor forecast_days: Integer

        attr_accessor historical_days: Integer

        attr_accessor metric: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric

        attr_accessor model: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model

        def initialize: (
          account_ids: ::Array[String],
          forecast_days: Integer,
          historical_days: Integer,
          metric: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric,
          model: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account_ids: ::Array[String],
          forecast_days: Integer,
          historical_days: Integer,
          metric: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric,
          model: Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model,
          request_options: Onlyfansapi::RequestOptions
        }

        type metric = :revenue | :churn_percentage

        module Metric
          extend Onlyfansapi::Internal::Type::Enum

          REVENUE: :revenue
          CHURN_PERCENTAGE: :churn_percentage

          def self?.values: -> ::Array[Onlyfansapi::Models::Analytics::FinancialGetForecastParams::metric]
        end

        type model = :moving_average | :linear_regression | :arima | :sarima

        module Model
          extend Onlyfansapi::Internal::Type::Enum

          MOVING_AVERAGE: :moving_average
          LINEAR_REGRESSION: :linear_regression
          ARIMA: :arima
          SARIMA: :sarima

          def self?.values: -> ::Array[Onlyfansapi::Models::Analytics::FinancialGetForecastParams::model]
        end
      end
    end
  end
end
