module Onlyfansapi
  module Models
    module Analytics
      type summary_get_period_comparison_params =
        {
          account_ids: ::Array[String],
          period_a: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodA,
          period_b: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodB,
          granularity: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity,
          stat_type: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class SummaryGetPeriodComparisonParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account_ids: ::Array[String]

        attr_accessor period_a: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodA

        attr_accessor period_b: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodB

        attr_reader granularity: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity?

        def granularity=: (
          Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity
        ) -> Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity

        attr_reader stat_type: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type?

        def stat_type=: (
          Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type
        ) -> Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type

        def initialize: (
          account_ids: ::Array[String],
          period_a: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodA,
          period_b: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodB,
          ?granularity: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity,
          ?stat_type: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type,
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account_ids: ::Array[String],
          period_a: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodA,
          period_b: Onlyfansapi::Analytics::SummaryGetPeriodComparisonParams::PeriodB,
          granularity: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity,
          stat_type: Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type,
          request_options: Onlyfansapi::RequestOptions
        }

        type period_a = { end_: String, start: String }

        class PeriodA < Onlyfansapi::Internal::Type::BaseModel
          attr_accessor end_: String

          attr_accessor start: String

          def initialize: (end_: String, start: String) -> void

          def to_hash: -> { end_: String, start: String }
        end

        type period_b = { end_: String, start: String }

        class PeriodB < Onlyfansapi::Internal::Type::BaseModel
          attr_accessor end_: String

          attr_accessor start: String

          def initialize: (end_: String, start: String) -> void

          def to_hash: -> { end_: String, start: String }
        end

        type granularity = :months | :quarters | :half_years | :years

        module Granularity
          extend Onlyfansapi::Internal::Type::Enum

          MONTHS: :months
          QUARTERS: :quarters
          HALF_YEARS: :half_years
          YEARS: :years

          def self?.values: -> ::Array[Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::granularity]
        end

        type stat_type =
          :totalEarnings
          | :subscriptions
          | :posts
          | :messages
          | :tips
          | :streams

        module StatType
          extend Onlyfansapi::Internal::Type::Enum

          TOTAL_EARNINGS: :totalEarnings
          SUBSCRIPTIONS: :subscriptions
          POSTS: :posts
          MESSAGES: :messages
          TIPS: :tips
          STREAMS: :streams

          def self?.values: -> ::Array[Onlyfansapi::Models::Analytics::SummaryGetPeriodComparisonParams::stat_type]
        end
      end
    end
  end
end
