module Onlyfansapi
  module Models
    module Analytics
      type summary_get_earnings_overview_response =
        {
          messages: Float,
          posts: Float,
          streams: Float,
          subscriptions: Float,
          tips: Float,
          total_accounts: Integer,
          total_earnings: Float,
          total_images: Integer,
          total_messages: Integer,
          total_videos: Integer
        }

      class SummaryGetEarningsOverviewResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader messages: Float?

        def messages=: (Float) -> Float

        attr_reader posts: Float?

        def posts=: (Float) -> Float

        attr_reader streams: Float?

        def streams=: (Float) -> Float

        attr_reader subscriptions: Float?

        def subscriptions=: (Float) -> Float

        attr_reader tips: Float?

        def tips=: (Float) -> Float

        attr_reader total_accounts: Integer?

        def total_accounts=: (Integer) -> Integer

        attr_reader total_earnings: Float?

        def total_earnings=: (Float) -> Float

        attr_reader total_images: Integer?

        def total_images=: (Integer) -> Integer

        attr_reader total_messages: Integer?

        def total_messages=: (Integer) -> Integer

        attr_reader total_videos: Integer?

        def total_videos=: (Integer) -> Integer

        def initialize: (
          ?messages: Float,
          ?posts: Float,
          ?streams: Float,
          ?subscriptions: Float,
          ?tips: Float,
          ?total_accounts: Integer,
          ?total_earnings: Float,
          ?total_images: Integer,
          ?total_messages: Integer,
          ?total_videos: Integer
        ) -> void

        def to_hash: -> {
          messages: Float,
          posts: Float,
          streams: Float,
          subscriptions: Float,
          tips: Float,
          total_accounts: Integer,
          total_earnings: Float,
          total_images: Integer,
          total_messages: Integer,
          total_videos: Integer
        }
      end
    end
  end
end
