module Onlyfansapi
  module Resources
    class Accounts
      def list: (
        ?onlyfans_email: String?,
        ?onlyfans_id: String?,
        ?onlyfans_username: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::account_list_response

      def disconnect: (
        String id,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::account_disconnect_response?

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
