module Onlyfansapi
  module Resources
    class Banking
      attr_reader details: Onlyfansapi::Resources::Banking::Details

      def list_available_payout_systems: (
        String account,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::BankingListAvailablePayoutSystemsResponse

      def list_countries: (
        String account,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::BankingListCountriesResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
