module Onlyfansapi
  module Resources
    class ClientSessions
      def create: (
        display_name: String,
        ?client_reference_id: String,
        ?proxy_country: Onlyfansapi::Models::ClientSessionCreateParams::proxy_country?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::ClientSessionCreateResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
