module Onlyfansapi
  module Resources
    class Engagement
      attr_reader messages: Onlyfansapi::Resources::Engagement::Messages

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
