module Onlyfansapi
  module Resources
    class Fans
      attr_reader notes: Onlyfansapi::Resources::Fans::Notes

      attr_reader summary: Onlyfansapi::Resources::Fans::Summary

      def get_subscription_history: (
        String user_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanGetSubscriptionHistoryResponse

      def list_active: (
        String account,
        ?filter: Onlyfansapi::FanListActiveParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String?,
        ?type: Onlyfansapi::Models::FanListActiveParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanListActiveResponse

      def list_all: (
        String account,
        ?filter: Onlyfansapi::FanListAllParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String?,
        ?type: Onlyfansapi::Models::FanListAllParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanListAllResponse

      def list_expired: (
        String account,
        ?filter: Onlyfansapi::FanListExpiredParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String?,
        ?type: Onlyfansapi::Models::FanListExpiredParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanListExpiredResponse

      def list_latest: (
        String account,
        ?end_date: String?,
        ?limit: String?,
        ?offset: String?,
        ?start_date: String?,
        ?type: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanListLatestResponse

      def list_top: (
        String account,
        ?by: Onlyfansapi::Models::FanListTopParams::by?,
        ?end_date: String?,
        ?start_date: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanListTopResponse

      def set_custom_name: (
        String fan_id,
        account: String,
        custom_name: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::FanSetCustomNameResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
