module Onlyfansapi
  module Resources
    class Giphy
      def list_trending: (
        String account,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::GiphyListTrendingResponse

      def search: (
        String account,
        q: String,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::GiphySearchResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
