module Onlyfansapi
  module Resources
    class LinkTags
      def list: (
        ?type: Onlyfansapi::Models::LinkTagListParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::LinkTagListResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
