module Onlyfansapi
  module Resources
    class Media
      attr_reader uploads: Onlyfansapi::Resources::Media::Uploads

      attr_reader vault: Onlyfansapi::Resources::Media::Vault

      def download: (
        String cdn_url,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> String

      def scrape: (
        String account,
        ?expiration_date: String?,
        ?file_type: Onlyfansapi::Models::MediaScrapeParams::file_type?,
        ?media_id: Integer?,
        ?public: bool?,
        ?url: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::MediaScrapeResponse

      def upload: (
        String account,
        ?async: bool,
        ?file: Onlyfansapi::Internal::file_input,
        ?file_url: String,
        ?type: Onlyfansapi::Models::MediaUploadParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::MediaUploadResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
