module Onlyfansapi
  module Resources
    class Notifications
      attr_reader tabs_order: Onlyfansapi::Resources::Notifications::TabsOrder

      def list: (
        String account,
        ?from_id: Integer,
        ?limit: Integer,
        ?skip_users: Onlyfansapi::Models::NotificationListParams::skip_users,
        ?type: Onlyfansapi::Models::NotificationListParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::NotificationListResponse

      def get_counts: (
        String account,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::NotificationGetCountsResponse

      def mark_all_as_read: (
        String account,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::NotificationMarkAllAsReadResponse

      def search_users: (
        String account,
        query: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::NotificationSearchUsersResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
