module Onlyfansapi
  module Resources
    class Profiles
      def retrieve: (
        String username,
        ?fresh: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::ProfileRetrieveResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
