module Onlyfansapi
  module Resources
    class SharedTrialLinks
      attr_reader tags: Onlyfansapi::Resources::SharedTrialLinks::Tags

      def list: (
        String account,
        ?limit: Integer,
        ?offset: Integer,
        ?synchronous: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::SharedTrialLinkListResponse

      def revoke_access: (
        Integer shared_trial_link_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::SharedTrialLinkRevokeAccessResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
