module Onlyfansapi
  module Resources
    class Statistics
      attr_reader statements: Onlyfansapi::Resources::Statistics::Statements

      attr_reader reach: Onlyfansapi::Resources::Statistics::Reach

      def calculate_total_transactions: (
        String account,
        end_date: String,
        start_date: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StatisticCalculateTotalTransactionsResponse

      def get_overview: (
        String account,
        end_date: String,
        start_date: String,
        ?type: Onlyfansapi::Models::StatisticGetOverviewParams::type_?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StatisticGetOverviewResponse

      def get_subscriber_metrics: (
        String account,
        end_date: String,
        start_date: String,
        ?detailed: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StatisticGetSubscriberMetricsResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
