module Onlyfansapi
  module Resources
    class Stories
      attr_reader highlights: Onlyfansapi::Resources::Stories::Highlights

      def create: (
        String account,
        media_files: ::Array[String],
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryCreateResponse

      def retrieve: (
        Integer story_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryRetrieveResponse

      def delete: (
        Integer story_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryDeleteResponse

      def list_active: (
        String account,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryListActiveResponse

      def list_archive: (
        String account,
        ?limit: Integer,
        ?marker: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryListArchiveResponse

      def list_viewers: (
        Integer story_id,
        account: String,
        ?limit: Integer?,
        ?offset: Integer?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryListViewersResponse

      def mark_as_watched: (
        Integer story_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryMarkAsWatchedResponse

      def retrieve_stats: (
        Integer story_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::StoryRetrieveStatsResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
