module Onlyfansapi
  module Resources
    class Subscribers
      def retrieve_statistics: (
        String account,
        ?end_date: String?,
        ?start_date: String?,
        ?type: Onlyfansapi::Models::SubscriberRetrieveStatisticsParams::type_?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::SubscriberRetrieveStatisticsResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
