module Onlyfansapi
  module Resources
    class Transactions
      def list: (
        String account,
        ?limit: String,
        ?marker: String,
        ?start_date: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::TransactionListResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
