module Onlyfansapi
  module Resources
    class UserLists
      attr_reader users: Onlyfansapi::Resources::UserLists::Users

      def create: (
        String account,
        name: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::UserListCreateResponse

      def update: (
        String user_list_id,
        account: String,
        name: String,
        ?is_pinned_to_feed: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::UserListUpdateResponse

      def list: (
        String account,
        ?limit: Integer?,
        ?offset: Integer?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::UserListListResponse

      def delete: (
        String user_list_id,
        account: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::UserListDeleteResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
