module Onlyfansapi
  module Resources
    class Webhooks
      def create: (
        endpoint_url: String,
        events: ::Array[String],
        ?signing_secret: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookCreateResponse

      def delete: (
        String webhook_id,
        ?request_options: Onlyfansapi::request_opts
      ) -> top?

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
