module Onlyfansapi
  module Resources
    class Webhooks
      def create: (
        account_scope: String,
        endpoint_url: String,
        events: ::Array[String],
        ?account_ids: ::Array[String],
        ?signing_secret: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookCreateResponse

      def retrieve: (
        String webhook_id,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookRetrieveResponse

      def update: (
        String webhook_id,
        account_scope: String,
        endpoint_url: String,
        events: ::Array[String],
        ?account_ids: ::Array[String],
        ?enabled: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookUpdateResponse

      def list: (
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookListResponse

      def delete: (
        String webhook_id,
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::webhook_delete_response?

      def list_events: (
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WebhookListEventsResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
