module Onlyfansapi
  module Resources
    class Whoami
      def retrieve: (
        ?request_options: Onlyfansapi::request_opts
      ) -> Onlyfansapi::Models::WhoamiRetrieveResponse

      def initialize: (client: Onlyfansapi::Client) -> void
    end
  end
end
