module Onlyfansapi
  module Models
    module SharedTrackingLinks
      type tag_remove_params =
        {
          account: String,
          shared_tracking_link_id: Integer,
          tags: ::Array[String]
        }
        & Onlyfansapi::Internal::Type::request_parameters

      class TagRemoveParams < Onlyfansapi::Internal::Type::BaseModel
        extend Onlyfansapi::Internal::Type::RequestParameters::Converter
        include Onlyfansapi::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor shared_tracking_link_id: Integer

        attr_accessor tags: ::Array[String]

        def initialize: (
          account: String,
          shared_tracking_link_id: Integer,
          tags: ::Array[String],
          ?request_options: Onlyfansapi::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          shared_tracking_link_id: Integer,
          tags: ::Array[String],
          request_options: Onlyfansapi::RequestOptions
        }
      end
    end
  end
end
