module Onlyfansapi
  module Models
    module SharedTrackingLinks
      type tag_list_response =
        {
          _meta: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta,
          data: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data
        }

      class TagListResponse < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _meta: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta?

        def _meta=: (
          Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta
        ) -> Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta

        attr_reader data: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data?

        def data=: (
          Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data
        ) -> Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data

        def initialize: (
          ?_meta: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta,
          ?data: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data
        ) -> void

        def to_hash: -> {
          _meta: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta,
          data: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Data
        }

        type meta =
          {
            _cache: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits
          }

        class Meta < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _cache: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache?

          def _cache=: (
            Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache
          ) -> Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache

          attr_reader _credits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits?

          def _credits=: (
            Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits
          ) -> Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits

          attr_reader _rate_limits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits?

          def _rate_limits=: (
            Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits
          ) -> Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits

          def initialize: (
            ?_cache: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache,
            ?_credits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits,
            ?_rate_limits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits
          ) -> void

          def to_hash: -> {
            _cache: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Cache,
            _credits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::Credits,
            _rate_limits: Onlyfansapi::Models::SharedTrackingLinks::TagListResponse::Meta::RateLimits
          }

          type cache = { is_cached: bool, note: String }

          class Cache < Onlyfansapi::Internal::Type::BaseModel
            attr_reader is_cached: bool?

            def is_cached=: (bool) -> bool

            attr_reader note: String?

            def note=: (String) -> String

            def initialize: (?is_cached: bool, ?note: String) -> void

            def to_hash: -> { is_cached: bool, note: String }
          end

          type credits = { balance: Integer, note: String, used: Integer }

          class Credits < Onlyfansapi::Internal::Type::BaseModel
            attr_reader balance: Integer?

            def balance=: (Integer) -> Integer

            attr_reader note: String?

            def note=: (String) -> String

            attr_reader used: Integer?

            def used=: (Integer) -> Integer

            def initialize: (
              ?balance: Integer,
              ?note: String,
              ?used: Integer
            ) -> void

            def to_hash: -> { balance: Integer, note: String, used: Integer }
          end

          type rate_limits =
            {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }

          class RateLimits < Onlyfansapi::Internal::Type::BaseModel
            attr_accessor limit_day: String?

            attr_reader limit_minute: Integer?

            def limit_minute=: (Integer) -> Integer

            attr_reader notice: String?

            def notice=: (String) -> String

            attr_accessor remaining_day: String?

            attr_reader remaining_minute: Integer?

            def remaining_minute=: (Integer) -> Integer

            def initialize: (
              ?limit_day: String?,
              ?limit_minute: Integer,
              ?notice: String,
              ?remaining_day: String?,
              ?remaining_minute: Integer
            ) -> void

            def to_hash: -> {
              limit_day: String?,
              limit_minute: Integer,
              notice: String,
              remaining_day: String?,
              remaining_minute: Integer
            }
          end
        end

        type data = { tags: ::Array[String] }

        class Data < Onlyfansapi::Internal::Type::BaseModel
          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          def initialize: (?tags: ::Array[String]) -> void

          def to_hash: -> { tags: ::Array[String] }
        end
      end
    end
  end
end
