module Onlyfans
  module Models
    module Settings
      type blocked_country_update_params =
        {
          account: String,
          blocked_countries: ::Array[String],
          blocked_states: ::Array[String]
        }
        & Onlyfans::Internal::Type::request_parameters

      class BlockedCountryUpdateParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor blocked_countries: ::Array[String]

        attr_reader blocked_states: ::Array[String]?

        def blocked_states=: (::Array[String]) -> ::Array[String]

        def initialize: (
          account: String,
          blocked_countries: ::Array[String],
          ?blocked_states: ::Array[String],
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          blocked_countries: ::Array[String],
          blocked_states: ::Array[String],
          request_options: Onlyfans::RequestOptions
        }
      end
    end
  end
end
