module Onlyfansapi
  module Models
    type account_disconnect_params =
      { id: String } & Onlyfansapi::Internal::Type::request_parameters

    class AccountDisconnectParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
