module Onlyfansapi
  module Models
    type authenticate_submit2fa_params =
      { attempt_id: String, code: String, selfie_verification_completed: top }
      & Onlyfansapi::Internal::Type::request_parameters

    class AuthenticateSubmit2faParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor attempt_id: String

      attr_reader code: String?

      def code=: (String) -> String

      attr_reader selfie_verification_completed: top?

      def selfie_verification_completed=: (top) -> top

      def initialize: (
        attempt_id: String,
        ?code: String,
        ?selfie_verification_completed: top,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        attempt_id: String,
        code: String,
        selfie_verification_completed: top,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
