module Onlyfansapi
  module Models
    type authenticate_start_response =
      Onlyfansapi::Models::AuthenticateStartResponse::UnionMember0
      | Onlyfansapi::Models::AuthenticateStartResponse::UnionMember1

    module AuthenticateStartResponse
      extend Onlyfansapi::Internal::Type::Union

      type union_member0 =
        { attempt_id: String, message: String, polling_url: String }

      class UnionMember0 < Onlyfansapi::Internal::Type::BaseModel
        attr_reader attempt_id: String?

        def attempt_id=: (String) -> String

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader polling_url: String?

        def polling_url=: (String) -> String

        def initialize: (
          ?attempt_id: String,
          ?message: String,
          ?polling_url: String
        ) -> void

        def to_hash: -> {
          attempt_id: String,
          message: String,
          polling_url: String
        }
      end

      type union_member1 =
        {
          attempt_id: String,
          message: String,
          mobile_auth_session_deeplink: String,
          polling_url: String
        }

      class UnionMember1 < Onlyfansapi::Internal::Type::BaseModel
        attr_reader attempt_id: String?

        def attempt_id=: (String) -> String

        attr_reader message: String?

        def message=: (String) -> String

        attr_reader mobile_auth_session_deeplink: String?

        def mobile_auth_session_deeplink=: (String) -> String

        attr_reader polling_url: String?

        def polling_url=: (String) -> String

        def initialize: (
          ?attempt_id: String,
          ?message: String,
          ?mobile_auth_session_deeplink: String,
          ?polling_url: String
        ) -> void

        def to_hash: -> {
          attempt_id: String,
          message: String,
          mobile_auth_session_deeplink: String,
          polling_url: String
        }
      end

      def self?.variants: -> ::Array[Onlyfansapi::Models::authenticate_start_response]
    end
  end
end
