module Onlyfansapi
  module Models
    type authenticate_submit2fa_params =
      {
        attempt_id: String,
        code: String,
        selfie_verification_completed: Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class AuthenticateSubmit2faParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor attempt_id: String

      attr_reader code: String?

      def code=: (String) -> String

      attr_reader selfie_verification_completed: Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed?

      def selfie_verification_completed=: (
        Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed
      ) -> Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed

      def initialize: (
        attempt_id: String,
        ?code: String,
        ?selfie_verification_completed: Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        attempt_id: String,
        code: String,
        selfie_verification_completed: Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed,
        request_options: Onlyfansapi::RequestOptions
      }

      type selfie_verification_completed = nil

      module SelfieVerificationCompleted
        extend Onlyfansapi::Internal::Type::Enum

        def self?.values: -> ::Array[Onlyfansapi::Models::AuthenticateSubmit2faParams::selfie_verification_completed]
      end
    end
  end
end
