module Onlyfansapi
  module Models
    type authenticate_poll_status_response =
      {
        account: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account,
        last_attempt: Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt,
        progress: String,
        state: String
      }

    class AuthenticatePollStatusResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader account: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account?

      def account=: (
        Onlyfansapi::Models::AuthenticatePollStatusResponse::Account
      ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account

      attr_reader last_attempt: Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt?

      def last_attempt=: (
        Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt
      ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt

      attr_reader progress: String?

      def progress=: (String) -> String

      attr_reader state: String?

      def state=: (String) -> String

      def initialize: (
        ?account: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account,
        ?last_attempt: Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt,
        ?progress: String,
        ?state: String
      ) -> void

      def to_hash: -> {
        account: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account,
        last_attempt: Onlyfansapi::Models::AuthenticatePollStatusResponse::LastAttempt,
        progress: String,
        state: String
      }

      type account =
        {
          id: String,
          display_name: String,
          onlyfans_data: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData
        }

      class Account < Onlyfansapi::Internal::Type::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_reader onlyfans_data: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData?

        def onlyfans_data=: (
          Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData
        ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData

        def initialize: (
          ?id: String,
          ?display_name: String,
          ?onlyfans_data: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData
        ) -> void

        def to_hash: -> {
          id: String,
          display_name: String,
          onlyfans_data: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData
        }

        type onlyfans_data =
          {
            id: Integer,
            about: String?,
            adv_block: ::Array[String],
            age_verification_required: bool,
            age_verification_session: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession,
            archived_posts_count: Integer,
            audios_count: Integer,
            avatar: String?,
            avatar_header_converter_upload: bool,
            avatar_thumbs: String?,
            can_add_card: bool,
            can_alternative_wallet_top_up: bool,
            can_chat: bool,
            can_comment_story: bool,
            can_connect_of_account: bool,
            can_create_lists: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_pin_post: bool,
            can_receive_chat_message: bool,
            can_send_chat_to_all: bool,
            chat_messages_count: Integer,
            connected_of_accounts: ::Array[top],
            count_pinned_chat: Integer,
            count_priority_chat: Integer,
            credit_balance: Integer,
            credits_max: Integer,
            credits_min: Integer,
            csrf: String,
            email: String,
            enabled_image_editor_for_chat: bool,
            face_id_regular: ::Array[top],
            favorited_count: Integer,
            favorites_count: Integer,
            has_internal_payments: bool,
            has_labels: bool,
            has_new_alerts: bool,
            has_new_changed_price_subscriptions: bool,
            has_new_hints: bool,
            has_new_ticket_replies: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies,
            has_not_viewed_story: bool,
            has_pinned_posts: bool,
            has_purchased_posts: bool,
            has_scenario: bool,
            has_system_notifications: bool,
            has_tags: bool,
            has_watermark_photo: bool,
            has_watermark_video: bool,
            header: String?,
            header_size: String?,
            header_thumbs: String?,
            ip: String,
            is_age_verified: bool,
            is_allow_tweets: bool,
            is_auth: bool,
            is_credits_enabled: bool,
            is_delete_initiated: bool,
            is_email_checked: bool,
            is_email_required: bool,
            is_legal_approved_allowed: bool,
            is_make_payment: bool,
            is_markdown_disabled_for_about: bool,
            is_otp_enabled: bool,
            is_payment_card_connected: bool,
            is_paywall_passed: bool,
            is_performer: bool,
            is_real_card_connected: bool,
            is_real_performer: bool,
            is_referrer_allowed: bool,
            is_spotify_connected: bool,
            is_twitter_connected: bool,
            is_verified: bool,
            is_visible_online: bool,
            is_wallet_autorecharge: bool,
            is_want_comments: bool,
            iv_country: String?,
            iv_fail_reason: String,
            iv_flow: String,
            iv_status: String?,
            join_date: String,
            last_seen: String,
            location: String?,
            max_pinned_posts_count: Integer,
            medias_count: Integer,
            name: String,
            need_iv_approve: bool,
            new_tags_count: Integer,
            notifications_count: Integer,
            paid_feed: bool,
            payout_legal_approve_state: String,
            photos_count: Integer,
            pinned_posts_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            show_posts_in_feed: bool,
            subscribers_count: Integer,
            subscribes_count: Integer,
            twitter_username: String?,
            upload: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload,
            username: String,
            videos_count: Integer,
            view: String,
            wallet_autorecharge_amount: Integer,
            wallet_autorecharge_min: Integer,
            wallet_first_rebills: bool,
            watermark_position: String,
            watermark_text: String,
            website: String?,
            wishlist: String?,
            ws_auth_token: String,
            ws_url: String
          }

        class OnlyfansData < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_accessor about: String?

          attr_reader adv_block: ::Array[String]?

          def adv_block=: (::Array[String]) -> ::Array[String]

          attr_reader age_verification_required: bool?

          def age_verification_required=: (bool) -> bool

          attr_reader age_verification_session: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession?

          def age_verification_session=: (
            Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession
          ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession

          attr_reader archived_posts_count: Integer?

          def archived_posts_count=: (Integer) -> Integer

          attr_reader audios_count: Integer?

          def audios_count=: (Integer) -> Integer

          attr_accessor avatar: String?

          attr_reader avatar_header_converter_upload: bool?

          def avatar_header_converter_upload=: (bool) -> bool

          attr_accessor avatar_thumbs: String?

          attr_reader can_add_card: bool?

          def can_add_card=: (bool) -> bool

          attr_reader can_alternative_wallet_top_up: bool?

          def can_alternative_wallet_top_up=: (bool) -> bool

          attr_reader can_chat: bool?

          def can_chat=: (bool) -> bool

          attr_reader can_comment_story: bool?

          def can_comment_story=: (bool) -> bool

          attr_reader can_connect_of_account: bool?

          def can_connect_of_account=: (bool) -> bool

          attr_reader can_create_lists: bool?

          def can_create_lists=: (bool) -> bool

          attr_reader can_look_story: bool?

          def can_look_story=: (bool) -> bool

          attr_reader can_pay_internal: bool?

          def can_pay_internal=: (bool) -> bool

          attr_reader can_pin_post: bool?

          def can_pin_post=: (bool) -> bool

          attr_reader can_receive_chat_message: bool?

          def can_receive_chat_message=: (bool) -> bool

          attr_reader can_send_chat_to_all: bool?

          def can_send_chat_to_all=: (bool) -> bool

          attr_reader chat_messages_count: Integer?

          def chat_messages_count=: (Integer) -> Integer

          attr_reader connected_of_accounts: ::Array[top]?

          def connected_of_accounts=: (::Array[top]) -> ::Array[top]

          attr_reader count_pinned_chat: Integer?

          def count_pinned_chat=: (Integer) -> Integer

          attr_reader count_priority_chat: Integer?

          def count_priority_chat=: (Integer) -> Integer

          attr_reader credit_balance: Integer?

          def credit_balance=: (Integer) -> Integer

          attr_reader credits_max: Integer?

          def credits_max=: (Integer) -> Integer

          attr_reader credits_min: Integer?

          def credits_min=: (Integer) -> Integer

          attr_reader csrf: String?

          def csrf=: (String) -> String

          attr_reader email: String?

          def email=: (String) -> String

          attr_reader enabled_image_editor_for_chat: bool?

          def enabled_image_editor_for_chat=: (bool) -> bool

          attr_reader face_id_regular: ::Array[top]?

          def face_id_regular=: (::Array[top]) -> ::Array[top]

          attr_reader favorited_count: Integer?

          def favorited_count=: (Integer) -> Integer

          attr_reader favorites_count: Integer?

          def favorites_count=: (Integer) -> Integer

          attr_reader has_internal_payments: bool?

          def has_internal_payments=: (bool) -> bool

          attr_reader has_labels: bool?

          def has_labels=: (bool) -> bool

          attr_reader has_new_alerts: bool?

          def has_new_alerts=: (bool) -> bool

          attr_reader has_new_changed_price_subscriptions: bool?

          def has_new_changed_price_subscriptions=: (bool) -> bool

          attr_reader has_new_hints: bool?

          def has_new_hints=: (bool) -> bool

          attr_reader has_new_ticket_replies: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies?

          def has_new_ticket_replies=: (
            Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies
          ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies

          attr_reader has_not_viewed_story: bool?

          def has_not_viewed_story=: (bool) -> bool

          attr_reader has_pinned_posts: bool?

          def has_pinned_posts=: (bool) -> bool

          attr_reader has_purchased_posts: bool?

          def has_purchased_posts=: (bool) -> bool

          attr_reader has_scenario: bool?

          def has_scenario=: (bool) -> bool

          attr_reader has_system_notifications: bool?

          def has_system_notifications=: (bool) -> bool

          attr_reader has_tags: bool?

          def has_tags=: (bool) -> bool

          attr_reader has_watermark_photo: bool?

          def has_watermark_photo=: (bool) -> bool

          attr_reader has_watermark_video: bool?

          def has_watermark_video=: (bool) -> bool

          attr_accessor header: String?

          attr_accessor header_size: String?

          attr_accessor header_thumbs: String?

          attr_reader ip: String?

          def ip=: (String) -> String

          attr_reader is_age_verified: bool?

          def is_age_verified=: (bool) -> bool

          attr_reader is_allow_tweets: bool?

          def is_allow_tweets=: (bool) -> bool

          attr_reader is_auth: bool?

          def is_auth=: (bool) -> bool

          attr_reader is_credits_enabled: bool?

          def is_credits_enabled=: (bool) -> bool

          attr_reader is_delete_initiated: bool?

          def is_delete_initiated=: (bool) -> bool

          attr_reader is_email_checked: bool?

          def is_email_checked=: (bool) -> bool

          attr_reader is_email_required: bool?

          def is_email_required=: (bool) -> bool

          attr_reader is_legal_approved_allowed: bool?

          def is_legal_approved_allowed=: (bool) -> bool

          attr_reader is_make_payment: bool?

          def is_make_payment=: (bool) -> bool

          attr_reader is_markdown_disabled_for_about: bool?

          def is_markdown_disabled_for_about=: (bool) -> bool

          attr_reader is_otp_enabled: bool?

          def is_otp_enabled=: (bool) -> bool

          attr_reader is_payment_card_connected: bool?

          def is_payment_card_connected=: (bool) -> bool

          attr_reader is_paywall_passed: bool?

          def is_paywall_passed=: (bool) -> bool

          attr_reader is_performer: bool?

          def is_performer=: (bool) -> bool

          attr_reader is_real_card_connected: bool?

          def is_real_card_connected=: (bool) -> bool

          attr_reader is_real_performer: bool?

          def is_real_performer=: (bool) -> bool

          attr_reader is_referrer_allowed: bool?

          def is_referrer_allowed=: (bool) -> bool

          attr_reader is_spotify_connected: bool?

          def is_spotify_connected=: (bool) -> bool

          attr_reader is_twitter_connected: bool?

          def is_twitter_connected=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_reader is_visible_online: bool?

          def is_visible_online=: (bool) -> bool

          attr_reader is_wallet_autorecharge: bool?

          def is_wallet_autorecharge=: (bool) -> bool

          attr_reader is_want_comments: bool?

          def is_want_comments=: (bool) -> bool

          attr_accessor iv_country: String?

          attr_reader iv_fail_reason: String?

          def iv_fail_reason=: (String) -> String

          attr_reader iv_flow: String?

          def iv_flow=: (String) -> String

          attr_accessor iv_status: String?

          attr_reader join_date: String?

          def join_date=: (String) -> String

          attr_reader last_seen: String?

          def last_seen=: (String) -> String

          attr_accessor location: String?

          attr_reader max_pinned_posts_count: Integer?

          def max_pinned_posts_count=: (Integer) -> Integer

          attr_reader medias_count: Integer?

          def medias_count=: (Integer) -> Integer

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader need_iv_approve: bool?

          def need_iv_approve=: (bool) -> bool

          attr_reader new_tags_count: Integer?

          def new_tags_count=: (Integer) -> Integer

          attr_reader notifications_count: Integer?

          def notifications_count=: (Integer) -> Integer

          attr_reader paid_feed: bool?

          def paid_feed=: (bool) -> bool

          attr_reader payout_legal_approve_state: String?

          def payout_legal_approve_state=: (String) -> String

          attr_reader photos_count: Integer?

          def photos_count=: (Integer) -> Integer

          attr_reader pinned_posts_count: Integer?

          def pinned_posts_count=: (Integer) -> Integer

          attr_reader posts_count: Integer?

          def posts_count=: (Integer) -> Integer

          attr_reader private_archived_posts_count: Integer?

          def private_archived_posts_count=: (Integer) -> Integer

          attr_reader show_posts_in_feed: bool?

          def show_posts_in_feed=: (bool) -> bool

          attr_reader subscribers_count: Integer?

          def subscribers_count=: (Integer) -> Integer

          attr_reader subscribes_count: Integer?

          def subscribes_count=: (Integer) -> Integer

          attr_accessor twitter_username: String?

          attr_reader upload: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload?

          def upload=: (
            Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload
          ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader videos_count: Integer?

          def videos_count=: (Integer) -> Integer

          attr_reader view: String?

          def view=: (String) -> String

          attr_reader wallet_autorecharge_amount: Integer?

          def wallet_autorecharge_amount=: (Integer) -> Integer

          attr_reader wallet_autorecharge_min: Integer?

          def wallet_autorecharge_min=: (Integer) -> Integer

          attr_reader wallet_first_rebills: bool?

          def wallet_first_rebills=: (bool) -> bool

          attr_reader watermark_position: String?

          def watermark_position=: (String) -> String

          attr_reader watermark_text: String?

          def watermark_text=: (String) -> String

          attr_accessor website: String?

          attr_accessor wishlist: String?

          attr_reader ws_auth_token: String?

          def ws_auth_token=: (String) -> String

          attr_reader ws_url: String?

          def ws_url=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?about: String?,
            ?adv_block: ::Array[String],
            ?age_verification_required: bool,
            ?age_verification_session: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession,
            ?archived_posts_count: Integer,
            ?audios_count: Integer,
            ?avatar: String?,
            ?avatar_header_converter_upload: bool,
            ?avatar_thumbs: String?,
            ?can_add_card: bool,
            ?can_alternative_wallet_top_up: bool,
            ?can_chat: bool,
            ?can_comment_story: bool,
            ?can_connect_of_account: bool,
            ?can_create_lists: bool,
            ?can_look_story: bool,
            ?can_pay_internal: bool,
            ?can_pin_post: bool,
            ?can_receive_chat_message: bool,
            ?can_send_chat_to_all: bool,
            ?chat_messages_count: Integer,
            ?connected_of_accounts: ::Array[top],
            ?count_pinned_chat: Integer,
            ?count_priority_chat: Integer,
            ?credit_balance: Integer,
            ?credits_max: Integer,
            ?credits_min: Integer,
            ?csrf: String,
            ?email: String,
            ?enabled_image_editor_for_chat: bool,
            ?face_id_regular: ::Array[top],
            ?favorited_count: Integer,
            ?favorites_count: Integer,
            ?has_internal_payments: bool,
            ?has_labels: bool,
            ?has_new_alerts: bool,
            ?has_new_changed_price_subscriptions: bool,
            ?has_new_hints: bool,
            ?has_new_ticket_replies: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies,
            ?has_not_viewed_story: bool,
            ?has_pinned_posts: bool,
            ?has_purchased_posts: bool,
            ?has_scenario: bool,
            ?has_system_notifications: bool,
            ?has_tags: bool,
            ?has_watermark_photo: bool,
            ?has_watermark_video: bool,
            ?header: String?,
            ?header_size: String?,
            ?header_thumbs: String?,
            ?ip: String,
            ?is_age_verified: bool,
            ?is_allow_tweets: bool,
            ?is_auth: bool,
            ?is_credits_enabled: bool,
            ?is_delete_initiated: bool,
            ?is_email_checked: bool,
            ?is_email_required: bool,
            ?is_legal_approved_allowed: bool,
            ?is_make_payment: bool,
            ?is_markdown_disabled_for_about: bool,
            ?is_otp_enabled: bool,
            ?is_payment_card_connected: bool,
            ?is_paywall_passed: bool,
            ?is_performer: bool,
            ?is_real_card_connected: bool,
            ?is_real_performer: bool,
            ?is_referrer_allowed: bool,
            ?is_spotify_connected: bool,
            ?is_twitter_connected: bool,
            ?is_verified: bool,
            ?is_visible_online: bool,
            ?is_wallet_autorecharge: bool,
            ?is_want_comments: bool,
            ?iv_country: String?,
            ?iv_fail_reason: String,
            ?iv_flow: String,
            ?iv_status: String?,
            ?join_date: String,
            ?last_seen: String,
            ?location: String?,
            ?max_pinned_posts_count: Integer,
            ?medias_count: Integer,
            ?name: String,
            ?need_iv_approve: bool,
            ?new_tags_count: Integer,
            ?notifications_count: Integer,
            ?paid_feed: bool,
            ?payout_legal_approve_state: String,
            ?photos_count: Integer,
            ?pinned_posts_count: Integer,
            ?posts_count: Integer,
            ?private_archived_posts_count: Integer,
            ?show_posts_in_feed: bool,
            ?subscribers_count: Integer,
            ?subscribes_count: Integer,
            ?twitter_username: String?,
            ?upload: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload,
            ?username: String,
            ?videos_count: Integer,
            ?view: String,
            ?wallet_autorecharge_amount: Integer,
            ?wallet_autorecharge_min: Integer,
            ?wallet_first_rebills: bool,
            ?watermark_position: String,
            ?watermark_text: String,
            ?website: String?,
            ?wishlist: String?,
            ?ws_auth_token: String,
            ?ws_url: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            about: String?,
            adv_block: ::Array[String],
            age_verification_required: bool,
            age_verification_session: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::AgeVerificationSession,
            archived_posts_count: Integer,
            audios_count: Integer,
            avatar: String?,
            avatar_header_converter_upload: bool,
            avatar_thumbs: String?,
            can_add_card: bool,
            can_alternative_wallet_top_up: bool,
            can_chat: bool,
            can_comment_story: bool,
            can_connect_of_account: bool,
            can_create_lists: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_pin_post: bool,
            can_receive_chat_message: bool,
            can_send_chat_to_all: bool,
            chat_messages_count: Integer,
            connected_of_accounts: ::Array[top],
            count_pinned_chat: Integer,
            count_priority_chat: Integer,
            credit_balance: Integer,
            credits_max: Integer,
            credits_min: Integer,
            csrf: String,
            email: String,
            enabled_image_editor_for_chat: bool,
            face_id_regular: ::Array[top],
            favorited_count: Integer,
            favorites_count: Integer,
            has_internal_payments: bool,
            has_labels: bool,
            has_new_alerts: bool,
            has_new_changed_price_subscriptions: bool,
            has_new_hints: bool,
            has_new_ticket_replies: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::HasNewTicketReplies,
            has_not_viewed_story: bool,
            has_pinned_posts: bool,
            has_purchased_posts: bool,
            has_scenario: bool,
            has_system_notifications: bool,
            has_tags: bool,
            has_watermark_photo: bool,
            has_watermark_video: bool,
            header: String?,
            header_size: String?,
            header_thumbs: String?,
            ip: String,
            is_age_verified: bool,
            is_allow_tweets: bool,
            is_auth: bool,
            is_credits_enabled: bool,
            is_delete_initiated: bool,
            is_email_checked: bool,
            is_email_required: bool,
            is_legal_approved_allowed: bool,
            is_make_payment: bool,
            is_markdown_disabled_for_about: bool,
            is_otp_enabled: bool,
            is_payment_card_connected: bool,
            is_paywall_passed: bool,
            is_performer: bool,
            is_real_card_connected: bool,
            is_real_performer: bool,
            is_referrer_allowed: bool,
            is_spotify_connected: bool,
            is_twitter_connected: bool,
            is_verified: bool,
            is_visible_online: bool,
            is_wallet_autorecharge: bool,
            is_want_comments: bool,
            iv_country: String?,
            iv_fail_reason: String,
            iv_flow: String,
            iv_status: String?,
            join_date: String,
            last_seen: String,
            location: String?,
            max_pinned_posts_count: Integer,
            medias_count: Integer,
            name: String,
            need_iv_approve: bool,
            new_tags_count: Integer,
            notifications_count: Integer,
            paid_feed: bool,
            payout_legal_approve_state: String,
            photos_count: Integer,
            pinned_posts_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            show_posts_in_feed: bool,
            subscribers_count: Integer,
            subscribes_count: Integer,
            twitter_username: String?,
            upload: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload,
            username: String,
            videos_count: Integer,
            view: String,
            wallet_autorecharge_amount: Integer,
            wallet_autorecharge_min: Integer,
            wallet_first_rebills: bool,
            watermark_position: String,
            watermark_text: String,
            website: String?,
            wishlist: String?,
            ws_auth_token: String,
            ws_url: String
          }

          type age_verification_session =
            {
              api_flow: String,
              expired_at: String,
              status: String,
              url: String
            }

          class AgeVerificationSession < Onlyfansapi::Internal::Type::BaseModel
            attr_reader api_flow: String?

            def api_flow=: (String) -> String

            attr_reader expired_at: String?

            def expired_at=: (String) -> String

            attr_reader status: String?

            def status=: (String) -> String

            attr_reader url: String?

            def url=: (String) -> String

            def initialize: (
              ?api_flow: String,
              ?expired_at: String,
              ?status: String,
              ?url: String
            ) -> void

            def to_hash: -> {
              api_flow: String,
              expired_at: String,
              status: String,
              url: String
            }
          end

          type has_new_ticket_replies =
            { closed: bool, open_: bool, solved: bool }

          class HasNewTicketReplies < Onlyfansapi::Internal::Type::BaseModel
            attr_reader closed: bool?

            def closed=: (bool) -> bool

            attr_reader open_: bool?

            def open_=: (bool) -> bool

            attr_reader solved: bool?

            def solved=: (bool) -> bool

            def initialize: (?closed: bool, ?open_: bool, ?solved: bool) -> void

            def to_hash: -> { closed: bool, open_: bool, solved: bool }
          end

          type upload =
            {
              geo_upload_args: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs
            }

          class Upload < Onlyfansapi::Internal::Type::BaseModel
            attr_reader geo_upload_args: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs?

            def geo_upload_args=: (
              Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs
            ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs

            def initialize: (
              ?geo_upload_args: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs
            ) -> void

            def to_hash: -> {
              geo_upload_args: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs
            }

            type geo_upload_args =
              {
                additional: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional,
                is_delay: bool,
                need_thumbs: bool,
                preset: String,
                preset_png: String,
                protected_preset: String
              }

            class GeoUploadArgs < Onlyfansapi::Internal::Type::BaseModel
              attr_reader additional: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional?

              def additional=: (
                Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional
              ) -> Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional

              attr_reader is_delay: bool?

              def is_delay=: (bool) -> bool

              attr_reader need_thumbs: bool?

              def need_thumbs=: (bool) -> bool

              attr_reader preset: String?

              def preset=: (String) -> String

              attr_reader preset_png: String?

              def preset_png=: (String) -> String

              attr_reader protected_preset: String?

              def protected_preset=: (String) -> String

              def initialize: (
                ?additional: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional,
                ?is_delay: bool,
                ?need_thumbs: bool,
                ?preset: String,
                ?preset_png: String,
                ?protected_preset: String
              ) -> void

              def to_hash: -> {
                additional: Onlyfansapi::Models::AuthenticatePollStatusResponse::Account::OnlyfansData::Upload::GeoUploadArgs::Additional,
                is_delay: bool,
                need_thumbs: bool,
                preset: String,
                preset_png: String,
                protected_preset: String
              }

              type additional = { user: String }

              class Additional < Onlyfansapi::Internal::Type::BaseModel
                attr_reader user: String?

                def user=: (String) -> String

                def initialize: (?user: String) -> void

                def to_hash: -> { user: String }
              end
            end
          end
        end
      end

      type last_attempt =
        {
          completed_at: String,
          error_code: String?,
          error_message: String?,
          needs_otp: bool,
          otp_phone_ending: String?,
          started_at: String,
          success: bool
        }

      class LastAttempt < Onlyfansapi::Internal::Type::BaseModel
        attr_reader completed_at: String?

        def completed_at=: (String) -> String

        attr_accessor error_code: String?

        attr_accessor error_message: String?

        attr_reader needs_otp: bool?

        def needs_otp=: (bool) -> bool

        attr_accessor otp_phone_ending: String?

        attr_reader started_at: String?

        def started_at=: (String) -> String

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (
          ?completed_at: String,
          ?error_code: String?,
          ?error_message: String?,
          ?needs_otp: bool,
          ?otp_phone_ending: String?,
          ?started_at: String,
          ?success: bool
        ) -> void

        def to_hash: -> {
          completed_at: String,
          error_code: String?,
          error_message: String?,
          needs_otp: bool,
          otp_phone_ending: String?,
          started_at: String,
          success: bool
        }
      end
    end
  end
end
