module Onlyfansapi
  module Models
    type authenticate_start_params =
      {
        email: String,
        password: String,
        proxy_country: Onlyfansapi::Models::AuthenticateStartParams::proxy_country
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class AuthenticateStartParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor email: String

      attr_accessor password: String

      attr_accessor proxy_country: Onlyfansapi::Models::AuthenticateStartParams::proxy_country

      def initialize: (
        email: String,
        password: String,
        proxy_country: Onlyfansapi::Models::AuthenticateStartParams::proxy_country,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        email: String,
        password: String,
        proxy_country: Onlyfansapi::Models::AuthenticateStartParams::proxy_country,
        request_options: Onlyfansapi::RequestOptions
      }

      type proxy_country =
        :us | :uk | :de | :es | :fr | :it | :ua | :pl | :ro | :cz | :hu | :sk

      module ProxyCountry
        extend Onlyfansapi::Internal::Type::Enum

        US: :us
        UK: :uk
        DE: :de
        ES: :es
        FR: :fr
        IT: :it
        UA: :ua
        PL: :pl
        RO: :ro
        CZ: :cz
        HU: :hu
        SK: :sk

        def self?.values: -> ::Array[Onlyfansapi::Models::AuthenticateStartParams::proxy_country]
      end
    end
  end
end
