module Onlyfansapi
  module Models
    type chat_list_params =
      {
        account: String,
        filter: Onlyfansapi::Models::ChatListParams::filter,
        limit: String,
        offset: String,
        order: Onlyfansapi::Models::ChatListParams::order,
        query: String,
        skip_users: Onlyfansapi::Models::ChatListParams::skip_users
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class ChatListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader filter: Onlyfansapi::Models::ChatListParams::filter?

      def filter=: (
        Onlyfansapi::Models::ChatListParams::filter
      ) -> Onlyfansapi::Models::ChatListParams::filter

      attr_reader limit: String?

      def limit=: (String) -> String

      attr_reader offset: String?

      def offset=: (String) -> String

      attr_reader order: Onlyfansapi::Models::ChatListParams::order?

      def order=: (
        Onlyfansapi::Models::ChatListParams::order
      ) -> Onlyfansapi::Models::ChatListParams::order

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader skip_users: Onlyfansapi::Models::ChatListParams::skip_users?

      def skip_users=: (
        Onlyfansapi::Models::ChatListParams::skip_users
      ) -> Onlyfansapi::Models::ChatListParams::skip_users

      def initialize: (
        account: String,
        ?filter: Onlyfansapi::Models::ChatListParams::filter,
        ?limit: String,
        ?offset: String,
        ?order: Onlyfansapi::Models::ChatListParams::order,
        ?query: String,
        ?skip_users: Onlyfansapi::Models::ChatListParams::skip_users,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfansapi::Models::ChatListParams::filter,
        limit: String,
        offset: String,
        order: Onlyfansapi::Models::ChatListParams::order,
        query: String,
        skip_users: Onlyfansapi::Models::ChatListParams::skip_users,
        request_options: Onlyfansapi::RequestOptions
      }

      type filter =
        :pinned | :priority | :unread | :with_tips | :unread_with_tips

      module Filter
        extend Onlyfansapi::Internal::Type::Enum

        PINNED: :pinned
        PRIORITY: :priority
        UNREAD: :unread
        WITH_TIPS: :with_tips
        UNREAD_WITH_TIPS: :unread_with_tips

        def self?.values: -> ::Array[Onlyfansapi::Models::ChatListParams::filter]
      end

      type order = :recent | :old

      module Order
        extend Onlyfansapi::Internal::Type::Enum

        RECENT: :recent
        OLD: :old

        def self?.values: -> ::Array[Onlyfansapi::Models::ChatListParams::order]
      end

      type skip_users = :all | :none

      module SkipUsers
        extend Onlyfansapi::Internal::Type::Enum

        ALL: :all
        NONE: :none

        def self?.values: -> ::Array[Onlyfansapi::Models::ChatListParams::skip_users]
      end
    end
  end
end
