module Onlyfansapi
  module Models
    type chat_list_response =
      {
        _meta: Onlyfansapi::Models::ChatListResponse::Meta,
        _pagination: Onlyfansapi::Models::ChatListResponse::Pagination,
        data: ::Array[Onlyfansapi::Models::ChatListResponse::Data]
      }

    class ChatListResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::ChatListResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::ChatListResponse::Meta
      ) -> Onlyfansapi::Models::ChatListResponse::Meta

      attr_reader _pagination: Onlyfansapi::Models::ChatListResponse::Pagination?

      def _pagination=: (
        Onlyfansapi::Models::ChatListResponse::Pagination
      ) -> Onlyfansapi::Models::ChatListResponse::Pagination

      attr_reader data: ::Array[Onlyfansapi::Models::ChatListResponse::Data]?

      def data=: (
        ::Array[Onlyfansapi::Models::ChatListResponse::Data]
      ) -> ::Array[Onlyfansapi::Models::ChatListResponse::Data]

      def initialize: (
        ?_meta: Onlyfansapi::Models::ChatListResponse::Meta,
        ?_pagination: Onlyfansapi::Models::ChatListResponse::Pagination,
        ?data: ::Array[Onlyfansapi::Models::ChatListResponse::Data]
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::ChatListResponse::Meta,
        _pagination: Onlyfansapi::Models::ChatListResponse::Pagination,
        data: ::Array[Onlyfansapi::Models::ChatListResponse::Data]
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::ChatListResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::ChatListResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::ChatListResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::ChatListResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::ChatListResponse::Meta::Cache
        ) -> Onlyfansapi::Models::ChatListResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::ChatListResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::ChatListResponse::Meta::Credits
        ) -> Onlyfansapi::Models::ChatListResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::ChatListResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::ChatListResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::ChatListResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::ChatListResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::ChatListResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::ChatListResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::ChatListResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::ChatListResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::ChatListResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type pagination = { next_page: String }

      class Pagination < Onlyfansapi::Internal::Type::BaseModel
        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (?next_page: String) -> void

        def to_hash: -> { next_page: String }
      end

      type data =
        {
          can_go_to_profile: bool,
          can_not_send_reason: bool,
          can_send_message: bool,
          count_pinned_messages: Integer,
          fan: Onlyfansapi::Models::ChatListResponse::Data::Fan,
          has_purchased_feed: bool,
          has_unread_tips: bool,
          is_muted_notifications: bool,
          last_message: Onlyfansapi::Models::ChatListResponse::Data::LastMessage,
          last_read_message_id: Integer,
          unread_messages_count: Integer
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader can_go_to_profile: bool?

        def can_go_to_profile=: (bool) -> bool

        attr_reader can_not_send_reason: bool?

        def can_not_send_reason=: (bool) -> bool

        attr_reader can_send_message: bool?

        def can_send_message=: (bool) -> bool

        attr_reader count_pinned_messages: Integer?

        def count_pinned_messages=: (Integer) -> Integer

        attr_reader fan: Onlyfansapi::Models::ChatListResponse::Data::Fan?

        def fan=: (
          Onlyfansapi::Models::ChatListResponse::Data::Fan
        ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan

        attr_reader has_purchased_feed: bool?

        def has_purchased_feed=: (bool) -> bool

        attr_reader has_unread_tips: bool?

        def has_unread_tips=: (bool) -> bool

        attr_reader is_muted_notifications: bool?

        def is_muted_notifications=: (bool) -> bool

        attr_reader last_message: Onlyfansapi::Models::ChatListResponse::Data::LastMessage?

        def last_message=: (
          Onlyfansapi::Models::ChatListResponse::Data::LastMessage
        ) -> Onlyfansapi::Models::ChatListResponse::Data::LastMessage

        attr_reader last_read_message_id: Integer?

        def last_read_message_id=: (Integer) -> Integer

        attr_reader unread_messages_count: Integer?

        def unread_messages_count=: (Integer) -> Integer

        def initialize: (
          ?can_go_to_profile: bool,
          ?can_not_send_reason: bool,
          ?can_send_message: bool,
          ?count_pinned_messages: Integer,
          ?fan: Onlyfansapi::Models::ChatListResponse::Data::Fan,
          ?has_purchased_feed: bool,
          ?has_unread_tips: bool,
          ?is_muted_notifications: bool,
          ?last_message: Onlyfansapi::Models::ChatListResponse::Data::LastMessage,
          ?last_read_message_id: Integer,
          ?unread_messages_count: Integer
        ) -> void

        def to_hash: -> {
          can_go_to_profile: bool,
          can_not_send_reason: bool,
          can_send_message: bool,
          count_pinned_messages: Integer,
          fan: Onlyfansapi::Models::ChatListResponse::Data::Fan,
          has_purchased_feed: bool,
          has_unread_tips: bool,
          is_muted_notifications: bool,
          last_message: Onlyfansapi::Models::ChatListResponse::Data::LastMessage,
          last_read_message_id: Integer,
          unread_messages_count: Integer
        }

        type fan =
          {
            id: Integer,
            about: String,
            archived_posts_count: Integer,
            audios_count: Integer,
            avatar: String,
            avatar_header_converter_upload: bool,
            avatar_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs,
            can_add_subscriber: bool,
            can_chat: bool,
            can_comment_story: bool,
            can_create_promotion: bool,
            can_create_trial: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_receive_chat_message: bool,
            can_report: bool,
            can_restrict: bool,
            can_trial_send: bool,
            can_unsubscribe: bool,
            current_subscribe_price: Integer,
            display_name: String,
            favorited_count: Integer,
            favorites_count: Integer,
            finished_streams_count: Integer,
            first_published_post_date: String,
            has_friends: bool,
            has_labels: bool,
            has_links: bool,
            has_not_viewed_story: bool,
            has_pinned_posts: bool,
            has_saved_streams: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            header: String,
            header_size: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize,
            header_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs,
            is_adult_content: bool,
            is_blocked: bool,
            is_friend: bool,
            is_markdown_disabled_for_about: bool,
            is_paywall_required: bool,
            is_pending_autoprolong: bool,
            is_performer: bool,
            is_private_restriction: bool,
            is_real_performer: bool,
            is_referrer_allowed: bool,
            is_restricted: bool,
            is_spotify_connected: bool,
            is_spring_connected: bool,
            is_verified: bool,
            join_date: String,
            last_seen: String,
            lists_states: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState],
            location: String,
            medias_count: Integer,
            name: String,
            notice: String,
            photos_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            should_show_finished_streams: bool,
            show_media_count: bool,
            show_posts_in_feed: bool,
            show_subscribers_count: bool,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData,
            subscribed_on_duration: String,
            subscribed_on_expired_now: bool,
            subscribe_price: Integer,
            subscribers_count: String?,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            videos_count: Integer,
            view: String,
            website: String?,
            wishlist: String?
          }

        class Fan < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader about: String?

          def about=: (String) -> String

          attr_reader archived_posts_count: Integer?

          def archived_posts_count=: (Integer) -> Integer

          attr_reader audios_count: Integer?

          def audios_count=: (Integer) -> Integer

          attr_reader avatar: String?

          def avatar=: (String) -> String

          attr_reader avatar_header_converter_upload: bool?

          def avatar_header_converter_upload=: (bool) -> bool

          attr_reader avatar_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs?

          def avatar_thumbs=: (
            Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs
          ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs

          attr_reader can_add_subscriber: bool?

          def can_add_subscriber=: (bool) -> bool

          attr_reader can_chat: bool?

          def can_chat=: (bool) -> bool

          attr_reader can_comment_story: bool?

          def can_comment_story=: (bool) -> bool

          attr_reader can_create_promotion: bool?

          def can_create_promotion=: (bool) -> bool

          attr_reader can_create_trial: bool?

          def can_create_trial=: (bool) -> bool

          attr_reader can_earn: bool?

          def can_earn=: (bool) -> bool

          attr_reader can_look_story: bool?

          def can_look_story=: (bool) -> bool

          attr_reader can_pay_internal: bool?

          def can_pay_internal=: (bool) -> bool

          attr_reader can_receive_chat_message: bool?

          def can_receive_chat_message=: (bool) -> bool

          attr_reader can_report: bool?

          def can_report=: (bool) -> bool

          attr_reader can_restrict: bool?

          def can_restrict=: (bool) -> bool

          attr_reader can_trial_send: bool?

          def can_trial_send=: (bool) -> bool

          attr_reader can_unsubscribe: bool?

          def can_unsubscribe=: (bool) -> bool

          attr_reader current_subscribe_price: Integer?

          def current_subscribe_price=: (Integer) -> Integer

          attr_reader display_name: String?

          def display_name=: (String) -> String

          attr_reader favorited_count: Integer?

          def favorited_count=: (Integer) -> Integer

          attr_reader favorites_count: Integer?

          def favorites_count=: (Integer) -> Integer

          attr_reader finished_streams_count: Integer?

          def finished_streams_count=: (Integer) -> Integer

          attr_reader first_published_post_date: String?

          def first_published_post_date=: (String) -> String

          attr_reader has_friends: bool?

          def has_friends=: (bool) -> bool

          attr_reader has_labels: bool?

          def has_labels=: (bool) -> bool

          attr_reader has_links: bool?

          def has_links=: (bool) -> bool

          attr_reader has_not_viewed_story: bool?

          def has_not_viewed_story=: (bool) -> bool

          attr_reader has_pinned_posts: bool?

          def has_pinned_posts=: (bool) -> bool

          attr_reader has_saved_streams: bool?

          def has_saved_streams=: (bool) -> bool

          attr_reader has_scheduled_stream: bool?

          def has_scheduled_stream=: (bool) -> bool

          attr_reader has_stories: bool?

          def has_stories=: (bool) -> bool

          attr_reader has_stream: bool?

          def has_stream=: (bool) -> bool

          attr_reader header: String?

          def header=: (String) -> String

          attr_reader header_size: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize?

          def header_size=: (
            Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize
          ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize

          attr_reader header_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs?

          def header_thumbs=: (
            Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs
          ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs

          attr_reader is_adult_content: bool?

          def is_adult_content=: (bool) -> bool

          attr_reader is_blocked: bool?

          def is_blocked=: (bool) -> bool

          attr_reader is_friend: bool?

          def is_friend=: (bool) -> bool

          attr_reader is_markdown_disabled_for_about: bool?

          def is_markdown_disabled_for_about=: (bool) -> bool

          attr_reader is_paywall_required: bool?

          def is_paywall_required=: (bool) -> bool

          attr_reader is_pending_autoprolong: bool?

          def is_pending_autoprolong=: (bool) -> bool

          attr_reader is_performer: bool?

          def is_performer=: (bool) -> bool

          attr_reader is_private_restriction: bool?

          def is_private_restriction=: (bool) -> bool

          attr_reader is_real_performer: bool?

          def is_real_performer=: (bool) -> bool

          attr_reader is_referrer_allowed: bool?

          def is_referrer_allowed=: (bool) -> bool

          attr_reader is_restricted: bool?

          def is_restricted=: (bool) -> bool

          attr_reader is_spotify_connected: bool?

          def is_spotify_connected=: (bool) -> bool

          attr_reader is_spring_connected: bool?

          def is_spring_connected=: (bool) -> bool

          attr_reader is_verified: bool?

          def is_verified=: (bool) -> bool

          attr_reader join_date: String?

          def join_date=: (String) -> String

          attr_reader last_seen: String?

          def last_seen=: (String) -> String

          attr_reader lists_states: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState]?

          def lists_states=: (
            ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState]
          ) -> ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState]

          attr_reader location: String?

          def location=: (String) -> String

          attr_reader medias_count: Integer?

          def medias_count=: (Integer) -> Integer

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader notice: String?

          def notice=: (String) -> String

          attr_reader photos_count: Integer?

          def photos_count=: (Integer) -> Integer

          attr_reader posts_count: Integer?

          def posts_count=: (Integer) -> Integer

          attr_reader private_archived_posts_count: Integer?

          def private_archived_posts_count=: (Integer) -> Integer

          attr_reader should_show_finished_streams: bool?

          def should_show_finished_streams=: (bool) -> bool

          attr_reader show_media_count: bool?

          def show_media_count=: (bool) -> bool

          attr_reader show_posts_in_feed: bool?

          def show_posts_in_feed=: (bool) -> bool

          attr_reader show_subscribers_count: bool?

          def show_subscribers_count=: (bool) -> bool

          attr_reader subscribed_by: bool?

          def subscribed_by=: (bool) -> bool

          attr_reader subscribed_by_autoprolong: bool?

          def subscribed_by_autoprolong=: (bool) -> bool

          attr_reader subscribed_by_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData?

          def subscribed_by_data=: (
            Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData
          ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData

          attr_reader subscribed_by_expire: bool?

          def subscribed_by_expire=: (bool) -> bool

          attr_reader subscribed_by_expire_date: String?

          def subscribed_by_expire_date=: (String) -> String

          attr_reader subscribed_is_expired_now: bool?

          def subscribed_is_expired_now=: (bool) -> bool

          attr_reader subscribed_on: bool?

          def subscribed_on=: (bool) -> bool

          attr_reader subscribed_on_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData?

          def subscribed_on_data=: (
            Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData
          ) -> Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData

          attr_reader subscribed_on_duration: String?

          def subscribed_on_duration=: (String) -> String

          attr_reader subscribed_on_expired_now: bool?

          def subscribed_on_expired_now=: (bool) -> bool

          attr_reader subscribe_price: Integer?

          def subscribe_price=: (Integer) -> Integer

          attr_accessor subscribers_count: String?

          attr_reader tips_enabled: bool?

          def tips_enabled=: (bool) -> bool

          attr_reader tips_max: Integer?

          def tips_max=: (Integer) -> Integer

          attr_reader tips_min: Integer?

          def tips_min=: (Integer) -> Integer

          attr_reader tips_min_internal: Integer?

          def tips_min_internal=: (Integer) -> Integer

          attr_reader tips_text_enabled: bool?

          def tips_text_enabled=: (bool) -> bool

          attr_reader username: String?

          def username=: (String) -> String

          attr_reader videos_count: Integer?

          def videos_count=: (Integer) -> Integer

          attr_reader view: String?

          def view=: (String) -> String

          attr_accessor website: String?

          attr_accessor wishlist: String?

          def initialize: (
            ?id: Integer,
            ?about: String,
            ?archived_posts_count: Integer,
            ?audios_count: Integer,
            ?avatar: String,
            ?avatar_header_converter_upload: bool,
            ?avatar_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs,
            ?can_add_subscriber: bool,
            ?can_chat: bool,
            ?can_comment_story: bool,
            ?can_create_promotion: bool,
            ?can_create_trial: bool,
            ?can_earn: bool,
            ?can_look_story: bool,
            ?can_pay_internal: bool,
            ?can_receive_chat_message: bool,
            ?can_report: bool,
            ?can_restrict: bool,
            ?can_trial_send: bool,
            ?can_unsubscribe: bool,
            ?current_subscribe_price: Integer,
            ?display_name: String,
            ?favorited_count: Integer,
            ?favorites_count: Integer,
            ?finished_streams_count: Integer,
            ?first_published_post_date: String,
            ?has_friends: bool,
            ?has_labels: bool,
            ?has_links: bool,
            ?has_not_viewed_story: bool,
            ?has_pinned_posts: bool,
            ?has_saved_streams: bool,
            ?has_scheduled_stream: bool,
            ?has_stories: bool,
            ?has_stream: bool,
            ?header: String,
            ?header_size: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize,
            ?header_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs,
            ?is_adult_content: bool,
            ?is_blocked: bool,
            ?is_friend: bool,
            ?is_markdown_disabled_for_about: bool,
            ?is_paywall_required: bool,
            ?is_pending_autoprolong: bool,
            ?is_performer: bool,
            ?is_private_restriction: bool,
            ?is_real_performer: bool,
            ?is_referrer_allowed: bool,
            ?is_restricted: bool,
            ?is_spotify_connected: bool,
            ?is_spring_connected: bool,
            ?is_verified: bool,
            ?join_date: String,
            ?last_seen: String,
            ?lists_states: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState],
            ?location: String,
            ?medias_count: Integer,
            ?name: String,
            ?notice: String,
            ?photos_count: Integer,
            ?posts_count: Integer,
            ?private_archived_posts_count: Integer,
            ?should_show_finished_streams: bool,
            ?show_media_count: bool,
            ?show_posts_in_feed: bool,
            ?show_subscribers_count: bool,
            ?subscribed_by: bool,
            ?subscribed_by_autoprolong: bool,
            ?subscribed_by_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData,
            ?subscribed_by_expire: bool,
            ?subscribed_by_expire_date: String,
            ?subscribed_is_expired_now: bool,
            ?subscribed_on: bool,
            ?subscribed_on_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData,
            ?subscribed_on_duration: String,
            ?subscribed_on_expired_now: bool,
            ?subscribe_price: Integer,
            ?subscribers_count: String?,
            ?tips_enabled: bool,
            ?tips_max: Integer,
            ?tips_min: Integer,
            ?tips_min_internal: Integer,
            ?tips_text_enabled: bool,
            ?username: String,
            ?videos_count: Integer,
            ?view: String,
            ?website: String?,
            ?wishlist: String?
          ) -> void

          def to_hash: -> {
            id: Integer,
            about: String,
            archived_posts_count: Integer,
            audios_count: Integer,
            avatar: String,
            avatar_header_converter_upload: bool,
            avatar_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::AvatarThumbs,
            can_add_subscriber: bool,
            can_chat: bool,
            can_comment_story: bool,
            can_create_promotion: bool,
            can_create_trial: bool,
            can_earn: bool,
            can_look_story: bool,
            can_pay_internal: bool,
            can_receive_chat_message: bool,
            can_report: bool,
            can_restrict: bool,
            can_trial_send: bool,
            can_unsubscribe: bool,
            current_subscribe_price: Integer,
            display_name: String,
            favorited_count: Integer,
            favorites_count: Integer,
            finished_streams_count: Integer,
            first_published_post_date: String,
            has_friends: bool,
            has_labels: bool,
            has_links: bool,
            has_not_viewed_story: bool,
            has_pinned_posts: bool,
            has_saved_streams: bool,
            has_scheduled_stream: bool,
            has_stories: bool,
            has_stream: bool,
            header: String,
            header_size: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderSize,
            header_thumbs: Onlyfansapi::Models::ChatListResponse::Data::Fan::HeaderThumbs,
            is_adult_content: bool,
            is_blocked: bool,
            is_friend: bool,
            is_markdown_disabled_for_about: bool,
            is_paywall_required: bool,
            is_pending_autoprolong: bool,
            is_performer: bool,
            is_private_restriction: bool,
            is_real_performer: bool,
            is_referrer_allowed: bool,
            is_restricted: bool,
            is_spotify_connected: bool,
            is_spring_connected: bool,
            is_verified: bool,
            join_date: String,
            last_seen: String,
            lists_states: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::ListsState],
            location: String,
            medias_count: Integer,
            name: String,
            notice: String,
            photos_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            should_show_finished_streams: bool,
            show_media_count: bool,
            show_posts_in_feed: bool,
            show_subscribers_count: bool,
            subscribed_by: bool,
            subscribed_by_autoprolong: bool,
            subscribed_by_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData,
            subscribed_by_expire: bool,
            subscribed_by_expire_date: String,
            subscribed_is_expired_now: bool,
            subscribed_on: bool,
            subscribed_on_data: Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData,
            subscribed_on_duration: String,
            subscribed_on_expired_now: bool,
            subscribe_price: Integer,
            subscribers_count: String?,
            tips_enabled: bool,
            tips_max: Integer,
            tips_min: Integer,
            tips_min_internal: Integer,
            tips_text_enabled: bool,
            username: String,
            videos_count: Integer,
            view: String,
            website: String?,
            wishlist: String?
          }

          type avatar_thumbs = { :c144 => String, :c50 => String }

          class AvatarThumbs < Onlyfansapi::Internal::Type::BaseModel
            attr_reader c144: String?

            def c144=: (String) -> String

            attr_reader c50: String?

            def c50=: (String) -> String

            def initialize: (?c144: String, ?c50: String) -> void

            def to_hash: -> { :c144 => String, :c50 => String }
          end

          type header_size = { height: Integer, width: Integer }

          class HeaderSize < Onlyfansapi::Internal::Type::BaseModel
            attr_reader height: Integer?

            def height=: (Integer) -> Integer

            attr_reader width: Integer?

            def width=: (Integer) -> Integer

            def initialize: (?height: Integer, ?width: Integer) -> void

            def to_hash: -> { height: Integer, width: Integer }
          end

          type header_thumbs = { :w480 => String, :w760 => String }

          class HeaderThumbs < Onlyfansapi::Internal::Type::BaseModel
            attr_reader w480: String?

            def w480=: (String) -> String

            attr_reader w760: String?

            def w760=: (String) -> String

            def initialize: (?w480: String, ?w760: String) -> void

            def to_hash: -> { :w480 => String, :w760 => String }
          end

          type lists_state =
            {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }

          class ListsState < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: String?

            def id=: (String) -> String

            attr_reader can_add_user: bool?

            def can_add_user=: (bool) -> bool

            attr_reader cannot_add_user_reason: String?

            def cannot_add_user_reason=: (String) -> String

            attr_reader has_user: bool?

            def has_user=: (bool) -> bool

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader type: String?

            def type=: (String) -> String

            def initialize: (
              ?id: String,
              ?can_add_user: bool,
              ?cannot_add_user_reason: String,
              ?has_user: bool,
              ?name: String,
              ?type: String
            ) -> void

            def to_hash: -> {
              id: String,
              can_add_user: bool,
              cannot_add_user_reason: String,
              has_user: bool,
              name: String,
              type: String
            }
          end

          type subscribed_by_data =
            {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              new_price: Integer,
              price: Integer,
              regular_price: Integer,
              renewed_at: String,
              show_posts_in_feed: bool,
              status: String?,
              subscribe_at: String,
              subscribe_price: Integer,
              subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe],
              unsubscribe_reason: String
            }

          class SubscribedByData < Onlyfansapi::Internal::Type::BaseModel
            attr_accessor discount_finished_at: String?

            attr_reader discount_percent: Integer?

            def discount_percent=: (Integer) -> Integer

            attr_reader discount_period: Integer?

            def discount_period=: (Integer) -> Integer

            attr_accessor discount_started_at: String?

            attr_reader duration: String?

            def duration=: (String) -> String

            attr_reader expired_at: String?

            def expired_at=: (String) -> String

            attr_reader has_active_paid_subscriptions: bool?

            def has_active_paid_subscriptions=: (bool) -> bool

            attr_reader is_muted: bool?

            def is_muted=: (bool) -> bool

            attr_reader new_price: Integer?

            def new_price=: (Integer) -> Integer

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader regular_price: Integer?

            def regular_price=: (Integer) -> Integer

            attr_reader renewed_at: String?

            def renewed_at=: (String) -> String

            attr_reader show_posts_in_feed: bool?

            def show_posts_in_feed=: (bool) -> bool

            attr_accessor status: String?

            attr_reader subscribe_at: String?

            def subscribe_at=: (String) -> String

            attr_reader subscribe_price: Integer?

            def subscribe_price=: (Integer) -> Integer

            attr_reader subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe]?

            def subscribes=: (
              ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe]
            ) -> ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe]

            attr_reader unsubscribe_reason: String?

            def unsubscribe_reason=: (String) -> String

            def initialize: (
              ?discount_finished_at: String?,
              ?discount_percent: Integer,
              ?discount_period: Integer,
              ?discount_started_at: String?,
              ?duration: String,
              ?expired_at: String,
              ?has_active_paid_subscriptions: bool,
              ?is_muted: bool,
              ?new_price: Integer,
              ?price: Integer,
              ?regular_price: Integer,
              ?renewed_at: String,
              ?show_posts_in_feed: bool,
              ?status: String?,
              ?subscribe_at: String,
              ?subscribe_price: Integer,
              ?subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe],
              ?unsubscribe_reason: String
            ) -> void

            def to_hash: -> {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              new_price: Integer,
              price: Integer,
              regular_price: Integer,
              renewed_at: String,
              show_posts_in_feed: bool,
              status: String?,
              subscribe_at: String,
              subscribe_price: Integer,
              subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedByData::Subscribe],
              unsubscribe_reason: String
            }

            type subscribe =
              {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }

            class Subscribe < Onlyfansapi::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader action: String?

              def action=: (String) -> String

              attr_accessor cancel_date: String?

              attr_reader date: String?

              def date=: (String) -> String

              attr_reader discount: Integer?

              def discount=: (Integer) -> Integer

              attr_reader duration: Integer?

              def duration=: (Integer) -> Integer

              attr_reader earning_id: Integer?

              def earning_id=: (Integer) -> Integer

              attr_reader expire_date: String?

              def expire_date=: (String) -> String

              attr_reader is_current: bool?

              def is_current=: (bool) -> bool

              attr_accessor offer_end: String?

              attr_accessor offer_start: String?

              attr_reader price: Integer?

              def price=: (Integer) -> Integer

              attr_reader regular_price: Integer?

              def regular_price=: (Integer) -> Integer

              attr_reader start_date: String?

              def start_date=: (String) -> String

              attr_reader subscriber_id: Integer?

              def subscriber_id=: (Integer) -> Integer

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader user_id: Integer?

              def user_id=: (Integer) -> Integer

              def initialize: (
                ?id: Integer,
                ?action: String,
                ?cancel_date: String?,
                ?date: String,
                ?discount: Integer,
                ?duration: Integer,
                ?earning_id: Integer,
                ?expire_date: String,
                ?is_current: bool,
                ?offer_end: String?,
                ?offer_start: String?,
                ?price: Integer,
                ?regular_price: Integer,
                ?start_date: String,
                ?subscriber_id: Integer,
                ?type: String,
                ?user_id: Integer
              ) -> void

              def to_hash: -> {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }
            end
          end

          type subscribed_on_data =
            {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              messages_summ: Integer,
              new_price: Integer,
              posts_summ: Integer,
              price: Integer,
              regular_price: Float,
              renewed_at: String,
              status: String?,
              streams_summ: Integer,
              subscribe_at: String,
              subscribe_price: Float,
              subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe],
              subscribes_summ: Integer,
              tips_summ: Integer,
              total_summ: Integer,
              unsubscribe_reason: String
            }

          class SubscribedOnData < Onlyfansapi::Internal::Type::BaseModel
            attr_accessor discount_finished_at: String?

            attr_reader discount_percent: Integer?

            def discount_percent=: (Integer) -> Integer

            attr_reader discount_period: Integer?

            def discount_period=: (Integer) -> Integer

            attr_accessor discount_started_at: String?

            attr_reader duration: String?

            def duration=: (String) -> String

            attr_reader expired_at: String?

            def expired_at=: (String) -> String

            attr_reader has_active_paid_subscriptions: bool?

            def has_active_paid_subscriptions=: (bool) -> bool

            attr_reader is_muted: bool?

            def is_muted=: (bool) -> bool

            attr_reader messages_summ: Integer?

            def messages_summ=: (Integer) -> Integer

            attr_reader new_price: Integer?

            def new_price=: (Integer) -> Integer

            attr_reader posts_summ: Integer?

            def posts_summ=: (Integer) -> Integer

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader regular_price: Float?

            def regular_price=: (Float) -> Float

            attr_reader renewed_at: String?

            def renewed_at=: (String) -> String

            attr_accessor status: String?

            attr_reader streams_summ: Integer?

            def streams_summ=: (Integer) -> Integer

            attr_reader subscribe_at: String?

            def subscribe_at=: (String) -> String

            attr_reader subscribe_price: Float?

            def subscribe_price=: (Float) -> Float

            attr_reader subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe]?

            def subscribes=: (
              ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe]
            ) -> ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe]

            attr_reader subscribes_summ: Integer?

            def subscribes_summ=: (Integer) -> Integer

            attr_reader tips_summ: Integer?

            def tips_summ=: (Integer) -> Integer

            attr_reader total_summ: Integer?

            def total_summ=: (Integer) -> Integer

            attr_reader unsubscribe_reason: String?

            def unsubscribe_reason=: (String) -> String

            def initialize: (
              ?discount_finished_at: String?,
              ?discount_percent: Integer,
              ?discount_period: Integer,
              ?discount_started_at: String?,
              ?duration: String,
              ?expired_at: String,
              ?has_active_paid_subscriptions: bool,
              ?is_muted: bool,
              ?messages_summ: Integer,
              ?new_price: Integer,
              ?posts_summ: Integer,
              ?price: Integer,
              ?regular_price: Float,
              ?renewed_at: String,
              ?status: String?,
              ?streams_summ: Integer,
              ?subscribe_at: String,
              ?subscribe_price: Float,
              ?subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe],
              ?subscribes_summ: Integer,
              ?tips_summ: Integer,
              ?total_summ: Integer,
              ?unsubscribe_reason: String
            ) -> void

            def to_hash: -> {
              discount_finished_at: String?,
              discount_percent: Integer,
              discount_period: Integer,
              discount_started_at: String?,
              duration: String,
              expired_at: String,
              has_active_paid_subscriptions: bool,
              is_muted: bool,
              messages_summ: Integer,
              new_price: Integer,
              posts_summ: Integer,
              price: Integer,
              regular_price: Float,
              renewed_at: String,
              status: String?,
              streams_summ: Integer,
              subscribe_at: String,
              subscribe_price: Float,
              subscribes: ::Array[Onlyfansapi::Models::ChatListResponse::Data::Fan::SubscribedOnData::Subscribe],
              subscribes_summ: Integer,
              tips_summ: Integer,
              total_summ: Integer,
              unsubscribe_reason: String
            }

            type subscribe =
              {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }

            class Subscribe < Onlyfansapi::Internal::Type::BaseModel
              attr_reader id: Integer?

              def id=: (Integer) -> Integer

              attr_reader action: String?

              def action=: (String) -> String

              attr_accessor cancel_date: String?

              attr_reader date: String?

              def date=: (String) -> String

              attr_reader discount: Integer?

              def discount=: (Integer) -> Integer

              attr_reader duration: Integer?

              def duration=: (Integer) -> Integer

              attr_reader earning_id: Integer?

              def earning_id=: (Integer) -> Integer

              attr_reader expire_date: String?

              def expire_date=: (String) -> String

              attr_reader is_current: bool?

              def is_current=: (bool) -> bool

              attr_accessor offer_end: String?

              attr_accessor offer_start: String?

              attr_reader price: Integer?

              def price=: (Integer) -> Integer

              attr_reader regular_price: Integer?

              def regular_price=: (Integer) -> Integer

              attr_reader start_date: String?

              def start_date=: (String) -> String

              attr_reader subscriber_id: Integer?

              def subscriber_id=: (Integer) -> Integer

              attr_reader type: String?

              def type=: (String) -> String

              attr_reader user_id: Integer?

              def user_id=: (Integer) -> Integer

              def initialize: (
                ?id: Integer,
                ?action: String,
                ?cancel_date: String?,
                ?date: String,
                ?discount: Integer,
                ?duration: Integer,
                ?earning_id: Integer,
                ?expire_date: String,
                ?is_current: bool,
                ?offer_end: String?,
                ?offer_start: String?,
                ?price: Integer,
                ?regular_price: Integer,
                ?start_date: String,
                ?subscriber_id: Integer,
                ?type: String,
                ?user_id: Integer
              ) -> void

              def to_hash: -> {
                id: Integer,
                action: String,
                cancel_date: String?,
                date: String,
                discount: Integer,
                duration: Integer,
                earning_id: Integer,
                expire_date: String,
                is_current: bool,
                offer_end: String?,
                offer_start: String?,
                price: Integer,
                regular_price: Integer,
                start_date: String,
                subscriber_id: Integer,
                type: String,
                user_id: Integer
              }
            end
          end
        end

        type last_message =
          {
            id: Integer,
            can_be_pinned: bool,
            cancel_seconds: Integer,
            can_purchase: bool,
            can_purchase_reason: String,
            can_report: bool,
            can_unsend_queue: bool,
            changed_at: String,
            created_at: String,
            from_user: Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser,
            giphy_id: String?,
            is_couple_people_media: bool,
            is_free: bool,
            is_from_queue: bool,
            is_liked: bool,
            is_markdown_disabled: bool,
            is_media_ready: bool,
            is_new: bool,
            is_opened: bool,
            is_pinned: bool,
            is_reported_by_me: bool,
            is_tip: bool,
            locked_text: bool,
            media: ::Array[top],
            media_count: Integer,
            previews: ::Array[top],
            price: Integer,
            queue_id: Integer,
            response_type: String,
            text: String,
            unsend_seconds_queue: Integer
          }

        class LastMessage < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader can_be_pinned: bool?

          def can_be_pinned=: (bool) -> bool

          attr_reader cancel_seconds: Integer?

          def cancel_seconds=: (Integer) -> Integer

          attr_reader can_purchase: bool?

          def can_purchase=: (bool) -> bool

          attr_reader can_purchase_reason: String?

          def can_purchase_reason=: (String) -> String

          attr_reader can_report: bool?

          def can_report=: (bool) -> bool

          attr_reader can_unsend_queue: bool?

          def can_unsend_queue=: (bool) -> bool

          attr_reader changed_at: String?

          def changed_at=: (String) -> String

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_reader from_user: Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser?

          def from_user=: (
            Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser
          ) -> Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser

          attr_accessor giphy_id: String?

          attr_reader is_couple_people_media: bool?

          def is_couple_people_media=: (bool) -> bool

          attr_reader is_free: bool?

          def is_free=: (bool) -> bool

          attr_reader is_from_queue: bool?

          def is_from_queue=: (bool) -> bool

          attr_reader is_liked: bool?

          def is_liked=: (bool) -> bool

          attr_reader is_markdown_disabled: bool?

          def is_markdown_disabled=: (bool) -> bool

          attr_reader is_media_ready: bool?

          def is_media_ready=: (bool) -> bool

          attr_reader is_new: bool?

          def is_new=: (bool) -> bool

          attr_reader is_opened: bool?

          def is_opened=: (bool) -> bool

          attr_reader is_pinned: bool?

          def is_pinned=: (bool) -> bool

          attr_reader is_reported_by_me: bool?

          def is_reported_by_me=: (bool) -> bool

          attr_reader is_tip: bool?

          def is_tip=: (bool) -> bool

          attr_reader locked_text: bool?

          def locked_text=: (bool) -> bool

          attr_reader media: ::Array[top]?

          def media=: (::Array[top]) -> ::Array[top]

          attr_reader media_count: Integer?

          def media_count=: (Integer) -> Integer

          attr_reader previews: ::Array[top]?

          def previews=: (::Array[top]) -> ::Array[top]

          attr_reader price: Integer?

          def price=: (Integer) -> Integer

          attr_reader queue_id: Integer?

          def queue_id=: (Integer) -> Integer

          attr_reader response_type: String?

          def response_type=: (String) -> String

          attr_reader text: String?

          def text=: (String) -> String

          attr_reader unsend_seconds_queue: Integer?

          def unsend_seconds_queue=: (Integer) -> Integer

          def initialize: (
            ?id: Integer,
            ?can_be_pinned: bool,
            ?cancel_seconds: Integer,
            ?can_purchase: bool,
            ?can_purchase_reason: String,
            ?can_report: bool,
            ?can_unsend_queue: bool,
            ?changed_at: String,
            ?created_at: String,
            ?from_user: Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser,
            ?giphy_id: String?,
            ?is_couple_people_media: bool,
            ?is_free: bool,
            ?is_from_queue: bool,
            ?is_liked: bool,
            ?is_markdown_disabled: bool,
            ?is_media_ready: bool,
            ?is_new: bool,
            ?is_opened: bool,
            ?is_pinned: bool,
            ?is_reported_by_me: bool,
            ?is_tip: bool,
            ?locked_text: bool,
            ?media: ::Array[top],
            ?media_count: Integer,
            ?previews: ::Array[top],
            ?price: Integer,
            ?queue_id: Integer,
            ?response_type: String,
            ?text: String,
            ?unsend_seconds_queue: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            can_be_pinned: bool,
            cancel_seconds: Integer,
            can_purchase: bool,
            can_purchase_reason: String,
            can_report: bool,
            can_unsend_queue: bool,
            changed_at: String,
            created_at: String,
            from_user: Onlyfansapi::Models::ChatListResponse::Data::LastMessage::FromUser,
            giphy_id: String?,
            is_couple_people_media: bool,
            is_free: bool,
            is_from_queue: bool,
            is_liked: bool,
            is_markdown_disabled: bool,
            is_media_ready: bool,
            is_new: bool,
            is_opened: bool,
            is_pinned: bool,
            is_reported_by_me: bool,
            is_tip: bool,
            locked_text: bool,
            media: ::Array[top],
            media_count: Integer,
            previews: ::Array[top],
            price: Integer,
            queue_id: Integer,
            response_type: String,
            text: String,
            unsend_seconds_queue: Integer
          }

          type from_user = { id: Integer, _view: String }

          class FromUser < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader _view: String?

            def _view=: (String) -> String

            def initialize: (?id: Integer, ?_view: String) -> void

            def to_hash: -> { id: Integer, _view: String }
          end
        end
      end
    end
  end
end
