module Onlyfansapi
  module Models
    type data_export_retrieve_params =
      { data_export_id: String, download_url_expires_in: Integer }
      & Onlyfansapi::Internal::Type::request_parameters

    class DataExportRetrieveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor data_export_id: String

      attr_reader download_url_expires_in: Integer?

      def download_url_expires_in=: (Integer) -> Integer

      def initialize: (
        data_export_id: String,
        ?download_url_expires_in: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        data_export_id: String,
        download_url_expires_in: Integer,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
