module Onlyfansapi
  module Models
    type fan_list_latest_params =
      {
        account: String,
        end_date: String?,
        limit: Integer,
        offset: Integer,
        start_date: String?,
        type: Onlyfansapi::Models::FanListLatestParams::type_?
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class FanListLatestParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor start_date: String?

      attr_accessor type: Onlyfansapi::Models::FanListLatestParams::type_?

      def initialize: (
        account: String,
        ?end_date: String?,
        ?limit: Integer,
        ?offset: Integer,
        ?start_date: String?,
        ?type: Onlyfansapi::Models::FanListLatestParams::type_?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String?,
        limit: Integer,
        offset: Integer,
        start_date: String?,
        type: Onlyfansapi::Models::FanListLatestParams::type_?,
        request_options: Onlyfansapi::RequestOptions
      }

      type type_ = :total | :renew | :new

      module Type
        extend Onlyfansapi::Internal::Type::Enum

        TOTAL: :total
        RENEW: :renew
        NEW: :new

        def self?.values: -> ::Array[Onlyfansapi::Models::FanListLatestParams::type_]
      end
    end
  end
end
