module Onlyfansapi
  module Models
    type fan_list_active_params =
      {
        account: String,
        filter: Onlyfansapi::FanListActiveParams::Filter,
        limit: Integer,
        offset: Integer,
        query: String?,
        type: Onlyfansapi::Models::FanListActiveParams::type_
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class FanListActiveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader filter: Onlyfansapi::FanListActiveParams::Filter?

      def filter=: (
        Onlyfansapi::FanListActiveParams::Filter
      ) -> Onlyfansapi::FanListActiveParams::Filter

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor query: String?

      attr_reader type: Onlyfansapi::Models::FanListActiveParams::type_?

      def type=: (
        Onlyfansapi::Models::FanListActiveParams::type_
      ) -> Onlyfansapi::Models::FanListActiveParams::type_

      def initialize: (
        account: String,
        ?filter: Onlyfansapi::FanListActiveParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String?,
        ?type: Onlyfansapi::Models::FanListActiveParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfansapi::FanListActiveParams::Filter,
        limit: Integer,
        offset: Integer,
        query: String?,
        type: Onlyfansapi::Models::FanListActiveParams::type_,
        request_options: Onlyfansapi::RequestOptions
      }

      type filter =
        {
          duration: Integer,
          online: Onlyfansapi::Models::FanListActiveParams::Filter::online?,
          tips: Integer,
          total_spent: Integer
        }

      class Filter < Onlyfansapi::Internal::Type::BaseModel
        attr_reader duration: Integer?

        def duration=: (Integer) -> Integer

        attr_accessor online: Onlyfansapi::Models::FanListActiveParams::Filter::online?

        attr_reader tips: Integer?

        def tips=: (Integer) -> Integer

        attr_reader total_spent: Integer?

        def total_spent=: (Integer) -> Integer

        def initialize: (
          ?duration: Integer,
          ?online: Onlyfansapi::Models::FanListActiveParams::Filter::online?,
          ?tips: Integer,
          ?total_spent: Integer
        ) -> void

        def to_hash: -> {
          duration: Integer,
          online: Onlyfansapi::Models::FanListActiveParams::Filter::online?,
          tips: Integer,
          total_spent: Integer
        }

        type online = 1 | 0

        module Online
          extend Onlyfansapi::Internal::Type::Enum

          ONLINE_1: 1
          ONLINE_0: 0

          def self?.values: -> ::Array[Onlyfansapi::Models::FanListActiveParams::Filter::online]
        end
      end

      type type_ = :active | :expired | :all

      module Type
        extend Onlyfansapi::Internal::Type::Enum

        ACTIVE: :active
        EXPIRED: :expired
        ALL: :all

        def self?.values: -> ::Array[Onlyfansapi::Models::FanListActiveParams::type_]
      end
    end
  end
end
