module Onlyfansapi
  module Models
    type following_list_expired_params =
      {
        account: String,
        filter: Onlyfansapi::FollowingListExpiredParams::Filter,
        limit: Integer,
        offset: Integer,
        query: String?
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class FollowingListExpiredParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader filter: Onlyfansapi::FollowingListExpiredParams::Filter?

      def filter=: (
        Onlyfansapi::FollowingListExpiredParams::Filter
      ) -> Onlyfansapi::FollowingListExpiredParams::Filter

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor query: String?

      def initialize: (
        account: String,
        ?filter: Onlyfansapi::FollowingListExpiredParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfansapi::FollowingListExpiredParams::Filter,
        limit: Integer,
        offset: Integer,
        query: String?,
        request_options: Onlyfansapi::RequestOptions
      }

      type filter =
        {
          online: Onlyfansapi::Models::FollowingListExpiredParams::Filter::online?,
          paid: Onlyfansapi::Models::FollowingListExpiredParams::Filter::paid?
        }

      class Filter < Onlyfansapi::Internal::Type::BaseModel
        attr_accessor online: Onlyfansapi::Models::FollowingListExpiredParams::Filter::online?

        attr_accessor paid: Onlyfansapi::Models::FollowingListExpiredParams::Filter::paid?

        def initialize: (
          ?online: Onlyfansapi::Models::FollowingListExpiredParams::Filter::online?,
          ?paid: Onlyfansapi::Models::FollowingListExpiredParams::Filter::paid?
        ) -> void

        def to_hash: -> {
          online: Onlyfansapi::Models::FollowingListExpiredParams::Filter::online?,
          paid: Onlyfansapi::Models::FollowingListExpiredParams::Filter::paid?
        }

        type online = 1 | 0

        module Online
          extend Onlyfansapi::Internal::Type::Enum

          ONLINE_1: 1
          ONLINE_0: 0

          def self?.values: -> ::Array[Onlyfansapi::Models::FollowingListExpiredParams::Filter::online]
        end

        type paid = 1 | 0

        module Paid
          extend Onlyfansapi::Internal::Type::Enum

          PAID_1: 1
          PAID_0: 0

          def self?.values: -> ::Array[Onlyfansapi::Models::FollowingListExpiredParams::Filter::paid]
        end
      end
    end
  end
end
