module Onlyfansapi
  module Models
    type mass_messaging_send_params =
      {
        account: String,
        text: String,
        excluded_lists: ::Array[String],
        giphy_id: String,
        locked_text: bool,
        media_files: ::Array[top],
        previews: ::Array[top],
        price: Integer,
        rf_guest: String,
        rf_partner: String,
        rf_tag: String,
        save_for_later: bool,
        scheduled_date: String,
        user_ids: ::Array[String],
        user_lists: ::Array[String]
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class MassMessagingSendParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor text: String

      attr_reader excluded_lists: ::Array[String]?

      def excluded_lists=: (::Array[String]) -> ::Array[String]

      attr_reader giphy_id: String?

      def giphy_id=: (String) -> String

      attr_reader locked_text: bool?

      def locked_text=: (bool) -> bool

      attr_reader media_files: ::Array[top]?

      def media_files=: (::Array[top]) -> ::Array[top]

      attr_reader previews: ::Array[top]?

      def previews=: (::Array[top]) -> ::Array[top]

      attr_reader price: Integer?

      def price=: (Integer) -> Integer

      attr_reader rf_guest: String?

      def rf_guest=: (String) -> String

      attr_reader rf_partner: String?

      def rf_partner=: (String) -> String

      attr_reader rf_tag: String?

      def rf_tag=: (String) -> String

      attr_reader save_for_later: bool?

      def save_for_later=: (bool) -> bool

      attr_reader scheduled_date: String?

      def scheduled_date=: (String) -> String

      attr_reader user_ids: ::Array[String]?

      def user_ids=: (::Array[String]) -> ::Array[String]

      attr_reader user_lists: ::Array[String]?

      def user_lists=: (::Array[String]) -> ::Array[String]

      def initialize: (
        account: String,
        text: String,
        ?excluded_lists: ::Array[String],
        ?giphy_id: String,
        ?locked_text: bool,
        ?media_files: ::Array[top],
        ?previews: ::Array[top],
        ?price: Integer,
        ?rf_guest: String,
        ?rf_partner: String,
        ?rf_tag: String,
        ?save_for_later: bool,
        ?scheduled_date: String,
        ?user_ids: ::Array[String],
        ?user_lists: ::Array[String],
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        text: String,
        excluded_lists: ::Array[String],
        giphy_id: String,
        locked_text: bool,
        media_files: ::Array[top],
        previews: ::Array[top],
        price: Integer,
        rf_guest: String,
        rf_partner: String,
        rf_tag: String,
        save_for_later: bool,
        scheduled_date: String,
        user_ids: ::Array[String],
        user_lists: ::Array[String],
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
