module Onlyfansapi
  module Models
    type mass_messaging_list_statistics_params =
      {
        account: String,
        limit: Integer,
        offset: Integer,
        query: String,
        type: Onlyfansapi::Models::MassMessagingListStatisticsParams::type_
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class MassMessagingListStatisticsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader type: Onlyfansapi::Models::MassMessagingListStatisticsParams::type_?

      def type=: (
        Onlyfansapi::Models::MassMessagingListStatisticsParams::type_
      ) -> Onlyfansapi::Models::MassMessagingListStatisticsParams::type_

      def initialize: (
        account: String,
        ?limit: Integer,
        ?offset: Integer,
        ?query: String,
        ?type: Onlyfansapi::Models::MassMessagingListStatisticsParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: Integer,
        offset: Integer,
        query: String,
        type: Onlyfansapi::Models::MassMessagingListStatisticsParams::type_,
        request_options: Onlyfansapi::RequestOptions
      }

      type type_ = :sent | :scheduled | :unsent

      module Type
        extend Onlyfansapi::Internal::Type::Enum

        SENT: :sent
        SCHEDULED: :scheduled
        UNSENT: :unsent

        def self?.values: -> ::Array[Onlyfansapi::Models::MassMessagingListStatisticsParams::type_]
      end
    end
  end
end
