module Onlyfansapi
  module Models
    type mass_messaging_retrieve_response =
      {
        _meta: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta,
        data: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data
      }

    class MassMessagingRetrieveResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta
      ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta

      attr_reader data: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data?

      def data=: (
        Onlyfansapi::Models::MassMessagingRetrieveResponse::Data
      ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta,
        ?data: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta,
        data: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache
        ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits
        ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::MassMessagingRetrieveResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          queue: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue,
          success: bool
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader queue: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue?

        def queue=: (
          Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue
        ) -> Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue

        attr_reader success: bool?

        def success=: (bool) -> bool

        def initialize: (
          ?queue: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue,
          ?success: bool
        ) -> void

        def to_hash: -> {
          queue: Onlyfansapi::Models::MassMessagingRetrieveResponse::Data::Queue,
          success: bool
        }

        type queue =
          {
            id: Integer,
            can_unsend: bool,
            date: String,
            giphy_id: String?,
            has_error: bool,
            is_canceled: bool,
            is_free: bool,
            media_types: String?,
            release_forms: ::Array[top],
            sent_count: Integer,
            text: String,
            text_cropped: String,
            unsend_seconds: Integer,
            viewed_count: Integer
          }

        class Queue < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader can_unsend: bool?

          def can_unsend=: (bool) -> bool

          attr_reader date: String?

          def date=: (String) -> String

          attr_accessor giphy_id: String?

          attr_reader has_error: bool?

          def has_error=: (bool) -> bool

          attr_reader is_canceled: bool?

          def is_canceled=: (bool) -> bool

          attr_reader is_free: bool?

          def is_free=: (bool) -> bool

          attr_accessor media_types: String?

          attr_reader release_forms: ::Array[top]?

          def release_forms=: (::Array[top]) -> ::Array[top]

          attr_reader sent_count: Integer?

          def sent_count=: (Integer) -> Integer

          attr_reader text: String?

          def text=: (String) -> String

          attr_reader text_cropped: String?

          def text_cropped=: (String) -> String

          attr_reader unsend_seconds: Integer?

          def unsend_seconds=: (Integer) -> Integer

          attr_reader viewed_count: Integer?

          def viewed_count=: (Integer) -> Integer

          def initialize: (
            ?id: Integer,
            ?can_unsend: bool,
            ?date: String,
            ?giphy_id: String?,
            ?has_error: bool,
            ?is_canceled: bool,
            ?is_free: bool,
            ?media_types: String?,
            ?release_forms: ::Array[top],
            ?sent_count: Integer,
            ?text: String,
            ?text_cropped: String,
            ?unsend_seconds: Integer,
            ?viewed_count: Integer
          ) -> void

          def to_hash: -> {
            id: Integer,
            can_unsend: bool,
            date: String,
            giphy_id: String?,
            has_error: bool,
            is_canceled: bool,
            is_free: bool,
            media_types: String?,
            release_forms: ::Array[top],
            sent_count: Integer,
            text: String,
            text_cropped: String,
            unsend_seconds: Integer,
            viewed_count: Integer
          }
        end
      end
    end
  end
end
