module Onlyfansapi
  module Models
    type me_get_model_start_date_response =
      {
        _meta: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta,
        data: Onlyfansapi::Models::MeGetModelStartDateResponse::Data
      }

    class MeGetModelStartDateResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::MeGetModelStartDateResponse::Meta
      ) -> Onlyfansapi::Models::MeGetModelStartDateResponse::Meta

      attr_reader data: Onlyfansapi::Models::MeGetModelStartDateResponse::Data?

      def data=: (
        Onlyfansapi::Models::MeGetModelStartDateResponse::Data
      ) -> Onlyfansapi::Models::MeGetModelStartDateResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta,
        ?data: Onlyfansapi::Models::MeGetModelStartDateResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta,
        data: Onlyfansapi::Models::MeGetModelStartDateResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache
        ) -> Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits
        ) -> Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::MeGetModelStartDateResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data = { start_date: String }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader start_date: String?

        def start_date=: (String) -> String

        def initialize: (?start_date: String) -> void

        def to_hash: -> { start_date: String }
      end
    end
  end
end
