module Onlyfansapi
  module Models
    type notification_search_users_response =
      {
        _meta: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta,
        data: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]
      }

    class NotificationSearchUsersResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::NotificationSearchUsersResponse::Meta
      ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Meta

      attr_reader data: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]?

      def data=: (
        ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]
      ) -> ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]

      def initialize: (
        ?_meta: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta,
        ?data: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta,
        data: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data]
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache
        ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits
        ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::NotificationSearchUsersResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          id: Integer,
          avatar: String?,
          avatar_thumbs: String?,
          can_add_subscriber: bool,
          can_comment_story: bool,
          can_earn: bool,
          can_look_story: bool,
          can_pay_internal: bool,
          can_receive_chat_message: bool,
          can_report: bool,
          can_restrict: bool,
          can_trial_send: bool,
          can_unsubscribe: bool,
          current_subscribe_price: Integer,
          display_name: String,
          has_not_viewed_story: bool,
          has_scheduled_stream: bool,
          has_stories: bool,
          has_stream: bool,
          header: String?,
          header_size: String?,
          header_thumbs: String?,
          hide_chat: bool,
          is_blocked: bool,
          is_pending_autoprolong: bool,
          is_performer: bool,
          is_real_performer: bool,
          is_restricted: bool,
          is_verified: bool,
          last_seen: String,
          lists_states: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState],
          name: String,
          notice: String,
          promo_offers: ::Array[top],
          subscribed_by: bool,
          subscribed_by_autoprolong: bool,
          subscribed_by_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData,
          subscribed_by_expire: bool,
          subscribed_by_expire_date: String,
          subscribed_is_expired_now: bool,
          subscribed_on: bool,
          subscribed_on_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData,
          subscribed_on_duration: String,
          subscribed_on_expired_now: bool,
          subscribe_price: Integer,
          tips_enabled: bool,
          tips_max: Integer,
          tips_min: Integer,
          tips_min_internal: Integer,
          tips_text_enabled: bool,
          username: String,
          view: String
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader id: Integer?

        def id=: (Integer) -> Integer

        attr_accessor avatar: String?

        attr_accessor avatar_thumbs: String?

        attr_reader can_add_subscriber: bool?

        def can_add_subscriber=: (bool) -> bool

        attr_reader can_comment_story: bool?

        def can_comment_story=: (bool) -> bool

        attr_reader can_earn: bool?

        def can_earn=: (bool) -> bool

        attr_reader can_look_story: bool?

        def can_look_story=: (bool) -> bool

        attr_reader can_pay_internal: bool?

        def can_pay_internal=: (bool) -> bool

        attr_reader can_receive_chat_message: bool?

        def can_receive_chat_message=: (bool) -> bool

        attr_reader can_report: bool?

        def can_report=: (bool) -> bool

        attr_reader can_restrict: bool?

        def can_restrict=: (bool) -> bool

        attr_reader can_trial_send: bool?

        def can_trial_send=: (bool) -> bool

        attr_reader can_unsubscribe: bool?

        def can_unsubscribe=: (bool) -> bool

        attr_reader current_subscribe_price: Integer?

        def current_subscribe_price=: (Integer) -> Integer

        attr_reader display_name: String?

        def display_name=: (String) -> String

        attr_reader has_not_viewed_story: bool?

        def has_not_viewed_story=: (bool) -> bool

        attr_reader has_scheduled_stream: bool?

        def has_scheduled_stream=: (bool) -> bool

        attr_reader has_stories: bool?

        def has_stories=: (bool) -> bool

        attr_reader has_stream: bool?

        def has_stream=: (bool) -> bool

        attr_accessor header: String?

        attr_accessor header_size: String?

        attr_accessor header_thumbs: String?

        attr_reader hide_chat: bool?

        def hide_chat=: (bool) -> bool

        attr_reader is_blocked: bool?

        def is_blocked=: (bool) -> bool

        attr_reader is_pending_autoprolong: bool?

        def is_pending_autoprolong=: (bool) -> bool

        attr_reader is_performer: bool?

        def is_performer=: (bool) -> bool

        attr_reader is_real_performer: bool?

        def is_real_performer=: (bool) -> bool

        attr_reader is_restricted: bool?

        def is_restricted=: (bool) -> bool

        attr_reader is_verified: bool?

        def is_verified=: (bool) -> bool

        attr_reader last_seen: String?

        def last_seen=: (String) -> String

        attr_reader lists_states: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState]?

        def lists_states=: (
          ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState]
        ) -> ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState]

        attr_reader name: String?

        def name=: (String) -> String

        attr_reader notice: String?

        def notice=: (String) -> String

        attr_reader promo_offers: ::Array[top]?

        def promo_offers=: (::Array[top]) -> ::Array[top]

        attr_reader subscribed_by: bool?

        def subscribed_by=: (bool) -> bool

        attr_reader subscribed_by_autoprolong: bool?

        def subscribed_by_autoprolong=: (bool) -> bool

        attr_reader subscribed_by_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData?

        def subscribed_by_data=: (
          Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData
        ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData

        attr_reader subscribed_by_expire: bool?

        def subscribed_by_expire=: (bool) -> bool

        attr_reader subscribed_by_expire_date: String?

        def subscribed_by_expire_date=: (String) -> String

        attr_reader subscribed_is_expired_now: bool?

        def subscribed_is_expired_now=: (bool) -> bool

        attr_reader subscribed_on: bool?

        def subscribed_on=: (bool) -> bool

        attr_reader subscribed_on_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData?

        def subscribed_on_data=: (
          Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData
        ) -> Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData

        attr_reader subscribed_on_duration: String?

        def subscribed_on_duration=: (String) -> String

        attr_reader subscribed_on_expired_now: bool?

        def subscribed_on_expired_now=: (bool) -> bool

        attr_reader subscribe_price: Integer?

        def subscribe_price=: (Integer) -> Integer

        attr_reader tips_enabled: bool?

        def tips_enabled=: (bool) -> bool

        attr_reader tips_max: Integer?

        def tips_max=: (Integer) -> Integer

        attr_reader tips_min: Integer?

        def tips_min=: (Integer) -> Integer

        attr_reader tips_min_internal: Integer?

        def tips_min_internal=: (Integer) -> Integer

        attr_reader tips_text_enabled: bool?

        def tips_text_enabled=: (bool) -> bool

        attr_reader username: String?

        def username=: (String) -> String

        attr_reader view: String?

        def view=: (String) -> String

        def initialize: (
          ?id: Integer,
          ?avatar: String?,
          ?avatar_thumbs: String?,
          ?can_add_subscriber: bool,
          ?can_comment_story: bool,
          ?can_earn: bool,
          ?can_look_story: bool,
          ?can_pay_internal: bool,
          ?can_receive_chat_message: bool,
          ?can_report: bool,
          ?can_restrict: bool,
          ?can_trial_send: bool,
          ?can_unsubscribe: bool,
          ?current_subscribe_price: Integer,
          ?display_name: String,
          ?has_not_viewed_story: bool,
          ?has_scheduled_stream: bool,
          ?has_stories: bool,
          ?has_stream: bool,
          ?header: String?,
          ?header_size: String?,
          ?header_thumbs: String?,
          ?hide_chat: bool,
          ?is_blocked: bool,
          ?is_pending_autoprolong: bool,
          ?is_performer: bool,
          ?is_real_performer: bool,
          ?is_restricted: bool,
          ?is_verified: bool,
          ?last_seen: String,
          ?lists_states: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState],
          ?name: String,
          ?notice: String,
          ?promo_offers: ::Array[top],
          ?subscribed_by: bool,
          ?subscribed_by_autoprolong: bool,
          ?subscribed_by_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData,
          ?subscribed_by_expire: bool,
          ?subscribed_by_expire_date: String,
          ?subscribed_is_expired_now: bool,
          ?subscribed_on: bool,
          ?subscribed_on_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData,
          ?subscribed_on_duration: String,
          ?subscribed_on_expired_now: bool,
          ?subscribe_price: Integer,
          ?tips_enabled: bool,
          ?tips_max: Integer,
          ?tips_min: Integer,
          ?tips_min_internal: Integer,
          ?tips_text_enabled: bool,
          ?username: String,
          ?view: String
        ) -> void

        def to_hash: -> {
          id: Integer,
          avatar: String?,
          avatar_thumbs: String?,
          can_add_subscriber: bool,
          can_comment_story: bool,
          can_earn: bool,
          can_look_story: bool,
          can_pay_internal: bool,
          can_receive_chat_message: bool,
          can_report: bool,
          can_restrict: bool,
          can_trial_send: bool,
          can_unsubscribe: bool,
          current_subscribe_price: Integer,
          display_name: String,
          has_not_viewed_story: bool,
          has_scheduled_stream: bool,
          has_stories: bool,
          has_stream: bool,
          header: String?,
          header_size: String?,
          header_thumbs: String?,
          hide_chat: bool,
          is_blocked: bool,
          is_pending_autoprolong: bool,
          is_performer: bool,
          is_real_performer: bool,
          is_restricted: bool,
          is_verified: bool,
          last_seen: String,
          lists_states: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::ListsState],
          name: String,
          notice: String,
          promo_offers: ::Array[top],
          subscribed_by: bool,
          subscribed_by_autoprolong: bool,
          subscribed_by_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData,
          subscribed_by_expire: bool,
          subscribed_by_expire_date: String,
          subscribed_is_expired_now: bool,
          subscribed_on: bool,
          subscribed_on_data: Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData,
          subscribed_on_duration: String,
          subscribed_on_expired_now: bool,
          subscribe_price: Integer,
          tips_enabled: bool,
          tips_max: Integer,
          tips_min: Integer,
          tips_min_internal: Integer,
          tips_text_enabled: bool,
          username: String,
          view: String
        }

        type lists_state =
          {
            id: String,
            can_add_user: bool,
            cannot_add_user_reason: String,
            has_user: bool,
            name: String,
            type: String
          }

        class ListsState < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader can_add_user: bool?

          def can_add_user=: (bool) -> bool

          attr_reader cannot_add_user_reason: String?

          def cannot_add_user_reason=: (String) -> String

          attr_reader has_user: bool?

          def has_user=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: String,
            ?can_add_user: bool,
            ?cannot_add_user_reason: String,
            ?has_user: bool,
            ?name: String,
            ?type: String
          ) -> void

          def to_hash: -> {
            id: String,
            can_add_user: bool,
            cannot_add_user_reason: String,
            has_user: bool,
            name: String,
            type: String
          }
        end

        type subscribed_by_data =
          {
            discount_finished_at: String?,
            discount_percent: Integer,
            discount_period: Integer,
            discount_started_at: String?,
            duration: String,
            expired_at: String,
            has_active_paid_subscriptions: bool,
            is_muted: bool,
            new_price: Integer,
            price: Integer,
            regular_price: Integer,
            renewed_at: String,
            show_posts_in_feed: bool,
            status: String?,
            subscribe_at: String,
            subscribe_price: Integer,
            subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe],
            unsubscribe_reason: String
          }

        class SubscribedByData < Onlyfansapi::Internal::Type::BaseModel
          attr_accessor discount_finished_at: String?

          attr_reader discount_percent: Integer?

          def discount_percent=: (Integer) -> Integer

          attr_reader discount_period: Integer?

          def discount_period=: (Integer) -> Integer

          attr_accessor discount_started_at: String?

          attr_reader duration: String?

          def duration=: (String) -> String

          attr_reader expired_at: String?

          def expired_at=: (String) -> String

          attr_reader has_active_paid_subscriptions: bool?

          def has_active_paid_subscriptions=: (bool) -> bool

          attr_reader is_muted: bool?

          def is_muted=: (bool) -> bool

          attr_reader new_price: Integer?

          def new_price=: (Integer) -> Integer

          attr_reader price: Integer?

          def price=: (Integer) -> Integer

          attr_reader regular_price: Integer?

          def regular_price=: (Integer) -> Integer

          attr_reader renewed_at: String?

          def renewed_at=: (String) -> String

          attr_reader show_posts_in_feed: bool?

          def show_posts_in_feed=: (bool) -> bool

          attr_accessor status: String?

          attr_reader subscribe_at: String?

          def subscribe_at=: (String) -> String

          attr_reader subscribe_price: Integer?

          def subscribe_price=: (Integer) -> Integer

          attr_reader subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe]?

          def subscribes=: (
            ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe]
          ) -> ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe]

          attr_reader unsubscribe_reason: String?

          def unsubscribe_reason=: (String) -> String

          def initialize: (
            ?discount_finished_at: String?,
            ?discount_percent: Integer,
            ?discount_period: Integer,
            ?discount_started_at: String?,
            ?duration: String,
            ?expired_at: String,
            ?has_active_paid_subscriptions: bool,
            ?is_muted: bool,
            ?new_price: Integer,
            ?price: Integer,
            ?regular_price: Integer,
            ?renewed_at: String,
            ?show_posts_in_feed: bool,
            ?status: String?,
            ?subscribe_at: String,
            ?subscribe_price: Integer,
            ?subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe],
            ?unsubscribe_reason: String
          ) -> void

          def to_hash: -> {
            discount_finished_at: String?,
            discount_percent: Integer,
            discount_period: Integer,
            discount_started_at: String?,
            duration: String,
            expired_at: String,
            has_active_paid_subscriptions: bool,
            is_muted: bool,
            new_price: Integer,
            price: Integer,
            regular_price: Integer,
            renewed_at: String,
            show_posts_in_feed: bool,
            status: String?,
            subscribe_at: String,
            subscribe_price: Integer,
            subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedByData::Subscribe],
            unsubscribe_reason: String
          }

          type subscribe =
            {
              id: Integer,
              action: String,
              cancel_date: String?,
              date: String,
              discount: Integer,
              duration: Integer,
              earning_id: Integer,
              expire_date: String,
              is_current: bool,
              offer_end: String?,
              offer_start: String?,
              price: Integer,
              regular_price: Integer,
              start_date: String,
              subscriber_id: Integer,
              type: String,
              user_id: Integer
            }

          class Subscribe < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader action: String?

            def action=: (String) -> String

            attr_accessor cancel_date: String?

            attr_reader date: String?

            def date=: (String) -> String

            attr_reader discount: Integer?

            def discount=: (Integer) -> Integer

            attr_reader duration: Integer?

            def duration=: (Integer) -> Integer

            attr_reader earning_id: Integer?

            def earning_id=: (Integer) -> Integer

            attr_reader expire_date: String?

            def expire_date=: (String) -> String

            attr_reader is_current: bool?

            def is_current=: (bool) -> bool

            attr_accessor offer_end: String?

            attr_accessor offer_start: String?

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader regular_price: Integer?

            def regular_price=: (Integer) -> Integer

            attr_reader start_date: String?

            def start_date=: (String) -> String

            attr_reader subscriber_id: Integer?

            def subscriber_id=: (Integer) -> Integer

            attr_reader type: String?

            def type=: (String) -> String

            attr_reader user_id: Integer?

            def user_id=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?action: String,
              ?cancel_date: String?,
              ?date: String,
              ?discount: Integer,
              ?duration: Integer,
              ?earning_id: Integer,
              ?expire_date: String,
              ?is_current: bool,
              ?offer_end: String?,
              ?offer_start: String?,
              ?price: Integer,
              ?regular_price: Integer,
              ?start_date: String,
              ?subscriber_id: Integer,
              ?type: String,
              ?user_id: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              action: String,
              cancel_date: String?,
              date: String,
              discount: Integer,
              duration: Integer,
              earning_id: Integer,
              expire_date: String,
              is_current: bool,
              offer_end: String?,
              offer_start: String?,
              price: Integer,
              regular_price: Integer,
              start_date: String,
              subscriber_id: Integer,
              type: String,
              user_id: Integer
            }
          end
        end

        type subscribed_on_data =
          {
            discount_finished_at: String?,
            discount_percent: Integer,
            discount_period: Integer,
            discount_started_at: String?,
            duration: String,
            expired_at: String,
            has_active_paid_subscriptions: bool,
            is_muted: bool,
            last_activity: String,
            messages_summ: Integer,
            new_price: Integer,
            posts_summ: Integer,
            price: Integer,
            recommendations: Integer,
            regular_price: Integer,
            renewed_at: String,
            status: String?,
            streams_summ: Integer,
            subscribe_at: String,
            subscribe_price: Integer,
            subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe],
            subscribes_summ: Integer,
            tips_summ: Integer,
            total_summ: Integer,
            unsubscribe_reason: String
          }

        class SubscribedOnData < Onlyfansapi::Internal::Type::BaseModel
          attr_accessor discount_finished_at: String?

          attr_reader discount_percent: Integer?

          def discount_percent=: (Integer) -> Integer

          attr_reader discount_period: Integer?

          def discount_period=: (Integer) -> Integer

          attr_accessor discount_started_at: String?

          attr_reader duration: String?

          def duration=: (String) -> String

          attr_reader expired_at: String?

          def expired_at=: (String) -> String

          attr_reader has_active_paid_subscriptions: bool?

          def has_active_paid_subscriptions=: (bool) -> bool

          attr_reader is_muted: bool?

          def is_muted=: (bool) -> bool

          attr_reader last_activity: String?

          def last_activity=: (String) -> String

          attr_reader messages_summ: Integer?

          def messages_summ=: (Integer) -> Integer

          attr_reader new_price: Integer?

          def new_price=: (Integer) -> Integer

          attr_reader posts_summ: Integer?

          def posts_summ=: (Integer) -> Integer

          attr_reader price: Integer?

          def price=: (Integer) -> Integer

          attr_reader recommendations: Integer?

          def recommendations=: (Integer) -> Integer

          attr_reader regular_price: Integer?

          def regular_price=: (Integer) -> Integer

          attr_reader renewed_at: String?

          def renewed_at=: (String) -> String

          attr_accessor status: String?

          attr_reader streams_summ: Integer?

          def streams_summ=: (Integer) -> Integer

          attr_reader subscribe_at: String?

          def subscribe_at=: (String) -> String

          attr_reader subscribe_price: Integer?

          def subscribe_price=: (Integer) -> Integer

          attr_reader subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe]?

          def subscribes=: (
            ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe]
          ) -> ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe]

          attr_reader subscribes_summ: Integer?

          def subscribes_summ=: (Integer) -> Integer

          attr_reader tips_summ: Integer?

          def tips_summ=: (Integer) -> Integer

          attr_reader total_summ: Integer?

          def total_summ=: (Integer) -> Integer

          attr_reader unsubscribe_reason: String?

          def unsubscribe_reason=: (String) -> String

          def initialize: (
            ?discount_finished_at: String?,
            ?discount_percent: Integer,
            ?discount_period: Integer,
            ?discount_started_at: String?,
            ?duration: String,
            ?expired_at: String,
            ?has_active_paid_subscriptions: bool,
            ?is_muted: bool,
            ?last_activity: String,
            ?messages_summ: Integer,
            ?new_price: Integer,
            ?posts_summ: Integer,
            ?price: Integer,
            ?recommendations: Integer,
            ?regular_price: Integer,
            ?renewed_at: String,
            ?status: String?,
            ?streams_summ: Integer,
            ?subscribe_at: String,
            ?subscribe_price: Integer,
            ?subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe],
            ?subscribes_summ: Integer,
            ?tips_summ: Integer,
            ?total_summ: Integer,
            ?unsubscribe_reason: String
          ) -> void

          def to_hash: -> {
            discount_finished_at: String?,
            discount_percent: Integer,
            discount_period: Integer,
            discount_started_at: String?,
            duration: String,
            expired_at: String,
            has_active_paid_subscriptions: bool,
            is_muted: bool,
            last_activity: String,
            messages_summ: Integer,
            new_price: Integer,
            posts_summ: Integer,
            price: Integer,
            recommendations: Integer,
            regular_price: Integer,
            renewed_at: String,
            status: String?,
            streams_summ: Integer,
            subscribe_at: String,
            subscribe_price: Integer,
            subscribes: ::Array[Onlyfansapi::Models::NotificationSearchUsersResponse::Data::SubscribedOnData::Subscribe],
            subscribes_summ: Integer,
            tips_summ: Integer,
            total_summ: Integer,
            unsubscribe_reason: String
          }

          type subscribe =
            {
              id: Integer,
              action: String,
              cancel_date: String?,
              date: String,
              discount: Integer,
              duration: Integer,
              earning_id: Integer,
              expire_date: String,
              is_current: bool,
              offer_end: String,
              offer_start: String,
              price: Integer,
              regular_price: Integer,
              start_date: String,
              subscriber_id: Integer,
              type: String,
              user_id: Integer
            }

          class Subscribe < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader action: String?

            def action=: (String) -> String

            attr_accessor cancel_date: String?

            attr_reader date: String?

            def date=: (String) -> String

            attr_reader discount: Integer?

            def discount=: (Integer) -> Integer

            attr_reader duration: Integer?

            def duration=: (Integer) -> Integer

            attr_reader earning_id: Integer?

            def earning_id=: (Integer) -> Integer

            attr_reader expire_date: String?

            def expire_date=: (String) -> String

            attr_reader is_current: bool?

            def is_current=: (bool) -> bool

            attr_reader offer_end: String?

            def offer_end=: (String) -> String

            attr_reader offer_start: String?

            def offer_start=: (String) -> String

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader regular_price: Integer?

            def regular_price=: (Integer) -> Integer

            attr_reader start_date: String?

            def start_date=: (String) -> String

            attr_reader subscriber_id: Integer?

            def subscriber_id=: (Integer) -> Integer

            attr_reader type: String?

            def type=: (String) -> String

            attr_reader user_id: Integer?

            def user_id=: (Integer) -> Integer

            def initialize: (
              ?id: Integer,
              ?action: String,
              ?cancel_date: String?,
              ?date: String,
              ?discount: Integer,
              ?duration: Integer,
              ?earning_id: Integer,
              ?expire_date: String,
              ?is_current: bool,
              ?offer_end: String,
              ?offer_start: String,
              ?price: Integer,
              ?regular_price: Integer,
              ?start_date: String,
              ?subscriber_id: Integer,
              ?type: String,
              ?user_id: Integer
            ) -> void

            def to_hash: -> {
              id: Integer,
              action: String,
              cancel_date: String?,
              date: String,
              discount: Integer,
              duration: Integer,
              earning_id: Integer,
              expire_date: String,
              is_current: bool,
              offer_end: String,
              offer_start: String,
              price: Integer,
              regular_price: Integer,
              start_date: String,
              subscriber_id: Integer,
              type: String,
              user_id: Integer
            }
          end
        end
      end
    end
  end
end
