module Onlyfansapi
  module Models
    type notification_list_params =
      {
        account: String,
        from_id: Integer,
        limit: Integer,
        skip_users: Onlyfansapi::Models::NotificationListParams::skip_users,
        type: Onlyfansapi::Models::NotificationListParams::type_
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class NotificationListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader from_id: Integer?

      def from_id=: (Integer) -> Integer

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader skip_users: Onlyfansapi::Models::NotificationListParams::skip_users?

      def skip_users=: (
        Onlyfansapi::Models::NotificationListParams::skip_users
      ) -> Onlyfansapi::Models::NotificationListParams::skip_users

      attr_reader type: Onlyfansapi::Models::NotificationListParams::type_?

      def type=: (
        Onlyfansapi::Models::NotificationListParams::type_
      ) -> Onlyfansapi::Models::NotificationListParams::type_

      def initialize: (
        account: String,
        ?from_id: Integer,
        ?limit: Integer,
        ?skip_users: Onlyfansapi::Models::NotificationListParams::skip_users,
        ?type: Onlyfansapi::Models::NotificationListParams::type_,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        from_id: Integer,
        limit: Integer,
        skip_users: Onlyfansapi::Models::NotificationListParams::skip_users,
        type: Onlyfansapi::Models::NotificationListParams::type_,
        request_options: Onlyfansapi::RequestOptions
      }

      type skip_users = :all | :none

      module SkipUsers
        extend Onlyfansapi::Internal::Type::Enum

        ALL: :all
        NONE: :none

        def self?.values: -> ::Array[Onlyfansapi::Models::NotificationListParams::skip_users]
      end

      type type_ =
        :all
        | :subscriptions
        | :onlyfans
        | :purchases
        | :tips
        | :tags
        | :comments
        | :mentions
        | :likes
        | :promotions

      module Type
        extend Onlyfansapi::Internal::Type::Enum

        ALL: :all
        SUBSCRIPTIONS: :subscriptions
        ONLYFANS: :onlyfans
        PURCHASES: :purchases
        TIPS: :tips
        TAGS: :tags
        COMMENTS: :comments
        MENTIONS: :mentions
        LIKES: :likes
        PROMOTIONS: :promotions

        def self?.values: -> ::Array[Onlyfansapi::Models::NotificationListParams::type_]
      end
    end
  end
end
