module Onlyfansapi
  module Models
    type payout_request_manual_withdrawal_params =
      { account: String, amount: Integer }
      & Onlyfansapi::Internal::Type::request_parameters

    class PayoutRequestManualWithdrawalParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor amount: Integer

      def initialize: (
        account: String,
        amount: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        amount: Integer,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
