module Onlyfansapi
  module Models
    type payout_list_transactions_params =
      { account: String, limit: String, marker: String }
      & Onlyfansapi::Internal::Type::request_parameters

    class PayoutListTransactionsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader limit: String?

      def limit=: (String) -> String

      attr_reader marker: String?

      def marker=: (String) -> String

      def initialize: (
        account: String,
        ?limit: String,
        ?marker: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: String,
        marker: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
