module Onlyfansapi
  module Models
    type payout_retrieve_earning_statistics_params =
      { account: String, end_date: String?, start_date: String? }
      & Onlyfansapi::Internal::Type::request_parameters

    class PayoutRetrieveEarningStatisticsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String?

      attr_accessor start_date: String?

      def initialize: (
        account: String,
        ?end_date: String?,
        ?start_date: String?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String?,
        start_date: String?,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
