module Onlyfansapi
  module Models
    type post_archive_params =
      { account: String, post_id: Integer, private_archive: bool }
      & Onlyfansapi::Internal::Type::request_parameters

    class PostArchiveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor post_id: Integer

      attr_reader private_archive: bool?

      def private_archive=: (bool) -> bool

      def initialize: (
        account: String,
        post_id: Integer,
        ?private_archive: bool,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        post_id: Integer,
        private_archive: bool,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
