module Onlyfansapi
  module Models
    type post_unarchive_response =
      {
        _meta: Onlyfansapi::Models::PostUnarchiveResponse::Meta,
        data: Onlyfansapi::Models::PostUnarchiveResponse::Data
      }

    class PostUnarchiveResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::PostUnarchiveResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::PostUnarchiveResponse::Meta
      ) -> Onlyfansapi::Models::PostUnarchiveResponse::Meta

      attr_reader data: Onlyfansapi::Models::PostUnarchiveResponse::Data?

      def data=: (
        Onlyfansapi::Models::PostUnarchiveResponse::Data
      ) -> Onlyfansapi::Models::PostUnarchiveResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::PostUnarchiveResponse::Meta,
        ?data: Onlyfansapi::Models::PostUnarchiveResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::PostUnarchiveResponse::Meta,
        data: Onlyfansapi::Models::PostUnarchiveResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache
        ) -> Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits
        ) -> Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::PostUnarchiveResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          counters: Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters,
          label_states: ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader counters: Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters?

        def counters=: (
          Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters
        ) -> Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters

        attr_reader label_states: ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]?

        def label_states=: (
          ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]
        ) -> ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]

        def initialize: (
          ?counters: Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters,
          ?label_states: ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]
        ) -> void

        def to_hash: -> {
          counters: Onlyfansapi::Models::PostUnarchiveResponse::Data::Counters,
          label_states: ::Array[Onlyfansapi::Models::PostUnarchiveResponse::Data::LabelState]
        }

        type counters =
          {
            archived_posts_count: Integer,
            audios_count: Integer,
            medias_count: Integer,
            photos_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            streams_count: Integer,
            videos_count: Integer
          }

        class Counters < Onlyfansapi::Internal::Type::BaseModel
          attr_reader archived_posts_count: Integer?

          def archived_posts_count=: (Integer) -> Integer

          attr_reader audios_count: Integer?

          def audios_count=: (Integer) -> Integer

          attr_reader medias_count: Integer?

          def medias_count=: (Integer) -> Integer

          attr_reader photos_count: Integer?

          def photos_count=: (Integer) -> Integer

          attr_reader posts_count: Integer?

          def posts_count=: (Integer) -> Integer

          attr_reader private_archived_posts_count: Integer?

          def private_archived_posts_count=: (Integer) -> Integer

          attr_reader streams_count: Integer?

          def streams_count=: (Integer) -> Integer

          attr_reader videos_count: Integer?

          def videos_count=: (Integer) -> Integer

          def initialize: (
            ?archived_posts_count: Integer,
            ?audios_count: Integer,
            ?medias_count: Integer,
            ?photos_count: Integer,
            ?posts_count: Integer,
            ?private_archived_posts_count: Integer,
            ?streams_count: Integer,
            ?videos_count: Integer
          ) -> void

          def to_hash: -> {
            archived_posts_count: Integer,
            audios_count: Integer,
            medias_count: Integer,
            photos_count: Integer,
            posts_count: Integer,
            private_archived_posts_count: Integer,
            streams_count: Integer,
            videos_count: Integer
          }
        end

        type label_state =
          {
            id: String,
            is_clear_in_progress: bool,
            name: String,
            posts: ::Array[top],
            posts_count: Integer,
            type: String
          }

        class LabelState < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader is_clear_in_progress: bool?

          def is_clear_in_progress=: (bool) -> bool

          attr_reader name: String?

          def name=: (String) -> String

          attr_reader posts: ::Array[top]?

          def posts=: (::Array[top]) -> ::Array[top]

          attr_reader posts_count: Integer?

          def posts_count=: (Integer) -> Integer

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: String,
            ?is_clear_in_progress: bool,
            ?name: String,
            ?posts: ::Array[top],
            ?posts_count: Integer,
            ?type: String
          ) -> void

          def to_hash: -> {
            id: String,
            is_clear_in_progress: bool,
            name: String,
            posts: ::Array[top],
            posts_count: Integer,
            type: String
          }
        end
      end
    end
  end
end
