module Onlyfansapi
  module Models
    type profile_retrieve_params =
      { username: String, fresh: bool? }
      & Onlyfansapi::Internal::Type::request_parameters

    class ProfileRetrieveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor username: String

      attr_accessor fresh: bool?

      def initialize: (
        username: String,
        ?fresh: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        username: String,
        fresh: bool?,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
