module Onlyfansapi
  module Models
    type promotion_list_params =
      { account: String, limit: Integer, offset: Integer }
      & Onlyfansapi::Internal::Type::request_parameters

    class PromotionListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize: (
        account: String,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: Integer,
        offset: Integer,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
