module Onlyfansapi
  module Models
    type queue_list_response =
      {
        _meta: Onlyfansapi::Models::QueueListResponse::Meta,
        data: Onlyfansapi::Models::QueueListResponse::Data
      }

    class QueueListResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::QueueListResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::QueueListResponse::Meta
      ) -> Onlyfansapi::Models::QueueListResponse::Meta

      attr_reader data: Onlyfansapi::Models::QueueListResponse::Data?

      def data=: (
        Onlyfansapi::Models::QueueListResponse::Data
      ) -> Onlyfansapi::Models::QueueListResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::QueueListResponse::Meta,
        ?data: Onlyfansapi::Models::QueueListResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::QueueListResponse::Meta,
        data: Onlyfansapi::Models::QueueListResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::QueueListResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::QueueListResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::QueueListResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::QueueListResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::QueueListResponse::Meta::Cache
        ) -> Onlyfansapi::Models::QueueListResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::QueueListResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::QueueListResponse::Meta::Credits
        ) -> Onlyfansapi::Models::QueueListResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::QueueListResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::QueueListResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::QueueListResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::QueueListResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::QueueListResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::QueueListResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::QueueListResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::QueueListResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::QueueListResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type data =
        {
          list: ::Array[Onlyfansapi::Models::QueueListResponse::Data::List],
          sync_in_process: bool
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader list: ::Array[Onlyfansapi::Models::QueueListResponse::Data::List]?

        def list=: (
          ::Array[Onlyfansapi::Models::QueueListResponse::Data::List]
        ) -> ::Array[Onlyfansapi::Models::QueueListResponse::Data::List]

        attr_reader sync_in_process: bool?

        def sync_in_process=: (bool) -> bool

        def initialize: (
          ?list: ::Array[Onlyfansapi::Models::QueueListResponse::Data::List],
          ?sync_in_process: bool
        ) -> void

        def to_hash: -> {
          list: ::Array[Onlyfansapi::Models::QueueListResponse::Data::List],
          sync_in_process: bool
        }

        type list =
          {
            id: Integer,
            created_date_time: String,
            entity: Onlyfansapi::Models::QueueListResponse::Data::List::Entity,
            publish_date_time: String,
            type: String
          }

        class List < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader created_date_time: String?

          def created_date_time=: (String) -> String

          attr_reader entity: Onlyfansapi::Models::QueueListResponse::Data::List::Entity?

          def entity=: (
            Onlyfansapi::Models::QueueListResponse::Data::List::Entity
          ) -> Onlyfansapi::Models::QueueListResponse::Data::List::Entity

          attr_reader publish_date_time: String?

          def publish_date_time=: (String) -> String

          attr_reader type: String?

          def type=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?created_date_time: String,
            ?entity: Onlyfansapi::Models::QueueListResponse::Data::List::Entity,
            ?publish_date_time: String,
            ?type: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            created_date_time: String,
            entity: Onlyfansapi::Models::QueueListResponse::Data::List::Entity,
            publish_date_time: String,
            type: String
          }

          type entity =
            {
              id: Integer,
              cancel_seconds: Integer,
              can_purchase: bool,
              can_unsend_queue: bool,
              changed_at: String,
              created_at: String,
              giphy_id: String?,
              is_free: bool,
              is_from_queue: bool,
              is_liked: bool,
              is_markdown_disabled: bool,
              is_media_ready: bool,
              is_new: bool,
              is_opened: bool,
              is_tip: bool,
              locked_text: bool,
              media: ::Array[top],
              media_count: Integer,
              previews: ::Array[top],
              price: Integer,
              queue_id: Integer,
              raw_text: String,
              release_forms: ::Array[top],
              response_type: String,
              scheduled_at: String,
              sent_rules_extra: String,
              sent_rules_type: String,
              text: String,
              unsend_seconds_queue: Integer,
              user_lists: ::Array[String]
            }

          class Entity < Onlyfansapi::Internal::Type::BaseModel
            attr_reader id: Integer?

            def id=: (Integer) -> Integer

            attr_reader cancel_seconds: Integer?

            def cancel_seconds=: (Integer) -> Integer

            attr_reader can_purchase: bool?

            def can_purchase=: (bool) -> bool

            attr_reader can_unsend_queue: bool?

            def can_unsend_queue=: (bool) -> bool

            attr_reader changed_at: String?

            def changed_at=: (String) -> String

            attr_reader created_at: String?

            def created_at=: (String) -> String

            attr_accessor giphy_id: String?

            attr_reader is_free: bool?

            def is_free=: (bool) -> bool

            attr_reader is_from_queue: bool?

            def is_from_queue=: (bool) -> bool

            attr_reader is_liked: bool?

            def is_liked=: (bool) -> bool

            attr_reader is_markdown_disabled: bool?

            def is_markdown_disabled=: (bool) -> bool

            attr_reader is_media_ready: bool?

            def is_media_ready=: (bool) -> bool

            attr_reader is_new: bool?

            def is_new=: (bool) -> bool

            attr_reader is_opened: bool?

            def is_opened=: (bool) -> bool

            attr_reader is_tip: bool?

            def is_tip=: (bool) -> bool

            attr_reader locked_text: bool?

            def locked_text=: (bool) -> bool

            attr_reader media: ::Array[top]?

            def media=: (::Array[top]) -> ::Array[top]

            attr_reader media_count: Integer?

            def media_count=: (Integer) -> Integer

            attr_reader previews: ::Array[top]?

            def previews=: (::Array[top]) -> ::Array[top]

            attr_reader price: Integer?

            def price=: (Integer) -> Integer

            attr_reader queue_id: Integer?

            def queue_id=: (Integer) -> Integer

            attr_reader raw_text: String?

            def raw_text=: (String) -> String

            attr_reader release_forms: ::Array[top]?

            def release_forms=: (::Array[top]) -> ::Array[top]

            attr_reader response_type: String?

            def response_type=: (String) -> String

            attr_reader scheduled_at: String?

            def scheduled_at=: (String) -> String

            attr_reader sent_rules_extra: String?

            def sent_rules_extra=: (String) -> String

            attr_reader sent_rules_type: String?

            def sent_rules_type=: (String) -> String

            attr_reader text: String?

            def text=: (String) -> String

            attr_reader unsend_seconds_queue: Integer?

            def unsend_seconds_queue=: (Integer) -> Integer

            attr_reader user_lists: ::Array[String]?

            def user_lists=: (::Array[String]) -> ::Array[String]

            def initialize: (
              ?id: Integer,
              ?cancel_seconds: Integer,
              ?can_purchase: bool,
              ?can_unsend_queue: bool,
              ?changed_at: String,
              ?created_at: String,
              ?giphy_id: String?,
              ?is_free: bool,
              ?is_from_queue: bool,
              ?is_liked: bool,
              ?is_markdown_disabled: bool,
              ?is_media_ready: bool,
              ?is_new: bool,
              ?is_opened: bool,
              ?is_tip: bool,
              ?locked_text: bool,
              ?media: ::Array[top],
              ?media_count: Integer,
              ?previews: ::Array[top],
              ?price: Integer,
              ?queue_id: Integer,
              ?raw_text: String,
              ?release_forms: ::Array[top],
              ?response_type: String,
              ?scheduled_at: String,
              ?sent_rules_extra: String,
              ?sent_rules_type: String,
              ?text: String,
              ?unsend_seconds_queue: Integer,
              ?user_lists: ::Array[String]
            ) -> void

            def to_hash: -> {
              id: Integer,
              cancel_seconds: Integer,
              can_purchase: bool,
              can_unsend_queue: bool,
              changed_at: String,
              created_at: String,
              giphy_id: String?,
              is_free: bool,
              is_from_queue: bool,
              is_liked: bool,
              is_markdown_disabled: bool,
              is_media_ready: bool,
              is_new: bool,
              is_opened: bool,
              is_tip: bool,
              locked_text: bool,
              media: ::Array[top],
              media_count: Integer,
              previews: ::Array[top],
              price: Integer,
              queue_id: Integer,
              raw_text: String,
              release_forms: ::Array[top],
              response_type: String,
              scheduled_at: String,
              sent_rules_extra: String,
              sent_rules_type: String,
              text: String,
              unsend_seconds_queue: Integer,
              user_lists: ::Array[String]
            }
          end
        end
      end
    end
  end
end
