module Onlyfansapi
  module Models
    type release_form_list_taggable_users_params =
      {
        account: String,
        filter: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::filter?,
        limit: Integer,
        name: String?,
        offset: Integer,
        sort: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort?,
        sort_direction: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort_direction?
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class ReleaseFormListTaggableUsersParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor filter: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::filter?

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_accessor name: String?

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      attr_accessor sort: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort?

      attr_accessor sort_direction: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort_direction?

      def initialize: (
        account: String,
        ?filter: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::filter?,
        ?limit: Integer,
        ?name: String?,
        ?offset: Integer,
        ?sort: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort?,
        ?sort_direction: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort_direction?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::filter?,
        limit: Integer,
        name: String?,
        offset: Integer,
        sort: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort?,
        sort_direction: Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort_direction?,
        request_options: Onlyfansapi::RequestOptions
      }

      type filter = :all | :pending

      module Filter
        extend Onlyfansapi::Internal::Type::Enum

        ALL: :all
        PENDING: :pending

        def self?.values: -> ::Array[Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::filter]
      end

      type sort = :date | :name

      module Sort
        extend Onlyfansapi::Internal::Type::Enum

        DATE: :date
        NAME: :name

        def self?.values: -> ::Array[Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort]
      end

      type sort_direction = :desc | :asc

      module SortDirection
        extend Onlyfansapi::Internal::Type::Enum

        DESC: :desc
        ASC: :asc

        def self?.values: -> ::Array[Onlyfansapi::Models::ReleaseFormListTaggableUsersParams::sort_direction]
      end
    end
  end
end
