module Onlyfansapi
  module Models
    type setting_check_username_exists_params =
      { account: String, username: String }
      & Onlyfansapi::Internal::Type::request_parameters

    class SettingCheckUsernameExistsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor username: String

      def initialize: (
        account: String,
        username: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        username: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
