module Onlyfansapi
  module Models
    type smart_link_postback_delete_params =
      { postback_id: Integer } & Onlyfansapi::Internal::Type::request_parameters

    class SmartLinkPostbackDeleteParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor postback_id: Integer

      def initialize: (
        postback_id: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        postback_id: Integer,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
