module Onlyfansapi
  module Models
    type smart_link_retrieve_cohort_arps_params =
      {
        smart_link_id: String,
        acquisition_end: String,
        acquisition_start: String,
        revenue_basis: Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class SmartLinkRetrieveCohortArpsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor smart_link_id: String

      attr_reader acquisition_end: String?

      def acquisition_end=: (String) -> String

      attr_reader acquisition_start: String?

      def acquisition_start=: (String) -> String

      attr_reader revenue_basis: Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis?

      def revenue_basis=: (
        Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis
      ) -> Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis

      def initialize: (
        smart_link_id: String,
        ?acquisition_end: String,
        ?acquisition_start: String,
        ?revenue_basis: Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        smart_link_id: String,
        acquisition_end: String,
        acquisition_start: String,
        revenue_basis: Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis,
        request_options: Onlyfansapi::RequestOptions
      }

      type revenue_basis = :net | :gross

      module RevenueBasis
        extend Onlyfansapi::Internal::Type::Enum

        NET: :net
        GROSS: :gross

        def self?.values: -> ::Array[Onlyfansapi::Models::SmartLinkRetrieveCohortArpsParams::revenue_basis]
      end
    end
  end
end
