module Onlyfansapi
  module Models
    type statistic_get_subscriber_metrics_params =
      { account: String, end_date: String, start_date: String, detailed: bool? }
      & Onlyfansapi::Internal::Type::request_parameters

    class StatisticGetSubscriberMetricsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String

      attr_accessor start_date: String

      attr_accessor detailed: bool?

      def initialize: (
        account: String,
        end_date: String,
        start_date: String,
        ?detailed: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String,
        start_date: String,
        detailed: bool?,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
