module Onlyfansapi
  module Models
    type statistic_get_overview_params =
      {
        account: String,
        end_date: String,
        start_date: String,
        type: Onlyfansapi::Models::StatisticGetOverviewParams::type_?
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class StatisticGetOverviewParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader end_date: String?

      def end_date=: (String) -> String

      attr_reader start_date: String?

      def start_date=: (String) -> String

      attr_accessor type: Onlyfansapi::Models::StatisticGetOverviewParams::type_?

      def initialize: (
        account: String,
        ?end_date: String,
        ?start_date: String,
        ?type: Onlyfansapi::Models::StatisticGetOverviewParams::type_?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String,
        start_date: String,
        type: Onlyfansapi::Models::StatisticGetOverviewParams::type_?,
        request_options: Onlyfansapi::RequestOptions
      }

      type type_ = :fans | :visitors | :posts | :messages

      module Type
        extend Onlyfansapi::Internal::Type::Enum

        FANS: :fans
        VISITORS: :visitors
        POSTS: :posts
        MESSAGES: :messages

        def self?.values: -> ::Array[Onlyfansapi::Models::StatisticGetOverviewParams::type_]
      end
    end
  end
end
