module Onlyfansapi
  module Models
    type stored_list_trial_links_params =
      {
        account: String,
        filter: Onlyfansapi::StoredListTrialLinksParams::Filter,
        limit: Integer,
        offset: Integer
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class StoredListTrialLinksParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader filter: Onlyfansapi::StoredListTrialLinksParams::Filter?

      def filter=: (
        Onlyfansapi::StoredListTrialLinksParams::Filter
      ) -> Onlyfansapi::StoredListTrialLinksParams::Filter

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize: (
        account: String,
        ?filter: Onlyfansapi::StoredListTrialLinksParams::Filter,
        ?limit: Integer,
        ?offset: Integer,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        filter: Onlyfansapi::StoredListTrialLinksParams::Filter,
        limit: Integer,
        offset: Integer,
        request_options: Onlyfansapi::RequestOptions
      }

      type filter =
        { include_smart_links: bool, search: String?, tags: ::Array[String] }

      class Filter < Onlyfansapi::Internal::Type::BaseModel
        attr_reader include_smart_links: bool?

        def include_smart_links=: (bool) -> bool

        attr_accessor search: String?

        attr_reader tags: ::Array[String]?

        def tags=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?include_smart_links: bool,
          ?search: String?,
          ?tags: ::Array[String]
        ) -> void

        def to_hash: -> {
          include_smart_links: bool,
          search: String?,
          tags: ::Array[String]
        }
      end
    end
  end
end
