module Onlyfansapi
  module Models
    type story_create_params =
      { account: String, media_files: ::Array[String] }
      & Onlyfansapi::Internal::Type::request_parameters

    class StoryCreateParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor media_files: ::Array[String]

      def initialize: (
        account: String,
        media_files: ::Array[String],
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        media_files: ::Array[String],
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
