module Onlyfansapi
  module Models
    type story_list_archive_params =
      { account: String, limit: Integer, marker: String }
      & Onlyfansapi::Internal::Type::request_parameters

    class StoryListArchiveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader marker: String?

      def marker=: (String) -> String

      def initialize: (
        account: String,
        ?limit: Integer,
        ?marker: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        limit: Integer,
        marker: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
