module Onlyfansapi
  module Models
    type stored_list_trial_links_response =
      {
        _meta: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta,
        _pagination: Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination,
        data: Onlyfansapi::Models::StoredListTrialLinksResponse::Data
      }

    class StoredListTrialLinksResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::StoredListTrialLinksResponse::Meta
      ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Meta

      attr_reader _pagination: Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination?

      def _pagination=: (
        Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination
      ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination

      attr_reader data: Onlyfansapi::Models::StoredListTrialLinksResponse::Data?

      def data=: (
        Onlyfansapi::Models::StoredListTrialLinksResponse::Data
      ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta,
        ?_pagination: Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination,
        ?data: Onlyfansapi::Models::StoredListTrialLinksResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta,
        _pagination: Onlyfansapi::Models::StoredListTrialLinksResponse::Pagination,
        data: Onlyfansapi::Models::StoredListTrialLinksResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache
        ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits
        ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits

        attr_reader _rate_limits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits?

        def _rate_limits=: (
          Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits
        ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits

        def initialize: (
          ?_cache: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits,
          ?_rate_limits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::Credits,
          _rate_limits: Onlyfansapi::Models::StoredListTrialLinksResponse::Meta::RateLimits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end

        type rate_limits =
          {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }

        class RateLimits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader limit_day: Integer?

          def limit_day=: (Integer) -> Integer

          attr_reader limit_minute: Integer?

          def limit_minute=: (Integer) -> Integer

          attr_reader remaining_day: Integer?

          def remaining_day=: (Integer) -> Integer

          attr_reader remaining_minute: Integer?

          def remaining_minute=: (Integer) -> Integer

          def initialize: (
            ?limit_day: Integer,
            ?limit_minute: Integer,
            ?remaining_day: Integer,
            ?remaining_minute: Integer
          ) -> void

          def to_hash: -> {
            limit_day: Integer,
            limit_minute: Integer,
            remaining_day: Integer,
            remaining_minute: Integer
          }
        end
      end

      type pagination = { next_page: String }

      class Pagination < Onlyfansapi::Internal::Type::BaseModel
        attr_reader next_page: String?

        def next_page=: (String) -> String

        def initialize: (?next_page: String) -> void

        def to_hash: -> { next_page: String }
      end

      type data =
        {
          has_more: bool,
          list: ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader has_more: bool?

        def has_more=: (bool) -> bool

        attr_reader list: ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]?

        def list=: (
          ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]
        ) -> ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]

        def initialize: (
          ?has_more: bool,
          ?list: ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]
        ) -> void

        def to_hash: -> {
          has_more: bool,
          list: ::Array[Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List]
        }

        type list =
          {
            id: Integer,
            claim_counts: Integer,
            clicks_counts: Integer,
            cost: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost,
            created_at: String,
            expired_at: String?,
            is_finished: bool,
            links: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links,
            revenue: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue,
            subscribe_counts: Integer,
            subscribe_days: Integer,
            tags: ::Array[String],
            trial_link_name: String,
            url: String
          }

        class List < Onlyfansapi::Internal::Type::BaseModel
          attr_reader id: Integer?

          def id=: (Integer) -> Integer

          attr_reader claim_counts: Integer?

          def claim_counts=: (Integer) -> Integer

          attr_reader clicks_counts: Integer?

          def clicks_counts=: (Integer) -> Integer

          attr_reader cost: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost?

          def cost=: (
            Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost
          ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost

          attr_reader created_at: String?

          def created_at=: (String) -> String

          attr_accessor expired_at: String?

          attr_reader is_finished: bool?

          def is_finished=: (bool) -> bool

          attr_reader links: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links?

          def links=: (
            Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links
          ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links

          attr_reader revenue: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue?

          def revenue=: (
            Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue
          ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue

          attr_reader subscribe_counts: Integer?

          def subscribe_counts=: (Integer) -> Integer

          attr_reader subscribe_days: Integer?

          def subscribe_days=: (Integer) -> Integer

          attr_reader tags: ::Array[String]?

          def tags=: (::Array[String]) -> ::Array[String]

          attr_reader trial_link_name: String?

          def trial_link_name=: (String) -> String

          attr_reader url: String?

          def url=: (String) -> String

          def initialize: (
            ?id: Integer,
            ?claim_counts: Integer,
            ?clicks_counts: Integer,
            ?cost: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost,
            ?created_at: String,
            ?expired_at: String?,
            ?is_finished: bool,
            ?links: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links,
            ?revenue: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue,
            ?subscribe_counts: Integer,
            ?subscribe_days: Integer,
            ?tags: ::Array[String],
            ?trial_link_name: String,
            ?url: String
          ) -> void

          def to_hash: -> {
            id: Integer,
            claim_counts: Integer,
            clicks_counts: Integer,
            cost: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Cost,
            created_at: String,
            expired_at: String?,
            is_finished: bool,
            links: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links,
            revenue: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Revenue,
            subscribe_counts: Integer,
            subscribe_days: Integer,
            tags: ::Array[String],
            trial_link_name: String,
            url: String
          }

          type cost =
            {
              click_source_count: Integer,
              input_mode: String?,
              input_value: String?,
              per_click: String?,
              per_promo: String?,
              per_sub: String?,
              subscriber_source_count: Integer
            }

          class Cost < Onlyfansapi::Internal::Type::BaseModel
            attr_reader click_source_count: Integer?

            def click_source_count=: (Integer) -> Integer

            attr_accessor input_mode: String?

            attr_accessor input_value: String?

            attr_accessor per_click: String?

            attr_accessor per_promo: String?

            attr_accessor per_sub: String?

            attr_reader subscriber_source_count: Integer?

            def subscriber_source_count=: (Integer) -> Integer

            def initialize: (
              ?click_source_count: Integer,
              ?input_mode: String?,
              ?input_value: String?,
              ?per_click: String?,
              ?per_promo: String?,
              ?per_sub: String?,
              ?subscriber_source_count: Integer
            ) -> void

            def to_hash: -> {
              click_source_count: Integer,
              input_mode: String?,
              input_value: String?,
              per_click: String?,
              per_promo: String?,
              per_sub: String?,
              subscriber_source_count: Integer
            }
          end

          type links =
            {
              related: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related
            }

          class Links < Onlyfansapi::Internal::Type::BaseModel
            attr_reader related: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related?

            def related=: (
              Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related
            ) -> Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related

            def initialize: (
              ?related: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related
            ) -> void

            def to_hash: -> {
              related: Onlyfansapi::Models::StoredListTrialLinksResponse::Data::List::Links::Related
            }

            type related = { spenders: String, subscribers: String }

            class Related < Onlyfansapi::Internal::Type::BaseModel
              attr_reader spenders: String?

              def spenders=: (String) -> String

              attr_reader subscribers: String?

              def subscribers=: (String) -> String

              def initialize: (?spenders: String, ?subscribers: String) -> void

              def to_hash: -> { spenders: String, subscribers: String }
            end
          end

          type revenue =
            {
              calculated_at: String,
              is_loading: bool,
              revenue_per_subscriber: Float,
              spenders_count: Integer,
              total: Float
            }

          class Revenue < Onlyfansapi::Internal::Type::BaseModel
            attr_reader calculated_at: String?

            def calculated_at=: (String) -> String

            attr_reader is_loading: bool?

            def is_loading=: (bool) -> bool

            attr_reader revenue_per_subscriber: Float?

            def revenue_per_subscriber=: (Float) -> Float

            attr_reader spenders_count: Integer?

            def spenders_count=: (Integer) -> Integer

            attr_reader total: Float?

            def total=: (Float) -> Float

            def initialize: (
              ?calculated_at: String,
              ?is_loading: bool,
              ?revenue_per_subscriber: Float,
              ?spenders_count: Integer,
              ?total: Float
            ) -> void

            def to_hash: -> {
              calculated_at: String,
              is_loading: bool,
              revenue_per_subscriber: Float,
              spenders_count: Integer,
              total: Float
            }
          end
        end
      end
    end
  end
end
