module Onlyfansapi
  module Models
    type tracking_link_list_params =
      {
        account: String,
        end_date: String?,
        limit: Integer?,
        offset: Integer?,
        sort: Onlyfansapi::Models::TrackingLinkListParams::sort?,
        sortby: Onlyfansapi::Models::TrackingLinkListParams::sortby?,
        start_date: String?,
        synchronous: bool?,
        with_deleted: bool?
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class TrackingLinkListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor end_date: String?

      attr_accessor limit: Integer?

      attr_accessor offset: Integer?

      attr_accessor sort: Onlyfansapi::Models::TrackingLinkListParams::sort?

      attr_accessor sortby: Onlyfansapi::Models::TrackingLinkListParams::sortby?

      attr_accessor start_date: String?

      attr_accessor synchronous: bool?

      attr_accessor with_deleted: bool?

      def initialize: (
        account: String,
        ?end_date: String?,
        ?limit: Integer?,
        ?offset: Integer?,
        ?sort: Onlyfansapi::Models::TrackingLinkListParams::sort?,
        ?sortby: Onlyfansapi::Models::TrackingLinkListParams::sortby?,
        ?start_date: String?,
        ?synchronous: bool?,
        ?with_deleted: bool?,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        end_date: String?,
        limit: Integer?,
        offset: Integer?,
        sort: Onlyfansapi::Models::TrackingLinkListParams::sort?,
        sortby: Onlyfansapi::Models::TrackingLinkListParams::sortby?,
        start_date: String?,
        synchronous: bool?,
        with_deleted: bool?,
        request_options: Onlyfansapi::RequestOptions
      }

      type sort = :desc | :asc

      module Sort
        extend Onlyfansapi::Internal::Type::Enum

        DESC: :desc
        ASC: :asc

        def self?.values: -> ::Array[Onlyfansapi::Models::TrackingLinkListParams::sort]
      end

      type sortby = :claims | :created_date

      module Sortby
        extend Onlyfansapi::Internal::Type::Enum

        CLAIMS: :claims
        CREATED_DATE: :created_date

        def self?.values: -> ::Array[Onlyfansapi::Models::TrackingLinkListParams::sortby]
      end
    end
  end
end
