module Onlyfansapi
  module Models
    type trial_link_retrieve_stats_response =
      {
        _meta: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta,
        data: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data
      }

    class TrialLinkRetrieveStatsResponse < Onlyfansapi::Internal::Type::BaseModel
      attr_reader _meta: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta?

      def _meta=: (
        Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta
      ) -> Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta

      attr_reader data: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data?

      def data=: (
        Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data
      ) -> Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data

      def initialize: (
        ?_meta: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta,
        ?data: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data
      ) -> void

      def to_hash: -> {
        _meta: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta,
        data: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data
      }

      type meta =
        {
          _cache: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits
        }

      class Meta < Onlyfansapi::Internal::Type::BaseModel
        attr_reader _cache: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache?

        def _cache=: (
          Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache
        ) -> Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache

        attr_reader _credits: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits?

        def _credits=: (
          Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits
        ) -> Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits

        def initialize: (
          ?_cache: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache,
          ?_credits: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits
        ) -> void

        def to_hash: -> {
          _cache: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Cache,
          _credits: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Meta::Credits
        }

        type cache = { is_cached: bool, note: String }

        class Cache < Onlyfansapi::Internal::Type::BaseModel
          attr_reader is_cached: bool?

          def is_cached=: (bool) -> bool

          attr_reader note: String?

          def note=: (String) -> String

          def initialize: (?is_cached: bool, ?note: String) -> void

          def to_hash: -> { is_cached: bool, note: String }
        end

        type credits = { balance: Integer, note: String, used: Integer }

        class Credits < Onlyfansapi::Internal::Type::BaseModel
          attr_reader balance: Integer?

          def balance=: (Integer) -> Integer

          attr_reader note: String?

          def note=: (String) -> String

          attr_reader used: Integer?

          def used=: (Integer) -> Integer

          def initialize: (
            ?balance: Integer,
            ?note: String,
            ?used: Integer
          ) -> void

          def to_hash: -> { balance: Integer, note: String, used: Integer }
        end
      end

      type data =
        {
          daily_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric],
          monthly_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric],
          summary: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary
        }

      class Data < Onlyfansapi::Internal::Type::BaseModel
        attr_reader daily_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric]?

        def daily_metrics=: (
          ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric]
        ) -> ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric]

        attr_reader monthly_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric]?

        def monthly_metrics=: (
          ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric]
        ) -> ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric]

        attr_reader summary: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary?

        def summary=: (
          Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary
        ) -> Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary

        def initialize: (
          ?daily_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric],
          ?monthly_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric],
          ?summary: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary
        ) -> void

        def to_hash: -> {
          daily_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::DailyMetric],
          monthly_metrics: ::Array[Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::MonthlyMetric],
          summary: Onlyfansapi::Models::TrialLinkRetrieveStatsResponse::Data::Summary
        }

        type daily_metric =
          {
            clicks: Integer,
            revenue: Float,
            spenders: Integer,
            subs: Integer,
            timestamp: String
          }

        class DailyMetric < Onlyfansapi::Internal::Type::BaseModel
          attr_reader clicks: Integer?

          def clicks=: (Integer) -> Integer

          attr_reader revenue: Float?

          def revenue=: (Float) -> Float

          attr_reader spenders: Integer?

          def spenders=: (Integer) -> Integer

          attr_reader subs: Integer?

          def subs=: (Integer) -> Integer

          attr_reader timestamp: String?

          def timestamp=: (String) -> String

          def initialize: (
            ?clicks: Integer,
            ?revenue: Float,
            ?spenders: Integer,
            ?subs: Integer,
            ?timestamp: String
          ) -> void

          def to_hash: -> {
            clicks: Integer,
            revenue: Float,
            spenders: Integer,
            subs: Integer,
            timestamp: String
          }
        end

        type monthly_metric =
          {
            clicks: Integer,
            revenue: Float,
            spenders: Integer,
            subs: Integer,
            timestamp: String
          }

        class MonthlyMetric < Onlyfansapi::Internal::Type::BaseModel
          attr_reader clicks: Integer?

          def clicks=: (Integer) -> Integer

          attr_reader revenue: Float?

          def revenue=: (Float) -> Float

          attr_reader spenders: Integer?

          def spenders=: (Integer) -> Integer

          attr_reader subs: Integer?

          def subs=: (Integer) -> Integer

          attr_reader timestamp: String?

          def timestamp=: (String) -> String

          def initialize: (
            ?clicks: Integer,
            ?revenue: Float,
            ?spenders: Integer,
            ?subs: Integer,
            ?timestamp: String
          ) -> void

          def to_hash: -> {
            clicks: Integer,
            revenue: Float,
            spenders: Integer,
            subs: Integer,
            timestamp: String
          }
        end

        type summary =
          {
            clicks_total: Integer,
            revenue_cached_at: String,
            revenue_total: Float,
            spenders_total: Integer,
            subs_total: Integer
          }

        class Summary < Onlyfansapi::Internal::Type::BaseModel
          attr_reader clicks_total: Integer?

          def clicks_total=: (Integer) -> Integer

          attr_reader revenue_cached_at: String?

          def revenue_cached_at=: (String) -> String

          attr_reader revenue_total: Float?

          def revenue_total=: (Float) -> Float

          attr_reader spenders_total: Integer?

          def spenders_total=: (Integer) -> Integer

          attr_reader subs_total: Integer?

          def subs_total=: (Integer) -> Integer

          def initialize: (
            ?clicks_total: Integer,
            ?revenue_cached_at: String,
            ?revenue_total: Float,
            ?spenders_total: Integer,
            ?subs_total: Integer
          ) -> void

          def to_hash: -> {
            clicks_total: Integer,
            revenue_cached_at: String,
            revenue_total: Float,
            spenders_total: Integer,
            subs_total: Integer
          }
        end
      end
    end
  end
end
