module Onlyfansapi
  module Models
    type trial_link_retrieve_stats_params =
      {
        account: String,
        trial_link_id: String,
        date_end: String,
        date_start: String
      }
      & Onlyfansapi::Internal::Type::request_parameters

    class TrialLinkRetrieveStatsParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor trial_link_id: String

      attr_reader date_end: String?

      def date_end=: (String) -> String

      attr_reader date_start: String?

      def date_start=: (String) -> String

      def initialize: (
        account: String,
        trial_link_id: String,
        ?date_end: String,
        ?date_start: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        trial_link_id: String,
        date_end: String,
        date_start: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
