module Onlyfansapi
  module Models
    type user_list_params =
      { account: String, ids: String }
      & Onlyfansapi::Internal::Type::request_parameters

    class UserListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor account: String

      attr_accessor ids: String

      def initialize: (
        account: String,
        ids: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        account: String,
        ids: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
