module Onlyfansapi
  module Models
    type webhook_retrieve_params =
      { webhook_id: String } & Onlyfansapi::Internal::Type::request_parameters

    class WebhookRetrieveParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      attr_accessor webhook_id: String

      def initialize: (
        webhook_id: String,
        ?request_options: Onlyfansapi::request_opts
      ) -> void

      def to_hash: -> {
        webhook_id: String,
        request_options: Onlyfansapi::RequestOptions
      }
    end
  end
end
