module Onlyfansapi
  module Models
    type webhook_list_params =
      {  } & Onlyfansapi::Internal::Type::request_parameters

    class WebhookListParams < Onlyfansapi::Internal::Type::BaseModel
      extend Onlyfansapi::Internal::Type::RequestParameters::Converter
      include Onlyfansapi::Internal::Type::RequestParameters

      def initialize: (?request_options: Onlyfansapi::request_opts) -> void

      def to_hash: -> { request_options: Onlyfansapi::RequestOptions }
    end
  end
end
