module Onlyfans
  module Models
    module SavedForLater
      type message_list_params =
        { account: String, limit: Integer, offset: Integer }
        & Onlyfans::Internal::Type::request_parameters

      class MessageListParams < Onlyfans::Internal::Type::BaseModel
        extend Onlyfans::Internal::Type::RequestParameters::Converter
        include Onlyfans::Internal::Type::RequestParameters

        attr_accessor account: String

        attr_accessor limit: Integer

        attr_accessor offset: Integer

        def initialize: (
          account: String,
          limit: Integer,
          offset: Integer,
          ?request_options: Onlyfans::request_opts
        ) -> void

        def to_hash: -> {
          account: String,
          limit: Integer,
          offset: Integer,
          request_options: Onlyfans::RequestOptions
        }
      end
    end
  end
end
