module Onlyfansapi
  module Models
    module Engagement
      module Messages
        type mass_message_list_params =
          {
            account: String,
            end_date: String,
            limit: Integer,
            query: String,
            start_date: String
          }
          & Onlyfansapi::Internal::Type::request_parameters

        class MassMessageListParams < Onlyfansapi::Internal::Type::BaseModel
          extend Onlyfansapi::Internal::Type::RequestParameters::Converter
          include Onlyfansapi::Internal::Type::RequestParameters

          attr_accessor account: String

          attr_reader end_date: String?

          def end_date=: (String) -> String

          attr_reader limit: Integer?

          def limit=: (Integer) -> Integer

          attr_reader query: String?

          def query=: (String) -> String

          attr_reader start_date: String?

          def start_date=: (String) -> String

          def initialize: (
            account: String,
            ?end_date: String,
            ?limit: Integer,
            ?query: String,
            ?start_date: String,
            ?request_options: Onlyfansapi::request_opts
          ) -> void

          def to_hash: -> {
            account: String,
            end_date: String,
            limit: Integer,
            query: String,
            start_date: String,
            request_options: Onlyfansapi::RequestOptions
          }
        end
      end
    end
  end
end
