module Onlyfansapi
  module Models
    module Engagement
      module Messages
        type mass_message_chart_response =
          {
            _meta: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta,
            data: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data
          }

        class MassMessageChartResponse < Onlyfansapi::Internal::Type::BaseModel
          attr_reader _meta: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta?

          def _meta=: (
            Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta
          ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta

          attr_reader data: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data?

          def data=: (
            Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data
          ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data

          def initialize: (
            ?_meta: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta,
            ?data: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data
          ) -> void

          def to_hash: -> {
            _meta: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta,
            data: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data
          }

          type meta =
            {
              _cache: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache,
              _credits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits,
              _rate_limits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits
            }

          class Meta < Onlyfansapi::Internal::Type::BaseModel
            attr_reader _cache: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache?

            def _cache=: (
              Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache
            ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache

            attr_reader _credits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits?

            def _credits=: (
              Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits
            ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits

            attr_reader _rate_limits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits?

            def _rate_limits=: (
              Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits
            ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits

            def initialize: (
              ?_cache: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache,
              ?_credits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits,
              ?_rate_limits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits
            ) -> void

            def to_hash: -> {
              _cache: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Cache,
              _credits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::Credits,
              _rate_limits: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Meta::RateLimits
            }

            type cache = { is_cached: bool, note: String }

            class Cache < Onlyfansapi::Internal::Type::BaseModel
              attr_reader is_cached: bool?

              def is_cached=: (bool) -> bool

              attr_reader note: String?

              def note=: (String) -> String

              def initialize: (?is_cached: bool, ?note: String) -> void

              def to_hash: -> { is_cached: bool, note: String }
            end

            type credits = { balance: Integer, note: String, used: Integer }

            class Credits < Onlyfansapi::Internal::Type::BaseModel
              attr_reader balance: Integer?

              def balance=: (Integer) -> Integer

              attr_reader note: String?

              def note=: (String) -> String

              attr_reader used: Integer?

              def used=: (Integer) -> Integer

              def initialize: (
                ?balance: Integer,
                ?note: String,
                ?used: Integer
              ) -> void

              def to_hash: -> { balance: Integer, note: String, used: Integer }
            end

            type rate_limits =
              {
                limit_day: String?,
                limit_minute: Integer,
                notice: String,
                remaining_day: String?,
                remaining_minute: Integer
              }

            class RateLimits < Onlyfansapi::Internal::Type::BaseModel
              attr_accessor limit_day: String?

              attr_reader limit_minute: Integer?

              def limit_minute=: (Integer) -> Integer

              attr_reader notice: String?

              def notice=: (String) -> String

              attr_accessor remaining_day: String?

              attr_reader remaining_minute: Integer?

              def remaining_minute=: (Integer) -> Integer

              def initialize: (
                ?limit_day: String?,
                ?limit_minute: Integer,
                ?notice: String,
                ?remaining_day: String?,
                ?remaining_minute: Integer
              ) -> void

              def to_hash: -> {
                limit_day: String?,
                limit_minute: Integer,
                notice: String,
                remaining_day: String?,
                remaining_minute: Integer
              }
            end
          end

          type data =
            {
              group_messages: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages,
              group_messages_purchases: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases
            }

          class Data < Onlyfansapi::Internal::Type::BaseModel
            attr_reader group_messages: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages?

            def group_messages=: (
              Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages
            ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages

            attr_reader group_messages_purchases: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases?

            def group_messages_purchases=: (
              Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases
            ) -> Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases

            def initialize: (
              ?group_messages: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages,
              ?group_messages_purchases: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases
            ) -> void

            def to_hash: -> {
              group_messages: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages,
              group_messages_purchases: Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases
            }

            type group_messages =
              {
                chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart],
                delta: Float,
                total: Integer
              }

            class GroupMessages < Onlyfansapi::Internal::Type::BaseModel
              attr_reader chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart]?

              def chart=: (
                ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart]
              ) -> ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart]

              attr_reader delta: Float?

              def delta=: (Float) -> Float

              attr_reader total: Integer?

              def total=: (Integer) -> Integer

              def initialize: (
                ?chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart],
                ?delta: Float,
                ?total: Integer
              ) -> void

              def to_hash: -> {
                chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessages::Chart],
                delta: Float,
                total: Integer
              }

              type chart = { count: Integer, date: String }

              class Chart < Onlyfansapi::Internal::Type::BaseModel
                attr_reader count: Integer?

                def count=: (Integer) -> Integer

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Integer, ?date: String) -> void

                def to_hash: -> { count: Integer, date: String }
              end
            end

            type group_messages_purchases =
              {
                chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart],
                delta: Float,
                total: Integer
              }

            class GroupMessagesPurchases < Onlyfansapi::Internal::Type::BaseModel
              attr_reader chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart]?

              def chart=: (
                ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart]
              ) -> ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart]

              attr_reader delta: Float?

              def delta=: (Float) -> Float

              attr_reader total: Integer?

              def total=: (Integer) -> Integer

              def initialize: (
                ?chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart],
                ?delta: Float,
                ?total: Integer
              ) -> void

              def to_hash: -> {
                chart: ::Array[Onlyfansapi::Models::Engagement::Messages::MassMessageChartResponse::Data::GroupMessagesPurchases::Chart],
                delta: Float,
                total: Integer
              }

              type chart = { count: Float, date: String }

              class Chart < Onlyfansapi::Internal::Type::BaseModel
                attr_reader count: Float?

                def count=: (Float) -> Float

                attr_reader date: String?

                def date=: (String) -> String

                def initialize: (?count: Float, ?date: String) -> void

                def to_hash: -> { count: Float, date: String }
              end
            end
          end
        end
      end
    end
  end
end
